Repository bloom-housing/bloom, pull requests merged in 2020-08, with the labels that each got.

#482 Link Common Application to a listing and fix submittal
  apps/public-reference/pages/applications/review/terms.tsx
  backend/core/client.ts
  backend/core/generate-axios-client.ts
  backend/core/seeds.json
  services/listings/listings/triton-test.json
  shared/ui-components/src/alerts/__snapshots__/AlertBox.stories.storyshot
  shared/ui-components/src/alerts/__snapshots__/AlertNotice.stories.storyshot
  shared/ui-components/src/atoms/__snapshots__/ApplicationStatus.stories.storyshot
  shared/ui-components/src/atoms/__snapshots__/Button.stories.storyshot
  shared/ui-components/src/atoms/__snapshots__/ExpandableText.stories.storyshot
  shared/ui-components/src/atoms/__snapshots__/Icon.stories.storyshot
  shared/ui-components/src/atoms/__snapshots__/LinkButton.stories.storyshot
  shared/ui-components/src/authentication/client.ts
  shared/ui-components/src/cards/__snapshots__/ImageCard.stories.storyshot
  shared/ui-components/src/cards/__snapshots__/InfoCardGrid.stories.storyshot
  shared/ui-components/src/footers/SiteFooter/__snapshots__/SiteFooter.stories.storyshot
  shared/ui-components/src/forms/__snapshots__/ProgressNav.stories.storyshot
  shared/ui-components/src/forms/__snapshots__/checkbox.stories.storyshot
  shared/ui-components/src/forms/__snapshots__/radio.stories.storyshot
  shared/ui-components/src/headers/Hero/__snapshots__/Hero.stories.storyshot
  shared/ui-components/src/headers/PageHeader/__snapshots__/PageHeader.stories.storyshot
  shared/ui-components/src/headers/SiteHeader/__snapshots__/SiteHeader.stories.storyshot
  shared/ui-components/src/lists/ResponsiveContentList/__snapshots__/ResponsiveContentList.stories.storyshot
  shared/ui-components/src/lists/__snapshots__/PreferencesList.stories.storyshot
  shared/ui-components/src/page_components/__snapshots__/HousingCounselor.stories.storyshot
  shared/ui-components/src/page_components/__snapshots__/UnitTables.stories.storyshot
  shared/ui-components/src/page_components/listing/__snapshots__/AdditionalFees.stories.storyshot
  shared/ui-components/src/page_components/listing/__snapshots__/ListingsGroup.stories.storyshot
  shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot
  shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/Apply.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/AppCard.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/AppHeader.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/AppStatusItem.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/ButtonPager.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/DashBlocks.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/HeaderBadge.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/LanguageNav.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/Modal.stories.storyshot
  shared/ui-components/src/prototypes/__snapshots__/ProgressNav.stories.storyshot
Labels: High Priority, Ready for Review

#480 Feature/demographics
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/applications/contact/address.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
  apps/public-reference/pages/applications/household/add-members.tsx
  apps/public-reference/pages/applications/household/member.tsx
  apps/public-reference/pages/applications/review/demographics.tsx
  shared/ui-components/src/cards/FormCard.scss
  shared/ui-components/src/forms/CheckboxGroup.tsx
  shared/ui-components/src/forms/Select.tsx
  shared/ui-components/src/forms/StateSelect.tsx
  shared/ui-components/src/helpers/formOptions.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/styles/forms.scss
Labels: Ready for Review

#494 Feature/preferred unit
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/applications/household/preferred-units.tsx
  shared/ui-components/src/forms/CheckboxGroup.tsx
  shared/ui-components/src/helpers/formOptions.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/styles/forms.scss
Labels: Ready for Review

#464 Add idle timeout & automatic logout
  apps/public-reference/layouts/forms.tsx
  apps/public-reference/pages/_app.jsx
  apps/public-reference/pages/_error.jsx
  apps/public-reference/pages/index.tsx
  apps/public-reference/pages/sign-in.tsx
  apps/public-reference/src/forms/applications/ApplicationTimeout.ts
  shared/ui-components/index.ts
  shared/ui-components/src/alerts/AlertBox.tsx
  shared/ui-components/src/alerts/UrlAlert.tsx
  shared/ui-components/src/alerts/index.ts
  shared/ui-components/src/authentication/UserContext.tsx
  shared/ui-components/src/authentication/client.ts
  shared/ui-components/src/authentication/index.ts
  shared/ui-components/src/authentication/timeout.tsx
  shared/ui-components/src/config/ConfigContext.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/modals/Modal.scss
  shared/ui-components/src/modals/Modal.stories.tsx
  shared/ui-components/src/modals/Modal.tsx
  shared/ui-components/src/modals/__snapshots__/Modal.stories.storyshot
  shared/ui-components/src/prototypes/Modal.scss
  shared/ui-components/src/prototypes/Modal.stories.tsx
Labels: Ready for Review

#488 Fix minor issues with Cypress for partners-reference
  apps/partners-reference/cypress/support/index.ts
  apps/partners-reference/package.json
  apps/public-reference/package.json
  backend/core/package.json
  services/listings/package.json
  shared/core/package.json
  shared/ui-components/package.json
  yarn.lock
Labels: Ready for Review

#506 Add a bunch of additional documentation
  README.md
  backend/core/README.md
  docs/Analytics.md
  docs/BuildAndRelease.md
  docs/ObjectModel.md
  docs/ObjectModelEntities.md
  docs/bloom-logo.png
Labels: Ready for Review

#504 Update to storybook 6 official + other minor dep updates
  apps/partners-reference/package.json
  apps/public-reference/package.json
  backend/core/package.json
  package.json
  services/listings/package.json
  shared/core/package.json
  shared/ui-components/package.json
  yarn.lock
Labels: Ready for Review

#489 Add the Preferences form step
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/applications/financial/income.tsx
  apps/public-reference/pages/applications/household/add-members.tsx
  apps/public-reference/pages/applications/preferences/general.tsx
  apps/public-reference/pages/applications/preferences/intro.tsx
  apps/public-reference/pages/applications/preferences/live-or-work.tsx
  apps/public-reference/pages/applications/preferences/select.tsx
  apps/public-reference/pages/applications/review/demographics.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/styles/blocks.scss
  shared/ui-components/styles/forms.scss
  shared/ui-components/styles/mixins.scss
Labels: Ready for Review

#510 Add Preferences to the Review summary
  apps/public-reference/pages/applications/financial/vouchers.tsx
  apps/public-reference/pages/applications/household/ada.tsx
  apps/public-reference/pages/applications/household/preferred-units.tsx
  apps/public-reference/pages/applications/review/summary.tsx
  shared/ui-components/src/locales/general.json
Labels: Ready for Review

#512 Feature/successful submission confirmation
  apps/public-reference/pages/applications/review/confirmation.tsx
  shared/ui-components/src/cards/FormCard.scss
  shared/ui-components/src/locales/general.json
Labels: Ready for Review

#511 Expand CircleCI Coverage to include backend/core and app builds
  .circleci/config.yml
  package.json
Labels: Ready for Review

#527 Upgrade to Bulma 0.9
  shared/ui-components/package.json
  shared/ui-components/styles/navbar.scss
  shared/ui-components/styles/utilities/_setup_bulma.scss
  yarn.lock
Labels: Ready for Review

#531 Fix adding a new household member
  apps/public-reference/pages/applications/household/add-members.tsx
Labels: Ready for Review

#495 Initial email notifications setup
  apps/public-reference/next.config.js
  backend/core/.env.template
  backend/core/package.json
  backend/core/src/auth/auth.controller.spec.ts
  backend/core/src/auth/auth.controller.ts
  backend/core/src/auth/auth.module.ts
  backend/core/src/shared/email.service.spec.ts
  backend/core/src/shared/email.service.ts
  backend/core/src/shared/shared.module.ts
  backend/core/views/register-email.hbs
  package.json
  yarn.lock
Labels: Ready for Review

#521 Styled mobile navbar
  apps/public-reference/pages/applications/review/terms.tsx
  shared/ui-components/src/forms/Field.tsx
  shared/ui-components/src/headers/SiteHeader/SiteHeader.tsx
  shared/ui-components/styles/navbar.scss
Labels: Ready for Review

#533 Do not show map if lat & lng are null
  apps/public-reference/pages/listing.tsx
Labels: Ready for Review

#544 Enable the conditional income validation
  apps/public-reference/pages/applications/financial/income.tsx
Labels: Ready for Review

#484 Basic user account
  apps/public-reference/layouts/application.tsx
  apps/public-reference/next.config.js
  apps/public-reference/package.json
  apps/public-reference/pages/account/applications.tsx
  apps/public-reference/pages/account/dashboard.tsx
  apps/public-reference/pages/account/settings.tsx
  shared/ui-components/index.ts
  shared/ui-components/src/forms/ProgressNav.tsx
  shared/ui-components/src/headers/SiteHeader/__snapshots__/SiteHeader.stories.storyshot
  shared/ui-components/src/helpers/nextjs.ts
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/page_components/AppStatusItem.scss
  shared/ui-components/src/page_components/AppStatusItem.stories.tsx
  shared/ui-components/src/page_components/AppStatusItem.tsx
  shared/ui-components/src/page_components/DashBlock.tsx
  shared/ui-components/src/page_components/DashBlocks.scss
  shared/ui-components/src/page_components/DashBlocks.stories.tsx
  shared/ui-components/src/page_components/DashBlocks.tsx
  shared/ui-components/src/page_components/HeaderBadge.scss
  shared/ui-components/src/page_components/HeaderBadge.stories.tsx
  shared/ui-components/src/page_components/HeaderBadge.tsx
  shared/ui-components/src/page_components/UserNav.tsx
  shared/ui-components/src/page_components/__snapshots__/DashBlocks.stories.storyshot
  shared/ui-components/src/page_components/__snapshots__/HeaderBadge.stories.storyshot
  shared/ui-components/src/page_components/__snapshots__/Modal.stories.storyshot
  shared/ui-components/src/prototypes/AppStatusItem.stories.tsx
  shared/ui-components/src/prototypes/DashBlocks.stories.tsx
  shared/ui-components/src/prototypes/HeaderBadge.stories.tsx
  shared/ui-components/src/prototypes/__snapshots__/Modal.stories.storyshot
Labels: Ready for Review

#522 Added basic version of redirect
  apps/public-reference/lib/hooks.ts
  apps/public-reference/pages/applications/start/choose-language.tsx
  apps/public-reference/pages/create-account.tsx
  apps/public-reference/pages/sign-in.tsx
  shared/ui-components/src/authentication/UserContext.tsx
Labels: Ready for Review

#545 Feature/accessibility modal component
  shared/ui-components/.storybook/preview-body.html
  shared/ui-components/package.json
  shared/ui-components/src/authentication/timeout.tsx
  shared/ui-components/src/helpers/useKeyPress.ts
  shared/ui-components/src/helpers/useOutsideClick.ts
  shared/ui-components/src/modals/Modal.scss
  shared/ui-components/src/modals/Modal.stories.tsx
  shared/ui-components/src/modals/Modal.tsx
  shared/ui-components/src/modals/__snapshots__/Modal.stories.storyshot
Labels: Ready for Review

#559 Minor dependency updates: late August edition
  apps/partners-reference/package.json
  apps/public-reference/package.json
  apps/public-reference/pages/_error.jsx
  backend/core/package.json
  package.json
  services/listings/package.json
  shared/core/package.json
  shared/ui-components/package.json
  shared/ui-components/tailwind.config.js
  yarn.lock
Labels: WIP

#571 Fix modal ariaDescription on My Applications page + fix tests
  apps/partners-reference/layouts/application.tsx
  apps/public-reference/cypress/integration/navigation.ts
  apps/public-reference/package.json
  apps/public-reference/pages/account/applications.tsx
  shared/ui-components/src/cards/__snapshots__/ImageCard.stories.storyshot
  shared/ui-components/src/headers/SiteHeader/SiteHeader.tsx
  shared/ui-components/src/headers/SiteHeader/__snapshots__/SiteHeader.stories.storyshot
  yarn.lock
Labels: Ready for Review

#572 add postgres to CircleCI config + associated cleanups
  .circleci/config.yml
  backend/core/test/listings/listings.e2e-spec.ts
  package.json
Labels: Ready for Review

#561 Added terms checkbox validation
  apps/public-reference/pages/applications/review/terms.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/styles/forms.scss
Labels: Ready for Review

#575 Added missing address to listing element & updated story
  shared/ui-components/src/cards/ImageCard.scss
  shared/ui-components/src/cards/ImageCard.stories.tsx
  shared/ui-components/src/cards/ImageCard.tsx
  shared/ui-components/src/cards/__snapshots__/ImageCard.stories.storyshot
  shared/ui-components/src/page_components/listing/ListingsList.tsx
Labels: Ready for Review

#578 Text tweaks to support applications pilot
  apps/public-reference/pages/applications/household/members-info.tsx
  apps/public-reference/pages/applications/household/preferred-units.tsx
  shared/ui-components/src/locales/general.json
Labels: Ready for Review

#583 Moved copyright to the translation string
  apps/public-reference/layouts/application.tsx
  shared/ui-components/src/locales/general.json
Labels: Ready for Review

#584 Added validation for email
  apps/public-reference/pages/applications/contact/name.tsx
Labels: Ready for Review
