Repository bloom-housing/bloom, pull requests merged in 2020-12, with the labels that each got.

#854 Enhancements to the partners Signin Page
  apps/partners-reference/lib/helpers.ts
  apps/partners-reference/pages/sign-in.tsx
  shared/ui-components/src/locales/general.json
Labels: Partners, WIP

#874 Feature/add application primary data
  apps/partners-reference/pages/applications.tsx
  apps/partners-reference/pages/applications/add.tsx
  apps/partners-reference/src/applications/ApplicationForm.tsx
  apps/public-reference/pages/applications/contact/name.tsx
  apps/public-reference/pages/create-account.tsx
  shared/ui-components/index.ts
  shared/ui-components/src/blocks/ViewItem.scss
  shared/ui-components/src/blocks/ViewItem.tsx
  shared/ui-components/src/blocks/__snapshots__/ViewItem.stories.storyshot
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/Field.tsx
  shared/ui-components/src/helpers/validators.ts
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/sections/__snapshots__/GridSection.stories.storyshot
Labels: ready for review

#891 Feature/paper application form
  apps/partners-reference/src/applications/ApplicationForm.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-type.tsx
  shared/ui-components/src/forms/FieldGroup.tsx
  shared/ui-components/src/global/forms.scss
  shared/ui-components/src/helpers/formOptions.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/sections/GridSection.scss
  shared/ui-components/src/sections/GridSection.tsx
Labels: ready for review

#877 Update translation files and keys
  apps/partners-reference/pages/_error.jsx
  apps/partners-reference/pages/applications/[applicationId].tsx
  apps/public-reference/pages/_error.jsx
  apps/public-reference/pages/applications/contact/address.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-name.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-type.tsx
  apps/public-reference/pages/applications/contact/name.tsx
  apps/public-reference/pages/applications/financial/income.tsx
  apps/public-reference/pages/applications/financial/vouchers.tsx
  apps/public-reference/pages/applications/household/ada.tsx
  apps/public-reference/pages/applications/household/member.tsx
  apps/public-reference/pages/applications/household/members-info.tsx
  apps/public-reference/pages/applications/household/preferred-units.tsx
  apps/public-reference/pages/applications/preferences/select.tsx
  apps/public-reference/pages/applications/review/confirmation.tsx
  apps/public-reference/pages/applications/review/demographics.tsx
  apps/public-reference/pages/applications/review/terms.tsx
  apps/public-reference/pages/applications/start/choose-language.tsx
  apps/public-reference/pages/listing.tsx
  apps/public-reference/src/forms/applications/ApplicationTimeout.ts
  apps/public-reference/src/forms/applications/FormSummaryDetails.tsx
  shared/ui-components/README.md
  shared/ui-components/src/actions/ExpandableText.tsx
  shared/ui-components/src/authentication/timeout.tsx
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/HouseholdMemberForm.tsx
  shared/ui-components/src/forms/HouseholdSizeField.tsx
  shared/ui-components/src/helpers/occupancyFormatting.tsx
  shared/ui-components/src/helpers/tableSummaries.tsx
  shared/ui-components/src/locales/es.json
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/locales/general_OLD.json
  shared/ui-components/src/locales/vi.json
  shared/ui-components/src/locales/zh.json
  shared/ui-components/src/page_components/listing/ListingsList.tsx
  shared/ui-components/src/page_components/listing/UnitTables.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/SidebarAddress.tsx
Labels: WIP

#912 Feature/date time field
  shared/ui-components/index.ts
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/Field.tsx
  shared/ui-components/src/forms/Select.tsx
  shared/ui-components/src/forms/TimeField.stories.tsx
  shared/ui-components/src/forms/TimeField.tsx
  shared/ui-components/src/forms/__snapshots__/DOBField.stories.storyshot
  shared/ui-components/src/forms/__snapshots__/TimeField.stories.storyshot
  shared/ui-components/src/global/forms.scss
  shared/ui-components/src/locales/general.json
Labels: ready for review

#917 Add StatusAside component and place on the New/Edit Application form
  apps/partners-reference/src/applications/ApplicationForm.tsx
  shared/ui-components/index.ts
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/notifications/StatusAside.scss
  shared/ui-components/src/notifications/StatusAside.stories.tsx
  shared/ui-components/src/notifications/StatusAside.tsx
  shared/ui-components/src/notifications/StatusMessage.tsx
  shared/ui-components/src/notifications/__snapshots__/StatusAside.stories.storyshot
  shared/ui-components/src/notifications/__snapshots__/StatusMessages.stories.storyshot
Labels: ready for review

#907 Feature/paper add members
  apps/partners-reference/pages/applications/add.tsx
  apps/partners-reference/src/applications/ApplicationForm/ApplicationForm.tsx
  apps/partners-reference/src/applications/ApplicationForm/ApplicationFormAddress.tsx
  apps/partners-reference/src/applications/ApplicationForm/ApplicationFormMember.tsx
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/lib/ApplicationConductor.ts
  apps/public-reference/pages/_app.jsx
  apps/public-reference/pages/applications/contact/address.tsx
  apps/public-reference/pages/applications/household/member.tsx
  shared/core/index.ts
  shared/core/src/Member.ts
  shared/ui-components/index.ts
  shared/ui-components/src/actions/Button.scss
  shared/ui-components/src/forms/FieldGroup.tsx
  shared/ui-components/src/helpers/blankApplication.ts
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/overlays/Modal.scss
Labels: ready for review
