Repository bloom-housing/bloom, pull requests merged in 2020-11, with the labels that each got.

#784 Fix frontend typings (make use of autogenerated interfaces)
  .eslintrc.js
  apps/partners-reference/lib/hooks.ts
  apps/partners-reference/pages/applications.tsx
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/account/applications.tsx
  apps/public-reference/pages/applications/financial/income.tsx
  backend/core/client.ts
  backend/core/generate-axios-client.ts
  backend/core/src/applications/application.dto.ts
  backend/core/src/applications/applications.controller.ts
  backend/core/src/entity/application-method.entity.ts
  backend/core/src/entity/application.entity.ts
  backend/core/src/entity/listing-event.entity.ts
  backend/core/src/entity/listing.entity.ts
  backend/core/src/entity/unit.entity.ts
  backend/core/src/lib/unit_transformations.ts
  backend/core/src/listings/listing.dto.ts
  backend/core/src/migration/1603449837150-fix-integer-types-in-listing.ts
  backend/core/src/seed.ts
  backend/core/src/shared/dto/address.dto.ts
  backend/core/src/user/user.controller.ts
  backend/core/test/applications/applications.e2e-spec.ts
  shared/core/index.ts
  shared/core/src/ami_charts.ts
  shared/core/src/assets.ts
  shared/core/src/backend-swagger.ts
  shared/core/src/general.ts
  shared/core/src/listings.ts
  shared/core/src/preferences.ts
  shared/core/src/units.ts
  shared/ui-components/__tests__/authentication/RequireLogin.test.tsx
  shared/ui-components/src/authentication/UserContext.tsx
  shared/ui-components/src/authentication/api_requests.ts
  shared/ui-components/src/authentication/client.ts
  shared/ui-components/src/blocks/AppStatusItem.stories.tsx
  shared/ui-components/src/blocks/AppStatusItem.tsx
  shared/ui-components/src/blocks/__snapshots__/AppStatusItem.stories.storyshot
  shared/ui-components/src/page_components/listing/AdditionalFees.tsx
  shared/ui-components/src/page_components/listing/ListingsList.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/Apply.stories.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/Apply.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/Apply.stories.storyshot
Labels: in-development

#796 Add search query param to GET /applications and fix some missing @Exp…
  backend/core/src/applications/application.dto.ts
  backend/core/src/applications/applications.service.ts
  backend/core/src/entity/listing.entity.ts
  backend/core/src/migration/1604317983218-add-application-data-index.ts
  shared/core/src/backend-swagger.ts
Labels: ready for development

#823 Fixed infinity loop
  apps/public-reference/pages/applications/start/choose-language.tsx
Labels: bug

#813 Add application submission type, language and status
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/applications/household/member.tsx
  apps/public-reference/pages/applications/review/terms.tsx
  backend/core/client.ts
  backend/core/src/applications/application.dto.ts
  backend/core/src/applications/applications.service.ts
  backend/core/src/entity/application.entity.ts
  backend/core/test/applications/applications.e2e-spec.ts
  shared/core/src/backend-swagger.ts
Labels: Ready for Review

#789 Add authz tests
  backend/core/src/app.module.ts
  backend/core/src/application-methods/application-methods.controller.ts
  backend/core/src/assets/assets.controller.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/listing-events/listing-events.controller.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/main.ts
  backend/core/src/preferences/preferences.controller.ts
  backend/core/src/units/units.controller.ts
  backend/core/src/user/user.controller.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/assets/assets.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
Labels: Ready for Review

#552 Feature/lang nav
  apps/public-reference/.env.template
  apps/public-reference/layouts/application.tsx
  apps/public-reference/next.config.js
  shared/ui-components/index.ts
  shared/ui-components/src/headers/SiteHeader.stories.tsx
  shared/ui-components/src/headers/SiteHeader.tsx
  shared/ui-components/src/headers/__snapshots__/SiteHeader.stories.storyshot
  shared/ui-components/src/helpers/useLanguageChange.ts
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/navigation/LanguageNav.scss
  shared/ui-components/src/navigation/LanguageNav.stories.tsx
  shared/ui-components/src/navigation/LanguageNav.tsx
  shared/ui-components/src/navigation/__snapshots__/LanguageNav.stories.storyshot
  shared/ui-components/src/prototypes/LanguageNav.stories.tsx
  shared/ui-components/src/prototypes/LanguageNav.tsx
  shared/ui-components/src/prototypes/__snapshots__/LanguageNav.stories.storyshot
Labels: Ready for Review

#731 Feature/application form tests
  .circleci/config.yml
  apps/public-reference/cypress/fixtures/applicationConfigBlank.json
  apps/public-reference/cypress/fixtures/applicationConfigFilled.json
  apps/public-reference/cypress/fixtures/applications/ada.json
  apps/public-reference/cypress/fixtures/applications/address.json
  apps/public-reference/cypress/fixtures/applications/alternate-contact-contact.json
  apps/public-reference/cypress/fixtures/applications/alternate-contact-name.json
  apps/public-reference/cypress/fixtures/applications/alternate-contact-type.json
  apps/public-reference/cypress/fixtures/applications/demographics.json
  apps/public-reference/cypress/fixtures/applications/income.json
  apps/public-reference/cypress/fixtures/applications/member.json
  apps/public-reference/cypress/fixtures/applications/name.json
  apps/public-reference/cypress/fixtures/applications/summary.json
  apps/public-reference/cypress/fixtures/example.json
  apps/public-reference/cypress/fixtures/listing.json
  apps/public-reference/cypress/fixtures/listingConfig.json
  apps/public-reference/cypress/fixtures/routes.json
  apps/public-reference/cypress/integration/pages/ApplicationForms.ts
  apps/public-reference/cypress/integration/pages/application/contact/address.spec.ts
  apps/public-reference/cypress/integration/pages/application/contact/alternate-contact-contact.spec.ts
  apps/public-reference/cypress/integration/pages/application/contact/alternate-contact-name.spec.ts
  apps/public-reference/cypress/integration/pages/application/contact/alternate-contact-type.spec.ts
  apps/public-reference/cypress/integration/pages/application/contact/name.spec.ts
  apps/public-reference/cypress/integration/pages/application/financial/income.spec.ts
  apps/public-reference/cypress/integration/pages/application/financial/vouchers.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/ada.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/add-members.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/live-alone.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/member.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/members-info.spec.ts
  apps/public-reference/cypress/integration/pages/application/household/preferred-units.spec.ts
  apps/public-reference/cypress/integration/pages/application/preferences/general.spec.ts
  apps/public-reference/cypress/integration/pages/application/preferences/select.spec.ts
  apps/public-reference/cypress/integration/pages/application/review/confirmation.spec.ts
  apps/public-reference/cypress/integration/pages/application/review/demographics.spec.ts
  apps/public-reference/cypress/integration/pages/application/review/summary.spec.ts
  apps/public-reference/cypress/integration/pages/application/review/terms.spec.ts
  apps/public-reference/cypress/integration/pages/application/start/choose-language.ts
  apps/public-reference/cypress/support/commands.js
  apps/public-reference/cypress/support/index.d.ts
  apps/public-reference/pages/applications/contact/address.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-type.tsx
  apps/public-reference/pages/applications/contact/name.tsx
  apps/public-reference/pages/applications/household/add-members.tsx
  apps/public-reference/pages/applications/household/live-alone.tsx
  apps/public-reference/pages/applications/household/member.tsx
  apps/public-reference/pages/applications/preferences/select.tsx
  apps/public-reference/pages/applications/review/confirmation.tsx
  apps/public-reference/pages/applications/start/choose-language.tsx
  apps/public-reference/src/forms/applications/FormSummaryDetails.tsx
  shared/ui-components/src/actions/Button.tsx
  shared/ui-components/src/blocks/AppStatusItem.tsx
  shared/ui-components/src/blocks/ViewItem.tsx
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/Form.tsx
  shared/ui-components/src/forms/HouseholdMemberForm.tsx
  shared/ui-components/src/forms/PhoneField.tsx
  shared/ui-components/src/forms/Select.tsx
Labels: Ready for Review

#792 Feature/partners listing applications
  apps/partners-reference/lib/hooks.ts
  apps/partners-reference/next.config.js
  apps/partners-reference/package.json
  apps/partners-reference/page_content/locale_overrides/general.json
  apps/partners-reference/pages/applications.tsx
  apps/partners-reference/pages/applications/[applicationId].tsx
  apps/partners-reference/pages/listings.tsx
  apps/partners-reference/public/images/icons.svg
  apps/public-reference/pages/applications/contact/name.tsx
  apps/public-reference/pages/applications/household/member.tsx
  backend/core/client.ts
  shared/ui-components/index.ts
  shared/ui-components/public/images/icons.svg
  shared/ui-components/src/actions/Button.scss
  shared/ui-components/src/actions/Button.tsx
  shared/ui-components/src/actions/InlineButton.scss
  shared/ui-components/src/actions/InlineButton.tsx
  shared/ui-components/src/elements/Tag.scss
  shared/ui-components/src/elements/Tag.stories.tsx
  shared/ui-components/src/elements/Tag.tsx
  shared/ui-components/src/global/blocks.scss
  shared/ui-components/src/global/mixins.scss
  shared/ui-components/src/helpers/debounce.ts
  shared/ui-components/src/icons/Icon.tsx
  shared/ui-components/src/locales/general.json
  shared/ui-components/src/sections/GridSection.scss
  yarn.lock
Labels: WIP

#843 Split out applicants from Applications
  apps/partners-reference/pages/applications/[applicationId].tsx
  apps/public-reference/lib/AppSubmissionContext.ts
  apps/public-reference/pages/applications/household/member.tsx
  apps/public-reference/pages/applications/review/terms.tsx
  apps/public-reference/pages/applications/start/choose-language.tsx
  apps/public-reference/pages/index.tsx
  backend/core/archer.ts
  backend/core/client.ts
  backend/core/ormconfig.test.ts
  backend/core/ormconfig.ts
  backend/core/src/applications/application.dto.ts
  backend/core/src/applications/applications.controller.ts
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/applications.service.ts
  backend/core/src/applications/dto/accessibility.dto.ts
  backend/core/src/applications/dto/alternate-contact.dto.ts
  backend/core/src/applications/dto/applicant.dto.ts
  backend/core/src/applications/dto/application-preferences.dto.ts
  backend/core/src/applications/dto/application.dto.ts
  backend/core/src/applications/dto/demographics.dto.ts
  backend/core/src/applications/dto/household-member.dto.ts
  backend/core/src/applications/dto/housing-counselor.dto.ts
  backend/core/src/applications/entities/accessibility.entity.ts
  backend/core/src/applications/entities/alternate-contact.entity.ts
  backend/core/src/applications/entities/applicant.entity.ts
  backend/core/src/applications/entities/application-preferences.entity.ts
  backend/core/src/applications/entities/application.entity.ts
  backend/core/src/applications/entities/demographics.entity.ts
  backend/core/src/applications/entities/household-member.entity.ts
  backend/core/src/entity/application.entity.ts
  backend/core/src/entity/listing.entity.ts
  backend/core/src/entity/property.entity.ts
  backend/core/src/entity/user.entity.ts
  backend/core/src/listings/listing.dto.ts
  backend/core/src/migration/1605691160237-add-application-data.ts
  backend/core/src/property/property.dto.ts
  backend/core/src/seed.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeds/listings.ts
  backend/core/src/shared/dto/address.dto.ts
  backend/core/src/shared/email.service.spec.ts
  backend/core/src/shared/email.service.ts
  backend/core/src/shared/entities/abstract.entity.ts
  backend/core/src/shared/entities/address.entity.ts
  backend/core/test/applications/applications.e2e-spec.ts
  shared/core/src/archer-listing.ts
  shared/core/src/backend-swagger.ts
  shared/ui-components/src/blocks/AppStatusItem.tsx
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/HouseholdMemberForm.tsx
  shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/ApplicationSection.stories.storyshot
  shared/ui-components/src/page_components/listing/listing_sidebar/__snapshots__/Apply.stories.storyshot
Labels: ready for review

#824 Create ami charts table
  apps/public-reference/pages/applications/start/choose-language.tsx
  apps/public-reference/pages/index.tsx
  apps/public-reference/pages/listing.tsx
  apps/public-reference/pages/listings.tsx
  backend/core/ami_charts/AlamedaCountyLIHTC2020.json
  backend/core/ami_charts/AlamedaCountyTCAC2019.json
  backend/core/ami_charts/AlamedaCountyTCAC2020.json
  backend/core/ami_charts/OaklandFremontHUD2020.json
  backend/core/ami_charts/SanJoseTCAC2019.json
  backend/core/ami_charts/SanMateoCountyTCAC2019.json
  backend/core/ami_charts/SanMateoCountyTCAC2020.json
  backend/core/ami_charts/SanMateoHERASpecial2019.json
  backend/core/ami_charts/SanMateoHOME2019.json
  backend/core/ami_charts/SanMateoHUD2019.json
  backend/core/ami_charts/SanMateoHUD2020.json
  backend/core/client.ts
  backend/core/src/ami-charts/ami-chart.dto.ts
  backend/core/src/ami-charts/ami-charts.controller.ts
  backend/core/src/ami-charts/ami-charts.module.ts
  backend/core/src/ami-charts/ami-charts.service.ts
  backend/core/src/app.module.ts
  backend/core/src/applications/entities/applicant.entity.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/entity/ami-chart-item.entity.ts
  backend/core/src/entity/ami-chart.entity.ts
  backend/core/src/entity/property.entity.ts
  backend/core/src/entity/unit.entity.ts
  backend/core/src/lib/ami_charts.ts
  backend/core/src/lib/unit_transformations.ts
  backend/core/src/listings/listing.dto.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/migration/1604932002979-add-ami-chart.ts
  backend/core/src/migration/1605691160237-add-application-data.ts
  backend/core/src/property/property.dto.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyLIHTC2020.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyTCAC2019.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyTCAC2020.ts
  backend/core/src/seeds/ami-charts/OaklandFremontHUD2020.ts
  backend/core/src/seeds/ami-charts/SanJoseTCAC2019.ts
  backend/core/src/seeds/ami-charts/SanMateoCountyTCAC2019.ts
  backend/core/src/seeds/ami-charts/SanMateoCountyTCAC2020.ts
  backend/core/src/seeds/ami-charts/SanMateoHERASpecial2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHOME2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHUD2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHUD2020.ts
  backend/core/src/seeds/ami-charts/index.ts
  backend/core/src/seeds/listings.ts
  backend/core/src/shared/abstract-service.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  shared/core/src/backend-swagger.ts
Labels: ready for review

#862 Fix scrolling issue with Overlay
  shared/ui-components/src/overlays/Drawer.stories.tsx
  shared/ui-components/src/overlays/Overlay.tsx
Labels: bug, ready for review

#856 Feature/application details cleanup
  apps/partners-reference/pages/applications/[applicationId].tsx
  shared/ui-components/index.ts
  shared/ui-components/src/helpers/formatIncome.ts
  shared/ui-components/src/locales/general.json
Labels: Partners, ready for review

#864 Feature/persistent sort order
  apps/partners-reference/package.json
  apps/partners-reference/pages/applications.tsx
  yarn.lock
Labels: ready for review

#870 Status Messages component
  shared/ui-components/src/notifications/StatusMessage.tsx
  shared/ui-components/src/notifications/StatusMessages.scss
  shared/ui-components/src/notifications/StatusMessages.stories.tsx
  shared/ui-components/src/notifications/__snapshots__/StatusMessages.stories.storyshot
Labels: ready for review

#873 Enable cypress for circle ci
  .circleci/config.yml
  apps/partners-reference/next.config.js
  apps/partners-reference/package.json
  apps/public-reference/cypress/integration/navigation.ts
  apps/public-reference/cypress/integration/pages/application/financial/income.spec.ts
  apps/public-reference/cypress/support/helpers.ts
  apps/public-reference/package.json
  package.json
Labels: ready for review

#875 "required" prop in PhoneField and DOBField
  apps/public-reference/pages/applications/contact/address.tsx
  apps/public-reference/pages/applications/contact/alternate-contact-contact.tsx
  apps/public-reference/pages/applications/contact/name.tsx
  apps/public-reference/pages/applications/household/member.tsx
  shared/ui-components/src/forms/DOBField.stories.tsx
  shared/ui-components/src/forms/DOBField.tsx
  shared/ui-components/src/forms/PhoneField.tsx
  shared/ui-components/src/forms/__snapshots__/DOBField.stories.storyshot
Labels: ready for review
