Repository bloom-housing/bloom, pull requests merged in 2021-10, with the labels that each got.

#1895 docs: updating readmes
  README.md
  backend/core/README.md
  sites/partners/README.md
  sites/public/README.md
  ui-components/README.md
Labels: ready for review

#1810 Add AFS e2e tests to cover update scenario
  CHANGELOG.md
  backend/core/src/application-flagged-sets/application-flagged-sets.controller.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  backend/core/src/application-flagged-sets/dto/application-flagged-set-pagination-meta.ts
  backend/core/src/application-flagged-sets/dto/application-flagged-set-resolve.dto.ts
  backend/core/src/application-flagged-sets/dto/application-flagged-set.dto.ts
  backend/core/src/application-flagged-sets/dto/paginated-application-flagged-set.dto.ts
  backend/core/src/application-flagged-sets/entities/application-flagged-set.entity.ts
  backend/core/src/application-flagged-sets/paginated-application-flagged-set-query-params.ts
  backend/core/src/applications/applications.service.ts
  backend/core/test/afs/afs.e2e-spec.ts
Labels: ready for review

#1850 feat: listings management draft and publish validation backend & frontend
  CHANGELOG.md
  backend/core/package.json
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/dto/listings-retrieve-query-params.ts
  backend/core/src/listings/dto/paginated-listing.dto.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/validation-pipes/listing-create-validation-pipe.ts
  backend/core/src/listings/validation-pipes/listing-update-validation-pipe.ts
  backend/core/src/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeds/listings/listings.ts
  backend/core/src/seeds/listings/shared.ts
  backend/core/src/shared/entities/address.entity.ts
  backend/core/src/shared/filter/index.spec.ts
  backend/core/src/shared/url-helper.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/lib/helpers.ts
  sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailListingPhoto.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/ViewItem.tsx
  ui-components/src/forms/Form.tsx
  ui-components/src/locales/general.json
  yarn.lock
Labels: ready for review

#1889 feat(backend): add jurisidction relation to ReservedCommunittType Entity
  CHANGELOG.md
  backend/core/scripts/import-helpers.ts
  backend/core/src/migration/1632850106492-add-jurisdiction-relation-to-reserved-community-type.ts
  backend/core/src/reserved-community-type/dto/reserved-community-type-list-query-params.ts
  backend/core/src/reserved-community-type/dto/reserved-community-type.dto.ts
  backend/core/src/reserved-community-type/entities/reserved-community-type.entity.ts
  backend/core/src/reserved-community-type/reserved-community-types.controller.ts
  backend/core/src/reserved-community-type/reserved-community-types.service.ts
  backend/core/test/reserved-community-types/reserved-community-types.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: ready for review

#1885 refactor: re-write header menu bar, remove bulma
  CHANGELOG.md
  docs/Styling.md
  sites/partners/layouts/index.tsx
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/add.tsx
  sites/partners/src/ListingGuard.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPreferences.tsx
  sites/public/layouts/application.tsx
  ui-components/README.md
  ui-components/__tests__/headers/SiteHeader.test.tsx
  ui-components/__tests__/navigation/LanguageNav.test.tsx
  ui-components/__tests__/navigation/UserNav.test.tsx
  ui-components/index.ts
  ui-components/package.json
  ui-components/src/actions/Button.tsx
  ui-components/src/config/NavigationContext.tsx
  ui-components/src/global/app-css.scss
  ui-components/src/global/navbar.scss
  ui-components/src/global/print.scss
  ui-components/src/global/vendor/_setup_bulma.scss
  ui-components/src/headers/SiteHeader.scss
  ui-components/src/headers/SiteHeader.stories.tsx
  ui-components/src/headers/SiteHeader.tsx
  ui-components/src/icons/Icon.scss
  ui-components/src/icons/Icon.stories.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
  ui-components/src/navigation/LanguageNav.scss
  ui-components/src/navigation/LanguageNav.stories.tsx
  ui-components/src/navigation/LanguageNav.tsx
  ui-components/src/navigation/UserNav.tsx
  yarn.lock
Labels: ready for review, high priority, SF Request

#1924 feat: required labels on listings management fields
  CHANGELOG.md
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/PhoneField.tsx
  ui-components/src/forms/Select.tsx
  ui-components/src/global/forms.scss
  ui-components/src/locales/general.json
Labels: reviewed

#1925 fix: multiple ami charts should show a max not a range
  CHANGELOG.md
  backend/core/src/shared/units-transformations.ts
Labels: reviewed

#1911 chore: Add new `shared-helpers` package
  .circleci/config.yml
  CHANGELOG.md
  README.md
  lerna.json
  package.json
  shared-helpers/.jest/setup-tests.js
  shared-helpers/.npmignore
  shared-helpers/CHANGELOG.md
  shared-helpers/README.md
  shared-helpers/__tests__/formKeys.test.ts
  shared-helpers/index.ts
  shared-helpers/jest.config.js
  shared-helpers/package.json
  shared-helpers/src/formKeys.ts
  shared-helpers/tsconfig.json
  sites/partners/src/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormAlternateContact.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/public/pages/applications/contact/address.tsx
  sites/public/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/pages/applications/contact/alternate-contact-type.tsx
  sites/public/pages/applications/household/member.tsx
  sites/public/pages/applications/review/demographics.tsx
  ui-components/src/forms/Select.tsx
  ui-components/src/helpers/formOptions.tsx
  ui-components/src/helpers/preferences.tsx
Labels: reviewed

#1934 chore: Update text for preferred unit types and terms
  CHANGELOG.md
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: reviewed

#1955 1746/Update csv export
  CHANGELOG.md
  backend/core/archer.ts
  backend/core/package.json
  backend/core/scripts/minimal-listing.json
  backend/core/src/applications/applications.controller.ts
  backend/core/src/applications/applications.module.ts
  backend/core/src/csv/application-csv-exporter.ts
  backend/core/src/csv/csv-builder.service.ts
  backend/core/src/csv/csv-builder.spec.ts
  backend/core/src/csv/csv-encoder.service.ts
  backend/core/src/csv/formatting/application-formatting-metadata-factory.ts
  backend/core/src/csv/formatting/formatters.ts
  backend/core/src/csv/formatting/metadata/basic-formatting-metadata.ts
  backend/core/src/csv/formatting/metadata/bha-formatting-metadata.ts
  backend/core/src/csv/formatting/metadata/hayward-formatting-metadata.ts
  backend/core/src/csv/formatting/metadata/oha-formatting-metadata.ts
  backend/core/src/csv/types/csv-formatting-type-enum.ts
  backend/core/src/csv/types/formatting-metadata-aggregate-factory.ts
  backend/core/src/csv/types/formatting-metadata-aggregate.ts
  backend/core/src/csv/types/formatting-metadata-array.ts
  backend/core/src/csv/types/formatting-metadata.ts
  backend/core/src/libs/stringLib/index.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/main.ts
  backend/core/src/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeds/listings/shared.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  yarn.lock
Labels: ready for review

#1962 fix: modals no longer prevent scroll after being closed
  CHANGELOG.md
  sites/partners/src/listings/PaperListingForm/index.tsx
  ui-components/src/overlays/Overlay.tsx
Labels: Listings Mgmt, reviewed

#1996 feat(backend): Add user delete endpoint and expose leasingAgentInList…
  CHANGELOG.md
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/entities/user-roles.entity.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/migration/1634210584036-add-cascade-to-user-roles-user-relation.ts
  backend/core/src/shared/email/email.service.spec.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: ready for review

#1972 fix(backend): enforces lower casing of emails
  CHANGELOG.md
  backend/core/src/applications/entities/alternate-contact.entity.ts
  backend/core/src/applications/entities/applicant.entity.ts
  backend/core/src/applications/entities/household-member.entity.ts
  backend/core/src/auth/dto/email.dto.ts
  backend/core/src/auth/dto/forgot-password.dto.ts
  backend/core/src/auth/dto/login.dto.ts
  backend/core/src/auth/dto/user-create.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/passport-strategies/local.strategy.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1633557587028-user-email-lower-case.ts
  backend/core/src/shared/decorators/enforceLowerCase.decorator.ts
  backend/core/test/user/user.e2e-spec.ts
Labels: needs review(s)

#2042 chore: Pre-release GitHub Action
  .github/workflows/pre-release_components.yml
Labels: needs review(s)

#2091 fix: adds tests around the unit type work
  ui-components/__tests__/helpers/unitTypes.test.ts
  ui-components/src/helpers/unitTypes.ts
Labels: reviewed
