Repository bloom-housing/bloom, pull requests merged in 2021-12, with the labels that each got.

#2195 2140/fix paper application submission
  sites/partners/lib/formatApplicationData.ts
Labels: needs review(s), reviewed

#2215 feat(backend): add storing listing translations
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/migration/1637680690577-add-generated-listing-translation.ts
  backend/core/src/translations/entities/generated-listing-translation.entity.ts
  backend/core/src/translations/services/google-translate.service.ts
  backend/core/src/translations/services/translations.service.spec.ts
  backend/core/src/translations/services/translations.service.ts
  backend/core/src/translations/translations.controller.ts
  backend/core/src/translations/translations.module.ts
  backend/core/src/translations/translations.service.spec.ts
  backend/core/src/translations/translations.service.ts
Labels: reviewed

#2213 feat(backend): add listings closing routine
  backend/core/package.json
  backend/core/src/applications/applications.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  yarn.lock
Labels: needs review(s)

#2234 fix: Remove description for the partners programs
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrograms.tsx
Labels: ready to merge

#2260 2227/lock login attempts frontend
  shared-helpers/index.ts
  shared-helpers/src/catchNetworkError.ts
  sites/partners/pages/sign-in.tsx
  sites/public/pages/sign-in.tsx
  ui-components/index.ts
  ui-components/src/locales/general.json
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.tsx
  ui-components/src/notifications/AlertNotice.tsx
  ui-components/src/page_components/sign-in/FormSignIn.tsx
Labels: reviewed

#2280 fix: Fix modal styles on mobile
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.tsx
Labels: ready to merge

#2276 fix: visual improvement to programs form display
  sites/public/pages/applications/household/programs.tsx
Labels: ready to merge

#2262 feat: overrides fallback to english, tagalog support
  backend/core/src/migration/1630388600246-convert-preferred-unit-to-unit-types.ts
  backend/core/src/migration/1638478574456-add-tagalog.ts
  backend/core/src/shared/types/language-enum.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/translations.ts
  sites/public/pages/_app.tsx
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/src/translations.ts
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/missing-translations.ts
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2278 fix: account translations
  ui-components/src/locales/es.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2294 fix: prefUnits on autofill summary
  sites/public/src/forms/applications/FormSummaryDetails.tsx
Labels: ready to merge

#2277 chore: move Programs step to come after Students
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/lib/AppSubmissionContext.ts
  sites/public/lib/ApplicationConductor.ts
  sites/public/pages/applications/household/programs.tsx
  sites/public/pages/applications/household/student.tsx
  sites/public/pages/applications/preferences/all.tsx
Labels: reviewed, ready to merge

#2290 fix: units with invalid ami chart
  backend/core/src/shared/units-transformations.ts
Labels: needs review(s), reviewed

#2299 chore: missing translations
  sites/public/pages/account/dashboard.tsx
  sites/public/pages/create-account.tsx
  sites/public/src/ConfirmationModal.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2305 fix: demographics howDidYouHear options were not changing on language
  sites/public/pages/applications/review/demographics.tsx
Labels: needs review(s)

#2308 fix: mobile notice text wrap issue
  ui-components/src/headers/SiteHeader.scss
Labels: reviewed

#2190 feat(backend): add activity logging to listings module
  backend/core/package.json
  backend/core/src/activity-log/activity-log.module.ts
  backend/core/src/activity-log/decorators/activity-log-metadata.decorator.ts
  backend/core/src/activity-log/entities/activity-log.entity.ts
  backend/core/src/activity-log/interceptors/activity-log.interceptor.ts
  backend/core/src/activity-log/services/activity-log.service.ts
  backend/core/src/activity-log/types/activity-log-metadata-type.ts
  backend/core/src/app.module.ts
  backend/core/src/applications/applications.controller.ts
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/services/applications.service.ts
  backend/core/src/auth/auth.module.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/controllers/user.controller.spec.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/guards/authz.guard.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/migration/1638439254453-add-activity-log-metadata.ts
  backend/core/src/seeder/seeds/applications.ts
  backend/core/src/shared/http-methods-to-actions.ts
  backend/core/src/shared/utils/deep-find.ts
  backend/core/test/activity-logs/activity-log.e2e-spec.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
  yarn.lock
Labels: reviewed

#2239 2040/postmark date time fields partners
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  ui-components/src/blocks/ViewItem.tsx
  ui-components/src/forms/DateField.tsx
  ui-components/src/forms/TimeField.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.tsx
Labels: needs review(s), reviewed

#2302 feat(backend): all programs to csv export
  backend/core/src/applications/services/application-csv-exporter.service.ts
  backend/core/src/shared/units-transformations.ts
Labels: needs review(s)

#2301 feat(backend): add partnerTerms to jurisdiction entity
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/migration/1639135587230-add-partner-terms-to-jurisdiction.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s)

#2288 feat: adds updating open listing modal
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingIntro.tsx
  ui-components/src/actions/Button.tsx
  ui-components/src/locales/general.json
Labels: needs review(s), reviewed

#2317 2228/closed listings allowed applications
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#2319 2228/removes more closed listing application paths
  sites/public/lib/hooks.ts
  sites/public/src/ListingView.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.tsx
Labels: needs review(s)

#2227 feat(backend): lock failed login attempts
  backend/core/src/auth/dto/user-create.dto.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/passport-strategies/local.strategy.spec.ts
  backend/core/src/auth/passport-strategies/local.strategy.ts
  backend/core/src/auth/services/password.service.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/migration/1637924287461-add-user-login-metadata-to-user-entity.ts
  backend/core/src/shared/shared.module.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/index.ts
  shared-helpers/src/catchNetworkError.ts
  sites/partners/pages/sign-in.tsx
  sites/public/pages/sign-in.tsx
  sites/public/src/forms/applications/FormBackLink.tsx
  sites/public/src/forms/applications/FormSummaryDetails.tsx
  ui-components/index.ts
  ui-components/src/locales/general.json
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.tsx
  ui-components/src/notifications/AlertNotice.tsx
  ui-components/src/page_components/sign-in/FormSignIn.tsx
Labels: reviewed
