Repository bloom-housing/bloom, pull requests merged in 2021-09, with the labels that each got.

#1773 1574/remove business logic from from ListingsList component
  CHANGELOG.md
  sites/public/pages/listings.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/__tests__/page_components/ListingsList.test.tsx
  ui-components/index.ts
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.tsx
  ui-components/src/page_components/listing/ListingsList.tsx
Labels: ready for review, UI Components - Strip Dependencies

#1744 1742/relocate formatIncome
  CHANGELOG.md
  sites/partners/lib/helpers.ts
  sites/partners/src/applications/ApplicationsColDefs.ts
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdIncome.tsx
  ui-components/__tests__/helpers/formatIncome.test.ts
  ui-components/index.ts
  ui-components/src/helpers/formatIncome.ts
Labels: ready for review, UI Components - Strip Dependencies

#1809 Reset page to 1 on limit change
  CHANGELOG.md
  sites/partners/pages/index.tsx
Labels: ready for review

#1722 1721/remove business logic from HouseholdMemberForm component
  CHANGELOG.md
  sites/public/pages/applications/household/add-members.tsx
  ui-components/__tests__/forms/HouseholdMemberForm.test.tsx
  ui-components/src/forms/HouseholdMemberForm.stories.tsx
  ui-components/src/forms/HouseholdMemberForm.tsx
  ui-components/src/global/text.scss
Labels: ready for review, UI Components - Strip Dependencies

#1816 1725/remove dependencies from hero component
  CHANGELOG.md
  sites/public/pages/index.tsx
  ui-components/__tests__/headers/Hero.test.tsx
  ui-components/src/headers/Hero.stories.tsx
  ui-components/src/headers/Hero.tsx
Labels: ready for review, UI Components - Strip Dependencies

#1714 1713/remove business logic from AppStatusItem component
  CHANGELOG.md
  sites/public/pages/account/AppStatusItemWrapper.tsx
  sites/public/pages/account/StatusItemWrapper.tsx
  sites/public/pages/account/applications.tsx
  ui-components/__tests__/blocks/AppStatusItem.test.tsx
  ui-components/__tests__/blocks/StatusItem.test.tsx
  ui-components/index.ts
  ui-components/src/blocks/AppStatusItem.stories.tsx
  ui-components/src/blocks/StatusItem.scss
  ui-components/src/blocks/StatusItem.stories.tsx
  ui-components/src/blocks/StatusItem.tsx
Labels: ready for review, UI Components - Strip Dependencies

#1706 1544/ami overrides + unit form refactor
  CHANGELOG.md
  sites/partners/lib/hooks.ts
  sites/partners/src/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/locales/general.json
  ui-components/src/tables/StandardTable.tsx
Labels: ready for review

#1802 1728/notifications
  CHANGELOG.md
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/jurisdictions/jurisdictions.controller.ts
  backend/core/src/migration/1630105131436-add-jurisdiction-notification-setting.ts
  backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/pages/index.tsx
  ui-components/src/global/homepage.scss
  ui-components/src/locales/general.json
Labels: ready for review

#1768 Update select labels
  CHANGELOG.md
  sites/partners/lib/helpers.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  ui-components/src/locales/general.json
Labels: ready for review

#1848 dependency issues
  sites/partners/layouts/forms.tsx
  sites/partners/package.json
  sites/partners/pages/sign-in.tsx
  sites/partners/src/applications/ApplicationsColDefs.ts
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/public/package.json
  ui-components/.jest/setup-tests.js
  ui-components/README.md
  ui-components/package.json
  ui-components/src/global/mixins.scss
  ui-components/src/global/vendor/ag_grid.scss
  yarn.lock
Labels: ready for review

#1844 1842/additional fees
  CHANGELOG.md
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/AdditionalFees.test.tsx
  ui-components/src/page_components/listing/AdditionalFees.stories.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: ready for review, UI Components - Strip Dependencies

#1830 Add isPartner filter to GET /user/list endpoint
  CHANGELOG.md
  backend/core/src/applications/applications-submission.controller.ts
  backend/core/src/applications/applications.service.ts
  backend/core/src/auth/controllers/auth.controller.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/dto/forgot-password-response.dto.ts
  backend/core/src/auth/dto/forgot-password.dto.ts
  backend/core/src/auth/dto/login-response.dto.ts
  backend/core/src/auth/dto/login.dto.ts
  backend/core/src/auth/dto/user-create-query-params.ts
  backend/core/src/auth/dto/user-filter-params.ts
  backend/core/src/auth/dto/user-filter-type-to-field-map.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-list-query-params.ts
  backend/core/src/auth/dto/user-roles-create.dto.ts
  backend/core/src/auth/dto/user-roles-update.dto.ts
  backend/core/src/auth/dto/user-roles.dto.ts
  backend/core/src/auth/enum/authz-actions.enum.ts
  backend/core/src/auth/services/authz.service.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/auth/types/user-filter-keys.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/users/index.tsx
Labels: ready for review

#1819 1818/remove dependencies from apply
  CHANGELOG.md
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/ApplicationSection.test.tsx
  ui-components/__tests__/page_components/Apply.test.tsx
  ui-components/__tests__/page_components/GetApplication.test.tsx
  ui-components/__tests__/page_components/SubmitApplication.test.tsx
  ui-components/__tests__/page_components/Waitlist.test.tsx
  ui-components/index.ts
  ui-components/src/page_components/listing/listing_sidebar/ApplicationSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/ApplicationSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/Apply.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Apply.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/NumberedHeader.tsx
  ui-components/src/page_components/listing/listing_sidebar/OrDivider.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx
Labels: ready for review, UI Components - Strip Dependencies

#1846 chore: add conventional commit linting
  commitlint.config.js
  package.json
  yarn.lock
Labels: ready for review

#1823 Purge the CSS output from Tailwind, etc. so only used styles are published
  sites/partners/tailwind.config.js
  sites/public/tailwind.config.js
Labels: ready for review

#1849 fix unit form issues
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Labels: ready for review

#1860 1728/notifications qa
  sites/public/pages/index.tsx
  ui-components/src/blocks/ActionBlock.tsx
  ui-components/src/global/homepage.scss
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/general.json
Labels: ready for review

#1853 Bug/1843/application types
  CHANGELOG.md
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1632431578257-set-application-method-booleans.ts
  backend/core/src/seeds/listings/listing-coliseum-seed.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/public/lib/helpers.ts
  sites/public/lib/hooks.ts
  sites/public/pages/index.tsx
  sites/public/pages/listings.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/LeasingAgent.test.tsx
  ui-components/index.ts
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/PhoneMask.tsx
  ui-components/src/forms/Select.tsx
  ui-components/src/helpers/state.tsx
  ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
Labels: ready for review

#1874 fix: update alameda's notification sign up URL
  backend/core/src/migration/1632428425207-update-ala-signup.ts
Labels: ready for review

#1880 feat: new subheader prop and custom class names on ListingCard
  CHANGELOG.md
  sites/public/pages/listings.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: ready for review, SF Request

#1861 1780/Cleanup getStaticProps and getStaticPaths
  .gitignore
  CHANGELOG.md
  sites/public/package.json
  sites/public/pages/index.tsx
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/pages/listings.tsx
Labels: ready for review

#1887 chore: bump tmpl package
  yarn.lock
Labels: ready for review

#1828 1829/script to find missing translations
  ui-components/src/locales/general.json
  ui-components/src/locales/missing-translations.ts
Labels: ready for review

#1888 test: fix broken a11y test, stories
  ui-components/src/overlays/Drawer.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
  ui-components/src/prototypes/FieldSection.stories.tsx
  ui-components/src/prototypes/GridItem.stories.tsx
  ui-components/src/sections/GridSection.stories.tsx
Labels: ready for review
