Repository bloom-housing/bloom, pull requests merged in 2021-11, with the labels that each got.

#2074 fix: a11y color contrast issues with tint on ImageCard component
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/blocks/ImageCard.stories.tsx
Labels: SF Request, needs design review

#2070 feat: two new common app questions - Household Changes and Household Student
  backend/core/src/applications/entities/application.entity.ts
  backend/core/src/csv/application-csv-exporter.ts
  backend/core/src/migration/1635216780193-new-household-common-app-questions.ts
  backend/core/src/seeds/applications.ts
  backend/core/test/lib/get-test-app-body.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/public/cypress/fixtures/applicationConfigBlank.json
  sites/public/cypress/fixtures/applicationConfigFilled.json
  sites/public/cypress/fixtures/listing.json
  sites/public/cypress/fixtures/listingConfig.json
  sites/public/cypress/fixtures/routes.json
  sites/public/cypress/integration/pages/application/household/expecting-changes.ts
  sites/public/cypress/integration/pages/application/household/student.ts
  sites/public/lib/AppSubmissionContext.ts
  sites/public/lib/ApplicationConductor.ts
  sites/public/pages/applications/household/ada.tsx
  sites/public/pages/applications/household/changes.tsx
  sites/public/pages/applications/household/student.tsx
  sites/public/src/forms/applications/FormSummaryDetails.tsx
  ui-components/src/helpers/blankApplication.ts
  ui-components/src/locales/general.json
Labels: reviewed

#2113 fix: household member cypress test
  sites/public/cypress/integration/pages/application/household/member.spec.ts
Labels: reviewed

#2068 fix: SiteHeader visual issues with long menu bars
  sites/public/layouts/application.tsx
  sites/public/layouts/forms.tsx
  sites/public/pages/account/applications.tsx
  sites/public/pages/account/dashboard.tsx
  sites/public/pages/index.tsx
  ui-components/src/headers/PageHeader.scss
  ui-components/src/headers/SiteHeader.scss
  ui-components/src/headers/SiteHeader.stories.tsx
  ui-components/src/headers/SiteHeader.tsx
  ui-components/src/navigation/LanguageNav.scss
Labels: SF Request, needs design review

#2111 feat: jurisdictional email signatures
  backend/core/src/migration/1635546032998-add-jurisdictional-email-signatures.ts
  backend/core/src/seed.ts
  backend/core/src/seeds/listings/listing-default-sanjose-seed.ts
  backend/core/src/shared/email/email.service.spec.ts
  backend/core/src/shared/email/email.service.ts
  backend/core/src/views/partials/footer.hbs
Labels: ready to merge

#2110 fix: error on creating paper applications
  backend/core/src/applications/applications.service.ts
  sites/partners/pages/_app.tsx
Labels: reviewed, ready to merge

#2102 1838/ami chart jurisdictionalized
  backend/core/src/ami-charts/ami-charts.service.ts
  backend/core/src/ami-charts/dto/ami-chart-list-query-params.ts
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/seed.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeds/listings/listing-triton-seed.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Labels: reviewed

#2072 feat: Updates application confirmation numbers
  backend/core/src/csv/application-csv-exporter.ts
  sites/partners/pages/application/[id]/edit.tsx
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/src/applications/ApplicationsColDefs.ts
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/flags/applicationsCols.tsx
  sites/public/cypress/fixtures/applicationConfigBlank.json
  sites/public/cypress/fixtures/applicationConfigFilled.json
  sites/public/cypress/integration/pages/application/review/confirmation.spec.ts
  sites/public/cypress/integration/pages/application/review/terms.spec.ts
  sites/public/lib/appAutofill.ts
  sites/public/pages/account/StatusItemWrapper.tsx
  sites/public/pages/account/application/[id].tsx
  sites/public/pages/applications/review/confirmation.tsx
  sites/public/pages/applications/review/terms.tsx
  sites/public/pages/applications/view.tsx
  ui-components/src/helpers/blankApplication.ts
Labels: ready to merge

#2078 fix(backend): make it possible to filter portal users in /users endpoint
  backend/core/src/auth/dto/user-filter-params.ts
  backend/core/src/auth/dto/user-filter-type-to-field-map.ts
  backend/core/src/auth/filters/user-query-filter.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/auth/types/user-filter-keys.ts
  backend/core/src/shared/filter/base-query-filter.ts
  backend/core/src/shared/filter/index.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: reviewed

#2120 feat(backend): extend UserUpdateDto to support email change with conf…
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/dto/user-profile.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/migration/1635946663862-add-change-email-translations.ts
  backend/core/src/seed.ts
  backend/core/src/shared/email/email.service.ts
  backend/core/src/views/change-email.hbs
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s), reviewed

#2073 2056/user account edit fix
  backend/core/src/migration/1635946663862-add-change-email-translations.ts
  backend/core/src/views/change-email.hbs
  sites/public/pages/account/edit.tsx
  ui-components/src/authentication/AuthContext.ts
  ui-components/src/forms/DOBField.tsx
Labels: needs review(s)

#2132 2085/adds top level catchAll exception filter
  backend/core/src/app.module.ts
  backend/core/src/filters/catch-all.filter.ts
  backend/core/src/filters/entity-not-found-exception.filter.ts
Labels: needs review(s), reviewed

#2136 feat: Change unit number field type to text
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Labels: needs review(s)

#1982 1655/invite user edit
  backend/core/src/applications/entities/application.entity.ts
  backend/core/src/jurisdictions/services/jurisdiction-resolver.service.ts
  backend/core/src/migration/1634814157491-add-on-delete-action-to-application-user-relation.ts
  backend/core/test/user/user.e2e-spec.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/users/index.tsx
  sites/partners/src/users/FormUserAdd.tsx
  sites/partners/src/users/FormUserManage.tsx
  ui-components/src/locales/general.json
  ui-components/src/sections/GridSection.tsx
Labels: needs review(s), reviewed

#2151 fix: updates address order
  backend/core/src/csv/application-csv-exporter.ts
Labels: needs review(s), reviewed

#2119 feat(backend): add nginx proxy-cache configuration
  backend/core/src/listings/listings.controller.ts
  backend/proxy/default.conf
Labels: reviewed

#2169 1868/fixes program, preference, ami-chart de-dupe
  sites/partners/lib/hooks.ts
Labels: needs review(s)

#2150 2081/recalculate units available on listing update
  backend/core/src/listings/listings.service.ts
Labels: reviewed

#2009 refactor: remove applicationAddress
  CHANGELOG.md
  backend/core/archer.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1634316081536-remove-app-address.ts
  backend/core/src/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeds/listings/shared.ts
  backend/core/test/factories/listing.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/archer-listing.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/public/cypress/fixtures/listing.json
  ui-components/__tests__/fixtures/archer.json
  ui-components/__tests__/fixtures/gish.json
  ui-components/__tests__/fixtures/triton-test.json
  ui-components/__tests__/page_components/SidebarAddress.test.tsx
Labels: ready to merge

#2156 1975/better seed data for ami-charts
  backend/core/src/seed.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyLIHTC2020.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyTCAC2019.ts
  backend/core/src/seeds/ami-charts/AlamedaCountyTCAC2020.ts
  backend/core/src/seeds/ami-charts/OaklandFremontHUD2020.ts
  backend/core/src/seeds/ami-charts/SanJoseTCAC2019.ts
  backend/core/src/seeds/ami-charts/SanMateoCountyTCAC2019.ts
  backend/core/src/seeds/ami-charts/SanMateoCountyTCAC2020.ts
  backend/core/src/seeds/ami-charts/SanMateoHERASpecial2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHOME2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHUD2019.ts
  backend/core/src/seeds/ami-charts/SanMateoHUD2020.ts
  backend/core/src/seeds/ami-charts/default-ami-chart-san-jose.ts
  backend/core/src/seeds/ami-charts/default-ami-chart-san-mateo.ts
  backend/core/src/seeds/ami-charts/default-ami-chart.ts
  backend/core/src/seeds/ami-charts/index.ts
  backend/core/src/seeds/ami-charts/missing-household-ami-levels.ts
  backend/core/src/seeds/ami-charts/triton-ami-chart-detroit.ts
  backend/core/src/seeds/ami-charts/triton-ami-chart.ts
  backend/core/src/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeds/listings/listing-default-bmr-chart-seed.ts
  backend/core/src/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeds/listings/listing-default-multiple-ami-and-percentages.ts
  backend/core/src/seeds/listings/listing-default-multiple-ami.ts
  backend/core/src/seeds/listings/listing-default-sanjose-seed.ts
  backend/core/src/seeds/listings/listing-default-seed.ts
  backend/core/src/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeds/listings/shared.ts
Labels: ready to merge

#2103 1988/adds listing management cypress tests to partner portal
  sites/partners/cypress.json
  sites/partners/cypress/fixtures/exygy.jpeg
  sites/partners/cypress/fixtures/listing.json
  sites/partners/cypress/fixtures/listingImage.json
  sites/partners/cypress/fixtures/user.json
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/cypress/integration/navigation.ts
  sites/partners/cypress/plugins/index.js
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/helpers.ts
  sites/partners/cypress/support/index.d.ts
  sites/partners/cypress/support/index.js
  sites/partners/cypress/support/index.ts
  sites/partners/cypress/tsconfig.json
  sites/partners/package.json
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalDetails.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingDetails.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailCommunityType.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailListingIntro.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailListingPhoto.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPreferences.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/tables/MinimalTable.tsx
  ui-components/src/tables/StandardTable.tsx
  yarn.lock
Labels: ready to merge

#2158 1975/one month rent
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1636499724052-deposit-helper-text-creation.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: reviewed

#2206 refactor: removes jsonpath
  backend/core/package.json
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/listings.service.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/cypress/fixtures/listingImage.json
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  yarn.lock
Labels: ready to merge

#2114 1869/application program display
  backend/core/src/seed.ts
  backend/core/src/seeds/listings/listing-default-seed.ts
  backend/core/src/seeds/listings/shared.ts
  shared-helpers/index.ts
  shared-helpers/src/programHelpers.ts
  sites/partners/next.config.js
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/cypress/support/index.d.ts
  sites/public/lib/AppSubmissionContext.ts
  sites/public/lib/ApplicationConductor.ts
  sites/public/lib/ProgramsStep.ts
  sites/public/next.config.js
  sites/public/pages/applications/household/programs.tsx
  sites/public/src/forms/applications/FormBackLink.tsx
  sites/public/src/forms/applications/FormSummaryDetails.tsx
  ui-components/__tests__/fixtures/archer.json
  ui-components/__tests__/forms/FieldGroup.test.tsx
  ui-components/src/forms/FieldGroup.stories.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/Select.tsx
  ui-components/src/helpers/blankApplication.ts
  ui-components/src/locales/general.json
Labels: reviewed, ready to merge

#2182 1901/application program partners
  backend/core/src/seeds/listings/shared.ts
  shared-helpers/src/programHelpers.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsPrograms.tsx
  sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrograms.tsx
  sites/public/cypress/integration/pages/application/household/programs.spec.ts
  sites/public/pages/applications/household/programs.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#2109 feat: new demographics sub-race questions
  backend/core/src/applications/entities/demographics.entity.ts
  backend/core/src/csv/application-csv-exporter.ts
  backend/core/src/migration/1635535204972-allow-multiple-race-checkboxes.ts
  backend/core/src/seeds/applications.ts
  backend/core/test/lib/get-test-app-body.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/.jest/setup-tests.js
  shared-helpers/__tests__/formKeys.test.ts
  shared-helpers/jest.config.js
  shared-helpers/package.json
  shared-helpers/src/formKeys.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/next.config.js
  sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/next.config.js
  sites/public/pages/applications/review/demographics.tsx
  ui-components/.jest/setup-tests.js
  ui-components/__tests__/actions/ExpandableContent.test.tsx
  ui-components/__tests__/forms/FieldGroup.test.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/helpers/blankApplication.ts
  ui-components/src/locales/general.json
  yarn.lock
Labels: reviewed, ready to merge

#2208 fix: change the yes/no radio text to be more descriptive
  sites/public/pages/applications/financial/vouchers.tsx
  sites/public/pages/applications/household/changes.tsx
  sites/public/pages/applications/household/student.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#2209 fix: remove alameda reference in demographics
  shared-helpers/src/formKeys.ts
  sites/public/cypress/mockData/applicationData.ts
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/general_OLD.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: ready to merge

#2205 feat: skip preferences if not on listing
  sites/public/cypress/fixtures/example.json
  sites/public/cypress/integration/pages/submit-application.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/cypress/support/index.d.ts
  sites/public/lib/AppSubmissionContext.ts
  sites/public/pages/applications/review/summary.tsx
  sites/public/pages/applications/start/choose-language.tsx
Labels: reviewed

#2168 feat: simplify Waitlist component and use more flexible schema
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/Waitlist.test.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx
Labels: needs review(s), reviewed

#2226 fix: lottery results uploads now save
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s), reviewed
