Repository bloom-housing/bloom, pull requests merged in 2022-09, with the labels that each got.

#3036 fix: migration for application export clean up
  backend/core/src/migration/1661805250707-programAndPreferenceUpdates.ts
Labels: ready to merge

#3040 fix: return N/A if rent and income is NaN
  backend/core/src/shared/units-transformations.ts
  shared-helpers/src/summaryTables.tsx
Labels: ready to merge

#3054 2920/bordered field option
  ui-components/src/forms/Field.stories.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/global/forms.scss
Labels: ready to merge

#3050 feat: allow alerts to be sticky under page header
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/pages/listings/[id]/applications/add.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/pages/listings/add.tsx
  sites/partners/pages/settings/index.tsx
  sites/partners/pages/users/index.tsx
  ui-components/src/headers/PageHeader.scss
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.stories.tsx
  ui-components/src/notifications/AlertBox.tsx
  ui-components/src/notifications/SiteAlert.tsx
  ui-components/src/tables/StandardTable.tsx
Labels: ready to merge

#3058 Visuals for modal follup
  backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  backend/core/src/application-flagged-sets/dto/application-flagged-set-resolve.dto.ts
  backend/core/src/application-flagged-sets/entities/application-flagged-set.entity.ts
  backend/core/src/application-flagged-sets/types/flagged-set-status-enum.ts
  backend/core/src/applications/entities/application.entity.ts
  backend/core/src/applications/types/application-review-status-enum.ts
  backend/core/src/migration/1661788864862-adding-review-status.ts
  backend/core/src/migration/1661789324467-removing-flagged-status.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/applications.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/pages/application/[id]/review.tsx
  sites/partners/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/flags/flagSetCols.tsx
  ui-components/src/tables/AgTable.tsx
Labels: 2 reviews needed

#3073 fix: updated css class naming
  ui-components/src/page_components/ApplicationTimeline.scss
  ui-components/src/page_components/ApplicationTimeline.tsx
Labels: ready to merge

#3070 Update dropzone for single upload
  ui-components/src/forms/Dropzone.scss
  ui-components/src/forms/Dropzone.tsx
Labels: ready to merge

#3041 feat: add confirm modal when copying a preference
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/settings/index.tsx
  ui-components/src/tables/StandardTable.tsx
Labels: ready to merge

#3076 3071/Core - Fix Progress Bar
  sites/public/pages/applications/financial/income.tsx
  sites/public/pages/applications/household/student.tsx
Labels: 1 review needed

#3077 chore: add tests back to eslint
  .eslintrc.js
  shared-helpers/__tests__/RequireLogin.test.tsx
  shared-helpers/__tests__/Timeout.test.tsx
  sites/partners/__tests__/DatesFormatter.test.ts
  ui-components/__tests__/blocks/ImageCard.test.tsx
  ui-components/__tests__/blocks/InfoCard.test.tsx
  ui-components/__tests__/blocks/StandardCard.test.tsx
  ui-components/__tests__/blocks/StatusItem.test.tsx
  ui-components/__tests__/forms/DOBField.test.tsx
  ui-components/__tests__/forms/DateField.test.tsx
  ui-components/__tests__/forms/Field.test.tsx
  ui-components/__tests__/forms/FieldGroup.test.tsx
  ui-components/__tests__/forms/Form.test.tsx
  ui-components/__tests__/forms/HouseholdMemberForm.test.tsx
  ui-components/__tests__/forms/HouseholdSizeField.test.tsx
  ui-components/__tests__/forms/MultiSelectField.test.tsx
  ui-components/__tests__/forms/Select.test.tsx
  ui-components/__tests__/forms/Textarea.test.tsx
  ui-components/__tests__/forms/TimeField.test.tsx
  ui-components/__tests__/headers/SiteHeader.test.tsx
  ui-components/__tests__/navigation/LanguageNav.test.tsx
  ui-components/__tests__/navigation/SideNav.test.tsx
  ui-components/__tests__/navigation/Tabs.test.tsx
  ui-components/__tests__/notifications/SiteAlert.test.tsx
  ui-components/__tests__/overlays/Drawer.test.tsx
  ui-components/__tests__/overlays/Modal.test.tsx
  ui-components/__tests__/page_components/ContentAccordion.test.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/__tests__/page_components/ReferralApplication.test.tsx
  ui-components/__tests__/tables/AgTable.test.tsx
  ui-components/__tests__/tables/StandardTable.test.tsx
Labels: ready to merge

#3063 3030/what to expect visual updates
  shared-helpers/src/summaryTables.tsx
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.tsx
  ui-components/src/text/Tag.scss
  ui-components/src/text/Tag.tsx
Labels: ready to merge

#3084 fix: append copy text to copied preferences
  sites/partners/pages/settings/index.tsx
Labels: ready to merge

#3082 feat: show dismissable alert when updating afs
  backend/core/src/application-flagged-sets/application-flagged-sets.controller.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/pages/application/[id]/review.tsx
Labels: ready to merge

#3088 fix: make pill style on listing card optional
  sites/public/lib/helpers.tsx
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: sf request, 2 reviews needed

#3086 chore: standardize the typescript version
  backend/core/package.json
  backend/core/src/email/email.service.spec.ts
  package.json
  sites/partners/package.json
  sites/public/package.json
  ui-components/package.json
  yarn.lock
Labels: wip

#3056 refactor: cleanup application error state styles
  shared-helpers/src/multiselectQuestions.tsx
  sites/partners/src/applications/Aside.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/public/pages/applications/contact/address.tsx
  sites/public/pages/applications/contact/alternate-contact-type.tsx
  sites/public/pages/applications/contact/name.tsx
  sites/public/pages/applications/financial/income.tsx
  sites/public/pages/applications/financial/vouchers.tsx
  sites/public/pages/applications/household/changes.tsx
  sites/public/pages/applications/household/member.tsx
  sites/public/pages/applications/household/preferred-units.tsx
  sites/public/pages/applications/household/student.tsx
  ui-components/src/forms/DOBField.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/HouseholdSizeField.tsx
  ui-components/src/global/forms.scss
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
  ui-components/src/tables/StandardTable.stories.tsx
Labels: sf request, ready to merge

#3101 fix: duplicates ux issues
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/application/[id]/applicationsCols.tsx
  sites/partners/pages/listings/[id]/applications/pending/index.tsx
  ui-components/src/global/vendor/ag_grid.scss
Labels: 1 review needed

#3104 3096/csv-export-updates
  backend/core/src/applications/services/application-csv-exporter.service.ts
Labels: ready to merge

#3105 3099/AFS Pagination
  sites/partners/lib/hooks.ts
  sites/partners/pages/listings/[id]/applications/resolved/index.tsx
Labels: ready to merge

#3095 fix: email tests
  backend/core/src/email/email.service.spec.ts
  backend/core/src/migration/1664235051977-email-typo.ts
  ui-components/src/locales/general.json
Labels: ready to merge

#3090 fix: heading size issues on resources page
  ui-components/src/sections/InfoCardGrid.scss
  ui-components/src/sections/InfoCardGrid.tsx
Labels: ready to merge
