Repository bloom-housing/bloom, pull requests merged in 2022-04, with the labels that each got.

#2582 refactor: flatten translations strings, separate partners strings
  .prettierignore
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/reset-password.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsPreferences.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/public/layouts/application.tsx
  sites/public/pages/account/applications.tsx
  sites/public/pages/applications/financial/income.tsx
  sites/public/pages/reset-password.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/forms/HouseholdSizeField.test.tsx
  ui-components/scripts/duplicate-translations.ts
  ui-components/scripts/missing-translations.ts
  ui-components/scripts/reformat-strings.ts
  ui-components/scripts/unused-foreign-keys.ts
  ui-components/src/forms/DOBField.tsx
  ui-components/src/forms/DateField.tsx
  ui-components/src/forms/HouseholdSizeField.tsx
  ui-components/src/forms/TimeField.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/general_OLD.json
  ui-components/src/locales/missing-translations.ts
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2531 feat: listing card title redesign, multiple tags possible
  sites/public/cypress/support/commands.js
  sites/public/lib/helpers.tsx
  sites/public/pages/applications/start/choose-language.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/blocks/ImageCard.test.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/blocks/ImageCard.stories.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/global/text.scss
  ui-components/src/headers/Heading.stories.tsx
  ui-components/src/headers/Heading.tsx
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: needs design review

#2606 chore: update pr template to include qa note reminders
  docs/pull_request_template.md
Labels: needs review(s), ready to merge

#2563 Add terms content
  backend/core/src/auth/dto/user-create.dto.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-profile.dto.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/migration/1647858061141-add-jurisdiction-partner-terms.ts
  backend/core/src/migration/1648043352040-add-user-agreed-to-terms-of-service-column.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/cypress/integration/01-sign-in-terms.spec.ts
  sites/partners/cypress/integration/02-mfa.spec.ts
  sites/partners/cypress/integration/03-listing.spec.ts
  sites/partners/cypress/integration/04-application.spec.ts
  sites/partners/cypress/integration/05-paperApplication.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/layouts/forms.tsx
  sites/partners/pages/_app.tsx
  sites/partners/pages/users/terms.tsx
  sites/partners/src/users/FormUserConfirm.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/partners/types/md.d.ts
  ui-components/__tests__/authentication/RequireLogin.test.tsx
  ui-components/__tests__/authentication/Timeout.test.tsx
  ui-components/index.ts
  ui-components/src/authentication/AuthContext.ts
  ui-components/src/authentication/RequireLogin.tsx
  ui-components/src/locales/general.json
  ui-components/src/overlays/Overlay.scss
  ui-components/src/page_components/sign-in/FormTerms.tsx
  ui-components/src/sections/MarkdownSection.scss
  ui-components/src/sections/MarkdownSection.tsx
Labels: needs design review, ready to merge

#2653 fix: swap listing name h5 with h1 for screen reader compatibility
  ui-components/src/blocks/FormCard.tsx
Labels: ready to merge

#2630 feat(backend): add order param to listings GET endpoint
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/types/listing-orderby-enum.ts
  backend/core/src/migration/1649260977278-close-overdue-listings.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs changes

#2612 feat: refactor ada form fields
  shared-helpers/src/formKeys.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/applications/PaperApplicationForm/FormTypes.ts
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/public/pages/applications/household/ada.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#2558 2510/updated copy on the application confirmation screen
  sites/partners/cypress/integration/04-application.spec.ts
  sites/public/cypress/integration/pages/application/review/confirmation.spec.ts
  sites/public/pages/applications/review/confirmation.tsx
  ui-components/index.ts
  ui-components/src/global/markdown.scss
  ui-components/src/locales/general.json
  ui-components/src/page_components/ApplicationTimeline.scss
  ui-components/src/page_components/ApplicationTimeline.tsx
Labels: ready to merge

#2650 2481/resend confirmation public
  sites/partners/pages/sign-in.tsx
  sites/public/pages/sign-in.tsx
  ui-components/index.ts
  ui-components/src/page_components/sign-in/FormSignIn.tsx
  ui-components/src/page_components/sign-in/ResendConfirmationModal.tsx
Labels: ready for qa

#2648 feat: new category table component
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/src/occupancyFormatting.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailListingPhoto.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPreferences.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/__tests__/tables/CategoryTable.test.tsx
  ui-components/__tests__/tables/GroupedTable.test.tsx
  ui-components/__tests__/tables/MinimalTable.test.tsx
  ui-components/__tests__/tables/StackedTable.test.tsx
  ui-components/__tests__/tables/StandardTable.test.tsx
  ui-components/index.ts
  ui-components/src/global/tables.scss
  ui-components/src/global/text.scss
  ui-components/src/headers/Heading.stories.tsx
  ui-components/src/headers/Heading.tsx
  ui-components/src/helpers/tableSummaries.tsx
  ui-components/src/page_components/listing/ContentAccordion.stories.tsx
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/UnitTables.tsx
  ui-components/src/prototypes/SummaryCard.stories.tsx
  ui-components/src/sections/GridSection.stories.tsx
  ui-components/src/tables/CategoryTable.stories.tsx
  ui-components/src/tables/CategoryTable.tsx
  ui-components/src/tables/GroupedTable.stories.tsx
  ui-components/src/tables/GroupedTable.tsx
  ui-components/src/tables/MinimalTable.stories.tsx
  ui-components/src/tables/MinimalTable.tsx
  ui-components/src/tables/StackedTable.stories.tsx
  ui-components/src/tables/StackedTable.tsx
  ui-components/src/tables/StandardTable.stories.tsx
  ui-components/src/tables/StandardTable.tsx
Labels: SF Request

#2661 feat: min max occupancy validation in Add Unit
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Labels: needs review(s)

#2597 2475/css variables theming
  CODE_OF_CONDUCT.md
  docs/Styling.md
  docs/Styling2ndGen.md
  ui-components/.storybook/constants.ts
  ui-components/.storybook/main.js
  ui-components/.storybook/preview-head.html
  ui-components/.storybook/preview.ts
  ui-components/README.md
  ui-components/package.json
  ui-components/src/actions/Button.docs.mdx
  ui-components/src/actions/Button.scss
  ui-components/src/actions/Button.stories.tsx
  ui-components/src/global/app-css.scss
  ui-components/src/global/mixins.scss
  ui-components/src/global/tokens/borders.scss
  ui-components/src/global/tokens/colors.scss
  ui-components/src/global/tokens/fonts.scss
  ui-components/src/global/tokens/screens.scss
  ui-components/src/global/tokens/sizes.scss
  ui-components/src/headers/PageHeader.docs.mdx
  ui-components/src/headers/PageHeader.scss
  ui-components/src/headers/PageHeader.stories.tsx
  ui-components/src/headers/PageHeader.tsx
  ui-components/src/prototypes/Swatch.tsx
  ui-components/tailwind.config.js
  ui-components/tailwind.tosass.js
  yarn.lock
Labels: needs review(s)

#2683 fix: Add admins into users table
  sites/partners/lib/hooks.ts
Labels: ready to merge

#2696 feat: adding alameda prog and prefs
  backend/core/src/migration/1650934163344-alameda-programs-and-preferences.ts
Labels: needs review(s)

#2694 style: language button margin bottom
  sites/public/pages/applications/start/choose-language.tsx
Labels: ready to merge, needs qa notes

#2616 2145/application search requirements
  backend/core/src/applications/dto/paginated-application-list-query-params.ts
  backend/core/src/shared/decorators/isLength.decorator.ts
  backend/core/test/applications/applications.e2e-spec.ts
  sites/partners/lib/hooks.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/listings/[id]/applications/index.tsx
Labels: ready to merge

#2703 fix: authservice.token data null issue
  backend/core/src/auth/controllers/auth.controller.ts
  backend/core/src/auth/dto/token.dto.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s)

#2691 refactor: remove business logic, strings from application fee component
  shared-helpers/__tests__/stringFormatting.test.ts
  shared-helpers/src/stringFormatting.ts
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/AdditionalFees.test.tsx
  ui-components/src/page_components/listing/AdditionalFees.stories.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: needs review(s), SF Request

#2687 fix: ux updates for new listing card design
  sites/public/src/ListingView.tsx
  ui-components/src/global/text.scss
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: needs design review

#2700 fix: check for empty translations before sending to google translate
  backend/core/src/translations/services/translations.service.ts
Labels: ready to merge
