Repository bloom-housing/bloom, pull requests merged in 2022-01, with the labels that each got.

#2244 feat(backend): add user password expiration
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/dto/user-create.dto.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/guards/user-profile-authz.guard.ts
  backend/core/src/auth/passport-strategies/jwt.strategy.ts
  backend/core/src/auth/passport-strategies/local.strategy.spec.ts
  backend/core/src/auth/passport-strategies/local.strategy.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/auth/user-errors.ts
  backend/core/src/migration/1638356116695-add-user-password-outdating-fields.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/users/FormUserManage.tsx
  ui-components/__tests__/authentication/RequireLogin.test.tsx
  ui-components/__tests__/authentication/Timeout.test.tsx
  ui-components/src/locales/general.json
Labels: reviewed

#2258 test: adds cypress test coverage
  backend/core/test/listings/listings.e2e-spec.ts
  sites/partners/.babelrc
  sites/partners/cypress.json
  sites/partners/cypress/plugins/index.js
  sites/partners/cypress/support/index.js
  sites/partners/package.json
  sites/partners/pages/api/coverage.ts
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrograms.tsx
  sites/public/.babelrc
  sites/public/cypress.json
  sites/public/cypress/plugins/index.js
  sites/public/cypress/support/index.js
  sites/public/package.json
  sites/public/pages/api/coverage.ts
  ui-components/src/overlays/Modal.tsx
  yarn.lock
Labels: needs review(s)

#2352 fix: remove next dependency from ui-components
  sites/public/pages/forgot-password.tsx
  ui-components/src/page_components/sign-in/FormSignIn.tsx
Labels: needs review(s)

#2307 Fix checkbox rtl style
  ui-components/src/global/forms.scss
Labels: reviewed

#2316 Add public urls to jurisdiction
  backend/core/archer.ts
  backend/core/src/jurisdictions/dto/jurisdiction.dto.ts
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/migration/1639561971201-add-public-url-to-jurisdiction.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
  backend/core/types/src/archer-listing.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/lib/hooks.ts
  sites/partners/next.config.js
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/public/pages/account/StatusItemWrapper.tsx
  sites/public/pages/account/application/[id].tsx
Labels: reviewed, needs changes

#2353 refactor: prevent local reseed with cypress tests
  sites/public/cypress.json
  sites/public/cypress/integration/pages/submit-application.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/cypress/support/index.d.ts
  sites/public/pages/applications/contact/name.tsx
  sites/public/pages/applications/start/autofill.tsx
Labels: reviewed

#2338 1290/use dayjs instead of moment
  backend/core/package.json
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/dto/listing.dto.ts
  sites/partners/lib/formatApplicationData.ts
  sites/partners/lib/helpers.ts
  sites/partners/package.json
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/users/index.tsx
  sites/partners/src/applications/ApplicationsColDefs.ts
  sites/partners/src/applications/Aside.tsx
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/lib/helpers.tsx
  sites/public/lib/hooks.ts
  sites/public/package.json
  sites/public/pages/account/StatusItemWrapper.tsx
  sites/public/pages/account/edit.tsx
  sites/public/pages/applications/view.tsx
  sites/public/pages/create-account.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/LeasingAgent.test.tsx
  ui-components/package.json
  ui-components/src/forms/DOBField.tsx
  ui-components/src/forms/DateField.tsx
  ui-components/src/forms/TimeField.tsx
  ui-components/src/helpers/dateToString.ts
  ui-components/src/notifications/ApplicationStatus.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/ListingUpdated.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventDateSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/LotteryResultsEvent.tsx
  yarn.lock
Labels: reviewed

#2357 2098/unifies logic around listingid
  backend/core/src/applications/services/applications.service.ts
Labels: needs review(s), reviewed

#2377 fix: listings group expandable section css updates
  ui-components/__tests__/page_components/ListingsGroup.test.tsx
  ui-components/src/icons/Icon.stories.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/page_components/listing/ListingsGroup.scss
  ui-components/src/page_components/listing/ListingsGroup.stories.tsx
  ui-components/src/page_components/listing/ListingsGroup.tsx
Labels: SF Request, reviewed

#2248 test: add partners cypress ci job
  .circleci/config.yml
  sites/partners/cypress/fixtures/cypress-automated-image-upload-071e2ab9-5a52-4f34-85f0-e41f696f4b96.jpeg
  sites/partners/cypress/fixtures/listingImage.json
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/package.json
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/tsconfig.json
  ui-components/src/forms/Dropzone.tsx
Labels: needs review(s)

#2320 fix: open house events can now be edited and work cross-browser
  sites/partners/lib/helpers.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/listings/PaperListingForm/formatters/EventsFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
Labels: needs review(s)

#2386 2165/rosefield preference updates
  ui-components/src/locales/general.json
Labels: needs review(s)

#2362 fix: dates showing as invalid in send by mail section
  backend/core/archer.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/types/listing-application-address-type.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1641855882656-remove-application-due-time.ts
  backend/core/src/migration/1641860318345-add-mailing-address-type.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/translations/services/translations.service.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/__tests__/BooleansFormatter.test.ts
  sites/partners/__tests__/DatesFormatter.test.ts
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
  sites/partners/src/listings/PaperListingForm/formatters/DatesFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/public/lib/helpers.tsx
  sites/public/lib/hooks.ts
  sites/public/pages/applications/contact/name.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/SubmitApplication.test.tsx
  ui-components/src/actions/Button.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/Select.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventDateSection.tsx
Labels: needs review(s)

#2395 fix: partners render issue
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s)

#2407 feat: listing card takes optional children
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: needs review(s), SF Request

#2318 1932/ga updates
  shared-helpers/index.ts
  shared-helpers/src/gtm.ts
  sites/public/lib/constants.ts
  sites/public/pages/account/applications.tsx
  sites/public/pages/account/dashboard.tsx
  sites/public/pages/account/edit.tsx
  sites/public/pages/create-account.tsx
  sites/public/pages/disclaimer.tsx
  sites/public/pages/forgot-password.tsx
  sites/public/pages/index.tsx
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/pages/listings.tsx
  sites/public/pages/privacy.tsx
  sites/public/pages/reset-password.tsx
  sites/public/pages/sign-in.tsx
Labels: needs review(s)

#2428 fix: issues with public app and re adds auto save
  sites/public/lib/ApplicationConductor.ts
  sites/public/pages/_app.tsx
  sites/public/pages/applications/start/autofill.tsx
  sites/public/pages/applications/start/choose-language.tsx
Labels: needs review(s), reviewed

#2430 fix: ami charts without all households
  backend/core/src/seeder/seeds/ami-charts/default-ami-chart.ts
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
Labels: needs review(s), reviewed

#2418 chore: add translations for per month/year in hmi table
  ui-components/src/locales/es.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2434 fix: Fix infinite page width
  sites/public/src/ListingView.tsx
  ui-components/src/global/lists.scss
Labels: needs review(s)

#2435 refactor: Increase textarea limits
  sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx
Labels: needs review(s)

#2412 2328/address verification
  sites/public/cypress/integration/pages/application/contact/address.spec.ts
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/pages/applications/contact/address.tsx
  sites/public/src/forms/applications/ValidateAddress.tsx
  ui-components/src/locales/general.json
Labels: reviewed, needs changes

#2452 chore: add translation for household changes question
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: ready to merge
