Repository bloom-housing/bloom, pull requests merged in 2022-07, with the labels that each got.

#2851 fix: switch back to padding for image card leader
  ui-components/src/blocks/ImageCard.scss
Labels: ready to merge

#2812 2730/new partner email
  backend/core/package.json
  backend/core/src/migration/1655122535654-update-invite-email-text.ts
  backend/core/src/migration/1655299904609-add-default-email-translations.ts
  backend/core/src/shared/views/invite.hbs
  backend/core/src/shared/views/partials/header.hbs
Labels: ready to merge

#2799 Feat/partners breadcrumbs nav
  backend/core/src/seeder/seeds/jurisdictions.ts
  sites/partners/cypress/integration/03-listing.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/application/[id]/edit.tsx
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/add.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/listings/[id]/edit.tsx
  sites/partners/pages/listings/[id]/flags/[flagId]/index.tsx
  sites/partners/pages/listings/[id]/flags/index.tsx
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/pages/listings/add.tsx
  sites/partners/pages/settings/index.tsx
  sites/partners/pages/users/index.tsx
  sites/partners/src/applications/ApplicationSecondaryNav.tsx
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/listings/ListingStatusBar.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  ui-components/index.ts
  ui-components/src/headers/PageHeader.scss
  ui-components/src/headers/PageHeader.tsx
  ui-components/src/navigation/TabNav.scss
  ui-components/src/page_components/NavigationHeader.scss
  ui-components/src/page_components/NavigationHeader.tsx
Labels: ready to merge

#2828 feat: populate jurisdictional preferences on settings page
  backend/core/src/preferences/dto/preference.dto.ts
  backend/core/src/preferences/preferences.service.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/settings/index.tsx
  ui-components/src/blocks/StandardCard.scss
Labels: ready to merge

#2843 Core Utilities/Additional Fees Update
  backend/core/src/assets/assets.controller.spec.ts
  backend/core/src/email/email.service.spec.ts
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing-utilities.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing-utilities.entity.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/migration/1656447572782-add-utilities.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/src/units/entities/unit.entity.ts
  backend/core/test/authz/authz.e2e-spec.ts
  backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/formKeys.ts
  sites/partners/lib/helpers.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/AdditionalFees.test.tsx
  ui-components/src/blocks/InfoCard.scss
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
  ui-components/src/page_components/listing/AdditionalFees.stories.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: ready to merge

#2875 fix: fix email from address
  backend/core/src/seeder/seeds/jurisdictions.ts
Labels: ready to merge

#2859 fix: ux updates and bug fixes for sidebar components
  sites/public/pages/applications/preferences/all.tsx
  ui-components/index.ts
  ui-components/src/actions/Button.scss
  ui-components/src/actions/Button.stories.tsx
  ui-components/src/actions/Button.tsx
  ui-components/src/actions/ExpandableContent.stories.tsx
  ui-components/src/actions/ExpandableContent.tsx
  ui-components/src/actions/LinkButton.stories.tsx
  ui-components/src/actions/LinkButton.tsx
  ui-components/src/page_components/listing/listing_sidebar/ExpandableSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/SidebarBlock.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/SidebarBlock.tsx
Labels: needs review(s)

#2848 2792/juris admin user list filtering
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/filters/user-query-filter.ts
  backend/core/src/auth/guards/admin-or-jurisidictional-admin.guard.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/migration/1656362047737-user-role-updates.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/shared/query-filter/base-query-filter.ts
  backend/core/src/shared/query-filter/index.ts
  shared-helpers/src/formKeys.ts
  sites/partners/cypress/fixtures/jurisdictionalAdmin.json
  sites/partners/cypress/integration/02-mfa.spec.ts
  sites/partners/cypress/integration/06-user-mangement.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/layouts/index.tsx
  sites/partners/pages/users/index.tsx
  sites/partners/src/users/FormUserManage.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#2855 feat(backend): refactor listings query building
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/services/applications.service.ts
  backend/core/src/auth/auth.module.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/db/listing-query-builder.ts
  backend/core/src/listings/db/listing.repository.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/view.ts
  backend/core/test/applications/applications.e2e-spec.ts
Labels: ready to merge

#2895 2833/multilevel side nav
  ui-components/__tests__/navigation/SideNav.test.tsx
  ui-components/src/global/blocks.scss
  ui-components/src/global/tokens/screens.scss
  ui-components/src/navigation/SideNav.docs.mdx
  ui-components/src/navigation/SideNav.scss
  ui-components/src/navigation/SideNav.stories.tsx
  ui-components/src/navigation/SideNav.tsx
  ui-components/tailwind.config.js
Labels: ready to merge

#2897 fix: render html address properly
  ui-components/package.json
  ui-components/src/helpers/MultiLineAddress.tsx
  yarn.lock
Labels: needs review(s)

#2902 fix: allow jsx in expandable section
  ui-components/src/page_components/listing/listing_sidebar/ExpandableSection.tsx
Labels: needs review(s), SF Request

#2896 2849/media card component
  ui-components/index.ts
  ui-components/src/actions/Video.scss
  ui-components/src/actions/Video.tsx
  ui-components/src/blocks/MediaCard.scss
  ui-components/src/blocks/MediaCard.stories.tsx
  ui-components/src/blocks/MediaCard.tsx
Labels: ready to merge

#2844 2801/multi-select combo box component
  ui-components/__tests__/forms/MultiSelectField.test.tsx
  ui-components/index.ts
  ui-components/package.json
  ui-components/src/forms/MultiSelectField.docs.mdx
  ui-components/src/forms/MultiSelectField.scss
  ui-components/src/forms/MultiSelectField.stories.tsx
  ui-components/src/forms/MultiSelectField.tsx
  yarn.lock
Labels: needs review(s), needs changes

#2893 2791/jurisdictional admin listings
  backend/core/src/activity-log/interceptors/activity-log.interceptor.ts
  backend/core/src/ami-charts/ami-charts.controller.ts
  backend/core/src/application-methods/application-methods.controller.ts
  backend/core/src/applications/applications.controller.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/enum/user-role-enum.ts
  backend/core/src/auth/guards/admin-or-jurisidictional-admin.guard.ts
  backend/core/src/auth/guards/authz.guard.ts
  backend/core/src/auth/services/authz.service.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/jurisdictions/jurisdictions.controller.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/paper-applications/paper-applications.controller.ts
  backend/core/src/preferences/preferences.controller.ts
  backend/core/src/program/programs.controller.ts
  backend/core/src/reserved-community-type/reserved-community-types.controller.ts
  backend/core/src/translations/translations.controller.ts
  backend/core/src/unit-accessbility-priority-types/unit-accessibility-priority-types.controller.ts
  backend/core/src/unit-rent-types/unit-rent-types.controller.ts
  backend/core/src/unit-types/unit-types.controller.ts
  backend/core/src/units/units.controller.ts
  backend/core/test/activity-logs/activity-log.e2e-spec.ts
  backend/core/test/afs/afs.e2e-spec.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/application/[id]/index.tsx
  sites/partners/pages/index.tsx
  sites/partners/src/ListingGuard.tsx
  sites/partners/src/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/users/FormUserManage.tsx
  yarn.lock
Labels: needs review(s)

#2898 2818/existing user updates
  backend/core/src/auth/services/user.service.ts
  backend/core/src/email/email.service.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/migration/1658246384901-update-translations.ts
  backend/core/src/shared/views/portal-account-update.hbs
Labels: needs review(s), needs changes

#2910 feat(eventsection): allow EventSection to lowercase date
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx
Labels: needs review(s)
