Repository bloom-housing/bloom, pull requests merged in 2022-08, with the labels that each got.

#2862 2838/multiple photos and modal
  ui-components/__tests__/blocks/ImageCard.test.tsx
  ui-components/src/blocks/ImageCard.docs.mdx
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/blocks/ImageCard.stories.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/overlays/Modal.docs.mdx
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.tsx
  ui-components/src/overlays/Overlay.scss
Labels: ready to merge

#2912 feat(errormessage): add classname to errormessage; apply styles to Field
  ui-components/src/forms/HouseholdSizeField.tsx
  ui-components/src/forms/Textarea.scss
  ui-components/src/global/forms.scss
  ui-components/src/notifications/ErrorMessage.tsx
  ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
Labels: ready to merge

#2926 feat(expandabletext): remove translations;pass markdown props through…
  sites/public/src/ListingView.tsx
  ui-components/__tests__/actions/ExpandableText.test.tsx
  ui-components/src/actions/ExpandableText.stories.tsx
  ui-components/src/actions/ExpandableText.tsx
  ui-components/src/sections/InfoCardGrid.stories.tsx
Labels: needs review(s)

#2946 fix: fix for big timeout on flagged set
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  sites/partners/src/flags/flagSetCols.tsx
Labels: needs review(s)

#2953 fix: fix for big timeout on flagged set
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  sites/partners/src/flags/flagSetCols.tsx
Labels: needs review(s)

#2948 fix: replace usage of sanitize-html
  ui-components/package.json
  ui-components/src/helpers/MultiLineAddress.tsx
  yarn.lock
Labels: needs review(s)

#2943 fix: ensure listing card link region covers image tags
  ui-components/src/page_components/listing/ListingCard.scss
Labels: ready to merge

#2947 feat(listings): update default sort of listings
  backend/core/src/listings/db/listing-query-builder.ts
  backend/core/src/listings/types/listing-orderby-enum.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/hooks.ts
Labels: ready to merge

#2945 fix(paperlistform): adjust padding on add listing form
  sites/partners/src/listings/PaperListingForm/sections/AdditionalDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalEligibility.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
Labels: ready to merge

#2963 fix: update to resolve issue with migration
  backend/core/src/migration/1655821661726-remove-property-relation.ts
Labels: needs review(s)

#2954 feat(lottery): add edit lottery results functionality
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
Labels: ready to merge

#2970 fix: image width fix for tablet screen sizes
  ui-components/src/blocks/ImageCard.scss
Labels: SF Request, ready to merge

#2965 feat(expandabletext): add classname to expandable text button
  ui-components/src/actions/ExpandableText.stories.tsx
  ui-components/src/actions/ExpandableText.tsx
Labels: ready to merge

#2966 fix: update for migration
  backend/core/src/migration/1658871879940-multiselect-question.ts
Labels: ready to merge

#2974 fix: add a11y linting tools and fix errors
  .eslintrc.js
  package.json
  sites/partners/pages/settings/index.tsx
  sites/partners/src/LinkComponent.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/public/layouts/application.tsx
  sites/public/pages/account/application/[id].tsx
  sites/public/pages/account/edit.tsx
  sites/public/pages/applications/financial/income.tsx
  sites/public/pages/applications/household/member.tsx
  sites/public/pages/applications/review/confirmation.tsx
  sites/public/pages/applications/view.tsx
  sites/public/src/LinkComponent.tsx
  sites/public/src/forms/applications/FormBackLink.tsx
  sites/public/src/forms/applications/FormSummaryDetails.tsx
  ui-components/__tests__/sections/GridSection.test.tsx
  ui-components/src/actions/ExpandableText.tsx
  ui-components/src/blocks/MediaCard.scss
  ui-components/src/blocks/MediaCard.tsx
  ui-components/src/forms/Form.tsx
  ui-components/src/headers/SiteHeader.tsx
  ui-components/src/navigation/ProgressNav.scss
  ui-components/src/navigation/ProgressNav.tsx
  ui-components/src/overlays/Overlay.tsx
  ui-components/src/page_components/forgot-password/FormForgotPassword.tsx
  ui-components/src/page_components/listing/ListingMap.tsx
  ui-components/src/page_components/listing/listing_sidebar/SidebarBlock.tsx
  ui-components/src/page_components/sign-in/FormSignIn.tsx
  ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
  ui-components/src/sections/GridSection.stories.tsx
  ui-components/src/sections/GridSection.tsx
  yarn.lock
Labels: ready to merge

#2958 2918/add button group
  ui-components/.storybook/preview.ts
  ui-components/__tests__/actions/ButtonGroup.test.tsx
  ui-components/index.ts
  ui-components/src/actions/ButtonGroup.docs.mdx
  ui-components/src/actions/ButtonGroup.scss
  ui-components/src/actions/ButtonGroup.stories.tsx
  ui-components/src/actions/ButtonGroup.tsx
  ui-components/src/prototypes/Swatch.tsx
Labels: ready to merge

#2987 fix: update to get migration to run on dev
  backend/core/src/migration/1658871879940-multiselect-question.ts
Labels: 1 review needed

#2990 fix: Migration hotfix 2
  backend/core/src/migration/1658871879940-multiselect-question.ts
Labels: ready to merge

#2989 feat: show preference details on listing form
  backend/core/src/seeder/seeds/listings/shared.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  ui-components/src/overlays/Drawer.scss
Labels: needs design review

#2985 feat: managing preferences
  backend/core/src/seeder/seeds/listings/shared.ts
  shared-helpers/src/multiselectQuestions.tsx
  sites/partners/cypress/integration/08-preference-management.spec.ts
  sites/partners/lib/hooks.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/settings/index.tsx
  sites/partners/src/settings/ManageIconSection.tsx
  sites/partners/src/settings/PreferenceDrawer.tsx
  sites/public/src/ApplicationMultiselectQuestionStep.tsx
  sites/public/src/ListingView.tsx
Labels: ready to merge

#2994 fix: styling precedence issues in preferences
  backend/core/src/multiselect-question/multiselect-question.controller.ts
  sites/partners/layouts/index.tsx
  sites/partners/tailwind.config.js
  sites/public/tailwind.config.js
Labels: ready to merge

#2999 fix: add margin in contact section
  ui-components/src/page_components/listing/listing_sidebar/Contact.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Contact.tsx
Labels: sf request, ready to merge

#2950 2919/progress bar update
  ui-components/src/locales/general.json
  ui-components/src/navigation/ProgressNav.docs.mdx
  ui-components/src/navigation/ProgressNav.scss
  ui-components/src/navigation/ProgressNav.stories.tsx
  ui-components/src/navigation/ProgressNav.tsx
Labels: ready to merge

#3006 fix: remove export button from duplicate pages, fix table widths
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/pages/listings/[id]/applications/resolved/index.tsx
  sites/partners/pages/listings/[id]/flags/[flagId]/index.tsx
  sites/partners/pages/listings/[id]/flags/index.tsx
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/pages/users/index.tsx
  sites/partners/src/applications/helpers.ts
  ui-components/src/page_components/NavigationHeader.tsx
  ui-components/src/tables/AgTable.tsx
Labels: ready to merge, do not merge

#2968 2940/media modal sync
  ui-components/src/blocks/MediaCard.docs.mdx
  ui-components/src/blocks/MediaCard.scss
  ui-components/src/blocks/MediaCard.stories.tsx
  ui-components/src/blocks/MediaCard.tsx
  ui-components/src/overlays/Modal.scss
Labels: ready to merge

#2784 refactor: detroit improvements
  backend/core/src/auth/passport-strategies/jwt.strategy.ts
  backend/core/src/shared/views/change-email.hbs
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/public/pages/create-account.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/forms/FieldGroup.stories.tsx
Labels: ready to merge

#2988 fix(login): too many login attempts fix
  backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
  backend/core/test/user/user.e2e-spec.ts
  shared-helpers/src/catchNetworkError.ts
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: ready to merge

#2961 2835/async duplicates processing
  backend/core/package.json
  backend/core/src/ami-charts/dto/ami-chart.dto.ts
  backend/core/src/app.module.ts
  backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-boostrap.service.ts
  backend/core/src/application-flagged-sets/application-flagged-sets-cronjob-consumer.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.controller.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.module.ts
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  backend/core/src/application-flagged-sets/constants/applications-flagged-sets-constants.ts
  backend/core/src/application-flagged-sets/entities/application-flagged-set.entity.ts
  backend/core/src/application-methods/dto/application-method.dto.ts
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/dto/application-update.dto.ts
  backend/core/src/applications/services/applications.service.ts
  backend/core/src/assets/dto/asset.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/jurisdictions/dto/jurisdiction-update.dto.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-event.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1658992843452-add-afs-related-properties-to-listing.ts
  backend/core/src/paper-applications/dto/paper-application.dto.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/applications.ts
  backend/core/src/shared/shared.module.ts
  backend/core/src/translations/dto/translation.dto.ts
  backend/core/src/units/dto/unit-ami-chart-override-update.dto.ts
  backend/core/src/units/dto/unit-update.dto.ts
  backend/core/test/afs/afs.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  yarn.lock
Labels: ready to merge

#3016 fix: null app fee
  sites/public/src/ListingView.tsx
  ui-components/src/page_components/listing/AdditionalFees.stories.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: ready to merge

#3018 2891/add sign up to beginning of application flow
  sites/public/pages/applications/start/choose-language.tsx
Labels: ready to merge

#3017 fix: remove select text from multiselect application questions
  sites/public/pages/applications/financial/vouchers.tsx
  sites/public/pages/applications/household/ada.tsx
  sites/public/pages/applications/household/changes.tsx
  sites/public/pages/applications/household/student.tsx
  sites/public/src/ApplicationMultiselectQuestionStep.tsx
Labels: 1 review needed

#3005 fix: table columns should take up full width
  sites/partners/pages/index.tsx
  sites/partners/pages/users/index.tsx
  ui-components/src/tables/AgTable.tsx
Labels: ready to merge

#3012 refactor: allow custom strings
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/ReferralApplication.test.tsx
  ui-components/src/blocks/HousingCounselor.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/blocks/StatusItem.tsx
  ui-components/src/forms/DOBField.tsx
  ui-components/src/forms/DateField.tsx
  ui-components/src/forms/Dropzone.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/forms/HouseholdMemberForm.tsx
  ui-components/src/forms/HouseholdSizeField.tsx
  ui-components/src/forms/TimeField.tsx
  ui-components/src/headers/Hero.tsx
  ui-components/src/headers/SiteHeader.tsx
  ui-components/src/helpers/formOptions.tsx
  ui-components/src/helpers/formatYesNoLabel.ts
  ui-components/src/navigation/ProgressNav.tsx
  ui-components/src/notifications/StatusMessage.tsx
  ui-components/src/page_components/ApplicationTimeline.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/ListingUpdated.tsx
  ui-components/src/page_components/listing/listing_sidebar/OrDivider.tsx
  ui-components/src/page_components/listing/listing_sidebar/ReferralApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/ReferralApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx
  ui-components/src/tables/AgTable.tsx
  ui-components/src/tables/StandardTable.tsx
Labels: sf request, 1 review needed

#3014 refactor: alert box v2 styling refactor
  ui-components/src/notifications/AlertBox.docs.mdx
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.stories.tsx
  ui-components/src/notifications/AlertBox.tsx
  ui-components/src/notifications/alertTypes.ts
Labels: sf request, ready to merge

#3021 fix(application): remove programs from autofill
  sites/public/lib/appAutofill.ts
Labels: ready to merge
