Repository bloom-housing/bloom, pull requests merged in 2022-05, with the labels that each got.

#2677 feat(backend): improve ami chart dto definitions
  backend/core/archer.ts
  backend/core/src/ami-charts/dto/ami-chart.dto.ts
  backend/core/src/ami-charts/entities/ami-chart.entity.ts
  backend/core/src/shared/types/has-keys.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/types/src/archer-listing.ts
  backend/core/types/src/backend-swagger.ts
  ui-components/src/page_components/sign-in/ResendConfirmationModal.tsx
Labels: discussion

#2689 refactor: remove business logic, strings from waitlist component
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/QuantityRowSection.test.tsx
  ui-components/__tests__/page_components/Waitlist.test.tsx
  ui-components/index.ts
  ui-components/src/global/text.scss
  ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx
Labels: SF Request, ready to merge

#2675 refactor: remove backend dependencies from sidebar application components
  shared-helpers/__tests__/postmarkString.test.ts
  shared-helpers/index.ts
  shared-helpers/src/postmarkString.ts
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/Contact.test.tsx
  ui-components/__tests__/page_components/ContactAddress.test.tsx
  ui-components/__tests__/page_components/LeasingAgent.test.tsx
  ui-components/__tests__/page_components/SidebarAddress.test.tsx
  ui-components/__tests__/page_components/SubmitApplication.test.tsx
  ui-components/index.ts
  ui-components/src/global/text.scss
  ui-components/src/headers/Heading.stories.tsx
  ui-components/src/headers/Heading.tsx
  ui-components/src/helpers/MultiLineAddress.stories.tsx
  ui-components/src/helpers/MultiLineAddress.tsx
  ui-components/src/helpers/OneLineAddress.stories.tsx
  ui-components/src/helpers/OneLineAddress.tsx
  ui-components/src/helpers/address.tsx
  ui-components/src/page_components/listing/ListingMap.tsx
  ui-components/src/page_components/listing/listing_sidebar/Contact.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/Contact.tsx
  ui-components/src/page_components/listing/listing_sidebar/ContactAddress.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/ContactAddress.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
  ui-components/src/page_components/listing/listing_sidebar/SidebarAddress.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/SubmitApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx
Labels: needs review(s), SF Request

#2713 fix: footer alignment issue with overflowing links
  ui-components/src/footers/SiteFooter.stories.tsx
  ui-components/src/navigation/FooterNav.scss
Labels: high priority, SF Request, ready to merge

#2702 fix: use appropriate copy for FCFS vs Lottery in Application Confirmation screen
  sites/public/pages/applications/review/confirmation.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#2704 2681/listing application back button
  sites/public/pages/applications/contact/address.tsx
Labels: needs review(s)

#2714 feat(backend): add search param to GET /user/list endpoint
  backend/core/src/auth/dto/user-list-query-params.ts
  backend/core/src/auth/repositories/user-repository.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s)

#2728 feat: missing translations, script to merge new translations
  ui-components/scripts/generate-translations.ts
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2733 Reverse deployment 05-16-2022
  backend/core/CHANGELOG.md
  backend/core/package.json
  backend/core/src/migration/1650934163344-alameda-programs-and-preferences.ts
  shared-helpers/CHANGELOG.md
  shared-helpers/package.json
  sites/partners/CHANGELOG.md
  sites/partners/package.json
  sites/partners/src/ConfirmationModal.tsx
  sites/public/CHANGELOG.md
  sites/public/package.json
  ui-components/CHANGELOG.md
  ui-components/package.json
  ui-components/src/locales/vi.json
  ui-components/src/page_components/listing/ListingMap.tsx
Labels: needs review(s)

#2692 Add order/orderBy array support for listings query params
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/types/listings-api-extra-models.ts
  backend/core/src/listings/validators/order-query-param-validator.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/index.tsx
Labels: needs review(s), needs changes

#2732 feat(proxy): add nginx config for jurisdictions
  backend/proxy/Dockerfile
  backend/proxy/default.conf
  backend/proxy/shared-location.conf
Labels: needs review(s)

#2749 fix: check for empty url before rendering
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
Labels: needs review(s)

#2744 chore: add translations for the Confirmation form step
  sites/public/.env.template
  sites/public/lib/AppSubmissionContext.ts
  sites/public/pages/applications/review/confirmation.tsx
  sites/public/pages/applications/start/choose-language.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2740 2722/public listing summary updates
  backend/core/archer.ts
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-availability-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.ts
  backend/core/src/migration/1652833763955-add-listing-availability-field.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami-and-percentages.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/src/units/entities/unit.entity.ts
  backend/core/types/src/archer-listing.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/__tests__/unitTypes.test.ts
  sites/partners/cypress/integration/03-listing.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/helpers/tableSummaries.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#2759 refactor: refactor user filters to pull in improvements from detroit
  backend/core/src/auth/filters/user-query-filter.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/shared/query-filter/index.ts
Labels: ready to merge

#2737 2172/visual design bugs
  sites/public/pages/account/application/[id].tsx
  sites/public/pages/applications/contact/address.tsx
  sites/public/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/pages/applications/contact/alternate-contact-name.tsx
  sites/public/pages/applications/contact/alternate-contact-type.tsx
  sites/public/pages/applications/contact/name.tsx
  sites/public/pages/applications/financial/income.tsx
  sites/public/pages/applications/financial/vouchers.tsx
  sites/public/pages/applications/household/ada.tsx
  sites/public/pages/applications/household/add-members.tsx
  sites/public/pages/applications/household/changes.tsx
  sites/public/pages/applications/household/live-alone.tsx
  sites/public/pages/applications/household/member.tsx
  sites/public/pages/applications/household/members-info.tsx
  sites/public/pages/applications/household/preferred-units.tsx
  sites/public/pages/applications/household/programs.tsx
  sites/public/pages/applications/household/student.tsx
  sites/public/pages/applications/preferences/all.tsx
  sites/public/pages/applications/preferences/general.tsx
  sites/public/pages/applications/review/demographics.tsx
  sites/public/pages/applications/review/summary.tsx
  sites/public/pages/applications/review/terms.tsx
  sites/public/pages/applications/start/autofill.tsx
  sites/public/pages/applications/start/choose-language.tsx
  sites/public/pages/applications/start/what-to-expect.tsx
  sites/public/pages/applications/view.tsx
  ui-components/__tests__/blocks/FormCard.test.tsx
  ui-components/src/blocks/FormCard.scss
  ui-components/src/blocks/FormCard.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/global/blocks.scss
  ui-components/src/overlays/Overlay.scss
Labels: needs review(s)

#2711 2655/search listings
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/validators/order-query-param-validator.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/test/listings/utils/make-test-listing.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/cypress.json
  sites/partners/cypress/integration/04-application.spec.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/listings/[id]/flags/[flagId]/index.tsx
  sites/partners/pages/users/index.tsx
  ui-components/__tests__/tables/AgTable.test.tsx
  ui-components/index.ts
  ui-components/package.json
  ui-components/src/overlays/LoadingOverlay.tsx
  ui-components/src/tables/AgPagination.tsx
  ui-components/src/tables/AgTable.stories.tsx
  ui-components/src/tables/AgTable.tsx
Labels: needs review(s)
