Repository bloom-housing/bloom, pull requests merged in 2022-06, with the labels that each got.

#2767 refactor: remove some waitlist fields, update how it displays
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami-and-percentages.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  sites/partners/__tests__/WaitlistFormatter.test.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/formatters/WaitlistFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
Labels: needs review(s)

#2769 feat(modal): add option for fixed-height scrollable modal
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.stories.tsx
  ui-components/src/overlays/Modal.tsx
Labels: needs changes

#2781 feat: create table card component
  sites/partners/page_content/locale_overrides/general.json
  ui-components/__tests__/blocks/StandardCard.test.tsx
  ui-components/index.ts
  ui-components/src/blocks/StandardCard.docs.mdx
  ui-components/src/blocks/StandardCard.scss
  ui-components/src/blocks/StandardCard.stories.tsx
  ui-components/src/blocks/StandardCard.tsx
Labels: needs review(s)

#2796 refactor: remove backend deps from what to expect
  sites/public/pages/applications/preferences/all.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/actions/ExpandableContent.test.tsx
  ui-components/__tests__/page_components/ExpandableSection.test.tsx
  ui-components/__tests__/page_components/WhatToExpect.test.tsx
  ui-components/index.ts
  ui-components/src/actions/ExpandableContent.stories.tsx
  ui-components/src/actions/ExpandableContent.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/page_components/listing/listing_sidebar/ExpandableSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/ExpandableSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/WhatToExpect.tsx
Labels: needs review(s)

#2786 feat(sidenav component): update Prototype SideNav Component for Produ…
  ui-components/__tests__/navigation/SideNav.test.tsx
  ui-components/__tests__/prototypes/SideNav.test.tsx
  ui-components/src/navigation/SideNav.scss
  ui-components/src/navigation/SideNav.stories.tsx
  ui-components/src/navigation/SideNav.tsx
  ui-components/src/prototypes/SideNav.stories.tsx
  ui-components/src/prototypes/SideNav.tsx
Labels: ready to merge

#2793 refactor: remove backend deps from form options
  shared-helpers/src/formKeys.ts
  sites/partners/src/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/users/FormUserManage.tsx
  ui-components/src/helpers/formOptions.tsx
Labels: needs review(s)

#2768 Add FontAwesome icon support
  sites/public/package.json
  ui-components/package.json
  ui-components/src/actions/Button.stories.tsx
  ui-components/src/actions/Button.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/icons/FontAwesome.stories.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/notifications/ApplicationStatus.tsx
  ui-components/src/page_components/listing/ListingsGroup.tsx
  yarn.lock
Labels: ready to merge

#2794 refactor: remove backend deps from preferences helpers
  shared-helpers/index.ts
  shared-helpers/src/preferences.tsx
  sites/partners/lib/formatApplicationData.ts
  sites/partners/src/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormAlternateContact.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormPreferences.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/public/pages/applications/preferences/all.tsx
  ui-components/src/helpers/preferences.tsx
Labels: needs review(s)

#2795 refactor: remove backend deps from unit tables helpers
  shared-helpers/index.ts
  shared-helpers/src/summaryTables.tsx
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/UnitTables.test.tsx
  ui-components/index.ts
  ui-components/src/helpers/tableSummaries.tsx
  ui-components/src/page_components/listing/ContentAccordion.stories.tsx
  ui-components/src/page_components/listing/UnitTables.stories.tsx
  ui-components/src/page_components/listing/UnitTables.tsx
Labels: ready to merge

#2789 feat: add settings page to partners
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/migration/1654560903063-add-settings-jurisdiction-toggle.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/layouts/index.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/settings/index.tsx
Labels: needs review(s)

#2797 refactor: remove backend deps from mfa components
  sites/partners/pages/sign-in.tsx
  ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
  ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
Labels: needs review(s)

#2809 fix: make isWaitlistOpen optional
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
Labels: ready to merge

#2811 feat(expandablecontent.tsx): add classname prop
  ui-components/src/actions/ExpandableContent.tsx
Labels: ready to merge

#2810 feat: actionable row component
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/blocks/StandardCard.stories.tsx
  ui-components/src/global/tables.scss
  ui-components/src/icons/Icon.tsx
  ui-components/src/locales/general.json
  ui-components/src/tables/MinimalTable.stories.tsx
  ui-components/src/tables/StandardTable.tsx
Labels: needs review(s)

#2817 feat: creating setting wall for accessibility feat
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/migration/1655309692011-flag-for-features.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/pages/preview/listings/[id].tsx
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#2821 feat(listingcard): add compatability for jsx elements in subheader
  sites/public/lib/helpers.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: needs changes

#2764 feat(backend): add jurisdictional admin relation
  .circleci/config.yml
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/services/applications.service.ts
  backend/core/src/assets/assets.controller.spec.ts
  backend/core/src/auth/auth.module.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/controllers/user-profile.controller.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/dto/user-invite.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/entities/user-roles.entity.ts
  backend/core/src/auth/enum/authz-actions.enum.ts
  backend/core/src/auth/services/authz.service.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/custom.d.ts
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/repositories/listing.repository.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1654612292843-add-jurisdictional-admin-role.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/test/utils/make-test-listing.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s), discussion

#2788 2611/listing card accessibility 2nd gen
  sites/public/cypress/support/commands.js
  sites/public/lib/helpers.tsx
  ui-components/src/actions/Button.docs.mdx
  ui-components/src/actions/Button.scss
  ui-components/src/actions/Button.tsx
  ui-components/src/actions/LinkButton.tsx
  ui-components/src/blocks/ImageCard.docs.mdx
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/blocks/ImageCard.stories.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/global/mixins.scss
  ui-components/src/global/text.scss
  ui-components/src/global/tokens/sizes.scss
  ui-components/src/page_components/listing/ListingCard.docs.mdx
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.stories.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
  ui-components/src/text/Tag.docs.mdx
  ui-components/src/text/Tag.scss
  ui-components/src/text/Tag.stories.tsx
Labels: needs review(s)

#2831 feat(preferenceslist): move ordinal at mobile bp; update text color f…
  ui-components/src/lists/PreferencesList.scss
  ui-components/src/lists/PreferencesList.stories.tsx
Labels: needs review(s)

#2822 2783/application due date sentence
  sites/public/pages/applications/review/terms.tsx
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/tl.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: ready to merge

#2830 Flatten property relation
  backend/core/src/app.module.ts
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/listings/views/view.ts
  backend/core/src/migration/1655821661726-remove-property-relation.ts
  backend/core/src/property-groups/dto/property-group.dto.ts
  backend/core/src/property-groups/entities/property-group.entity.ts
  backend/core/src/property-groups/property-groups.controller.ts
  backend/core/src/property-groups/property-groups.module.ts
  backend/core/src/property-groups/property-groups.service.ts
  backend/core/src/property/dto/property.dto.ts
  backend/core/src/property/entities/property.entity.ts
  backend/core/src/property/properties.controller.ts
  backend/core/src/property/properties.module.ts
  backend/core/src/property/properties.service.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-bmr-chart-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami-and-percentages.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-sanjose-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/listings.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/shared/url-helper.ts
  backend/core/src/translations/services/translations.service.spec.ts
  backend/core/src/translations/services/translations.service.ts
  backend/core/src/units/dto/unit.dto.ts
  backend/core/src/units/entities/unit.entity.ts
  backend/core/test/properties/properties.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s)

#2846 fix: hide apply section if there is no data
  ui-components/__tests__/page_components/GetApplication.test.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/GetApplication.tsx
Labels: ready to merge
