Repository bloom-housing/bloom, pull requests merged in 2022-02, with the labels that each got.

#2432 feat(backend): add publishedAt and closedAt to listing entity
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1643191027392-add-dates-to-listing.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s)

#2440 feat: partners terms page
  sites/partners/src/users/FormUserConfirm.tsx
  ui-components/src/overlays/Modal.tsx
  ui-components/src/overlays/Overlay.scss
  ui-components/src/overlays/Overlay.tsx
Labels: needs review(s)

#2441 refactor: move leasing agent address on listing form
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingDetails/sections/helpers.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  ui-components/src/forms/FieldGroup.tsx
Labels: needs review(s)

#2459 2374/infinite page scroll
  sites/public/layouts/application.tsx
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#2436 2382/berkeley way customizations
  backend/core/src/applications/types/form-metadata/form-metadata.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/programHelpers.ts
  sites/partners/src/applications/PaperApplicationForm/sections/FormPrograms.tsx
  sites/public/cypress/mockData/applicationData.ts
  sites/public/pages/applications/household/programs.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#2451 fix: unit accordion radio button not showing default value
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/page_components/listing/UnitTables.tsx
Labels: reviewed

#2415 2335/fixes adding user that's already created
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/shared/filters/catch-all-filter.ts
  sites/partners/src/users/FormUserManage.tsx
  sites/public/pages/create-account.tsx
  ui-components/src/forms/DOBField.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#2354 2126/creates paper app tests on partners side
  sites/partners/cypress/fixtures/alternateContactOnlyData.json
  sites/partners/cypress/fixtures/applicantOnlyData.json
  sites/partners/cypress/fixtures/application.json
  sites/partners/cypress/fixtures/demographicsOnlyData.json
  sites/partners/cypress/fixtures/emptyApplication.json
  sites/partners/cypress/fixtures/householdDetailsOnlyData.json
  sites/partners/cypress/fixtures/householdIncomeOnlyData.json
  sites/partners/cypress/fixtures/householdMemberOnlyData.json
  sites/partners/cypress/fixtures/partialApplicationA.json
  sites/partners/cypress/integration/paperApplication.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/src/applications/Aside.tsx
  sites/partners/src/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsHouseholdIncome.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/applications/PaperApplicationDetails/sections/DetailsTerms.tsx
  sites/partners/src/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  ui-components/src/forms/FieldGroup.tsx
Labels: needs review(s)

#2455 fix: cannot remove some fields in listings management
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingDetails.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.tsx
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
Labels: needs review(s)

#2482 2419/adding SMC preferences
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2483 2468/adding dublin preferences
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#2476 feat(backend): remove assigning partner user as an application owner
  backend/core/src/applications/services/applications.service.ts
  backend/core/test/applications/applications.e2e-spec.ts
Labels: ready to merge

#2485 refactor: store email from address on jurisdiction entity
  .circleci/config.yml
  backend/core/.env.template
  backend/core/README.md
  backend/core/archer.ts
  backend/core/src/email/email.service.ts
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/migration/1644365733034-add-custom-email-from.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/shared/shared.module.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/test/jurisdictions/jurisdictions.e2e-spec.ts
  backend/core/types/src/archer-listing.ts
  backend/core/types/src/backend-swagger.ts
  docs/DeployServicesHeroku.md
  sites/public/pages/create-account.tsx
Labels: needs review(s), reviewed

#2470 feat: only show MapBox map when it's in the viewport
  ui-components/.jest/setup-tests.js
  ui-components/index.ts
  ui-components/src/helpers/useIntersect.ts
  ui-components/src/page_components/listing/ListingMap.scss
  ui-components/src/page_components/listing/ListingMap.stories.tsx
  ui-components/src/page_components/listing/ListingMap.tsx
Labels: ready to merge

#2487 fix: image gradient obscures image on mobile, is harsh in safari (#2267)
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/blocks/ImageCard.stories.tsx
Labels: SF Request

#2461 1928/adding-mfa-to-partners-portal
  backend/core/src/auth/dto/get-mfa-info-response.dto.ts
  backend/core/src/auth/dto/login.dto.ts
  backend/core/src/auth/dto/request-mfa-code-response.dto.ts
  backend/core/src/auth/dto/request-mfa-code.dto.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/email/email.service.ts
  backend/core/src/migration/1644441969354-addPhoneNumberVerified.ts
  backend/core/src/seeder/seed.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/catchNetworkError.ts
  sites/partners/cypress/fixtures/mfaUser.json
  sites/partners/cypress/integration/mfa.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/lib/signInHelpers.ts
  sites/partners/package.json
  sites/partners/pages/sign-in.tsx
  ui-components/index.ts
  ui-components/src/authentication/AuthContext.ts
  ui-components/src/forms/Field.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/sign-in/FormSignIn.tsx
  ui-components/src/page_components/sign-in/FormSignInAddPhone.tsx
  ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
  ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
  ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
  yarn.lock
Labels: needs review(s)

#2494 docs: update readme
  README.md
  ui-components/README.md
Labels: needs review(s)

#2495 refactor: remove backend dependencies from events components, consolidate
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-pending.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-results.ts
  backend/core/test/listings/listings.e2e-spec.ts
  shared-helpers/__tests__/stringFormatting.test.ts
  shared-helpers/index.ts
  shared-helpers/src/stringFormatting.ts
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/DownloadLotteryResults.test.tsx
  ui-components/__tests__/page_components/EventSection.test.tsx
  ui-components/index.ts
  ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventDateSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/LotteryResultsEvent.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/OpenHouseEvent.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/PublicLotteryEvent.tsx
Labels: needs review(s), SF Request

#2477 feat(backend): make listing image an array
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-image-update.dto.ts
  backend/core/src/listings/dto/listing-image.dto.ts
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing-image.entity.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/migration/1644581761889-convert-listing-image-to-array.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/translations/services/translations.service.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/__tests__/photos.test.ts
  shared-helpers/src/photos.ts
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/pages/listings/[id]/edit.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
Labels: reviewed

#2489 fix: add icons to unit accordions if enabled (#2372)
  ui-components/__tests__/page_components/UnitTables.test.tsx
  ui-components/src/global/headers.scss
  ui-components/src/helpers/tableSummaries.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/page_components/listing/UnitTables.stories.tsx
  ui-components/src/page_components/listing/UnitTables.tsx
Labels: reviewed

#2497 fix: use the correct AlertBox component for preview listing notice
  sites/public/pages/preview/listings/[id].tsx
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.tsx
Labels: needs review(s)

#2506 feat(backend): fix translations table relation to jurisdiction (make …
  backend/core/src/ami-charts/ami-charts.service.ts
  backend/core/src/jurisdictions/services/jurisdictions.service.ts
  backend/core/src/migration/1645001562848-make-translations-one-to-many-with-jurisdiction.ts
  backend/core/src/preferences/preferences.service.ts
  backend/core/src/program/programs.service.ts
  backend/core/src/reserved-community-type/reserved-community-types.service.ts
  backend/core/src/shared/services/abstract-service.ts
  backend/core/src/translations/entities/translation.entity.ts
Labels: needs review(s)

#2478 feat(backend): add listing order by mostRecentlyClosed param
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-orderby-enum.ts
  backend/core/src/migration/1644325106310-add-listings-closed-at-fill.ts
  backend/core/src/migration/1645110873807-setProdPublishDates.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/hooks.ts
  sites/public/pages/listings.tsx
Labels: needs review(s), needs changes

#2502 Refactor flatten property
  backend/core/src/app.module.ts
  backend/core/src/listings/db/listing.repository.ts
  backend/core/src/listings/db/listings-query-builder.ts
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/migration/1644932339393-flatten-property-into-listing.ts
  backend/core/src/property-groups/dto/property-group.dto.ts
  backend/core/src/property-groups/entities/property-group.entity.ts
  backend/core/src/property-groups/property-groups.controller.ts
  backend/core/src/property-groups/property-groups.module.ts
  backend/core/src/property-groups/property-groups.service.ts
  backend/core/src/property/dto/property.dto.ts
  backend/core/src/property/entities/property.entity.ts
  backend/core/src/property/properties.controller.ts
  backend/core/src/property/properties.module.ts
  backend/core/src/property/properties.service.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-bmr-chart-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami-and-percentages.ts
  backend/core/src/seeder/seeds/listings/listing-default-multiple-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-sanjose-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/listings.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/shared/url-helper.ts
  backend/core/src/units/dto/unit.dto.ts
  backend/core/src/units/entities/unit.entity.ts
Labels: needs review(s), on hold

#2528 feat: accordion component cleanup
  ui-components/__tests__/page_components/AdditionalFees.test.tsx
  ui-components/__tests__/page_components/ContentAccordion.test.tsx
  ui-components/__tests__/page_components/UnitTables.test.tsx
  ui-components/index.ts
  ui-components/src/global/headers.scss
  ui-components/src/icons/Icons.tsx
  ui-components/src/page_components/listing/ContentAccordion.scss
  ui-components/src/page_components/listing/ContentAccordion.stories.tsx
  ui-components/src/page_components/listing/ContentAccordion.tsx
  ui-components/src/page_components/listing/UnitTables.tsx
Labels: needs review(s), SF Request, reviewed

#2526 fix: more style tweaks for AlertBox
  sites/public/pages/preview/listings/[id].tsx
  ui-components/src/notifications/AlertBox.scss
Labels: ready to merge

#2532 feat: updates to mfa styling
  backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
  shared-helpers/src/catchNetworkError.ts
  sites/partners/lib/signInHelpers.ts
  sites/partners/pages/sign-in.tsx
  ui-components/src/blocks/FormCard.scss
  ui-components/src/forms/Field.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/forgot-password/FormForgotPassword.tsx
  ui-components/src/page_components/sign-in/FormSignIn.tsx
  ui-components/src/page_components/sign-in/FormSignInAddPhone.tsx
  ui-components/src/page_components/sign-in/FormSignInErrorBox.tsx
  ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
  ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
Labels: needs review(s)
