Repository bloom-housing/bloom, pull requests merged in 2022-11, with the labels that each got.

#3161 fix: upgrade ioredis version
  backend/core/package.json
  yarn.lock
Labels: ready to merge

#3153 fix: allow for more space for modals on mobile
  shared-helpers/src/Timeout.tsx
  sites/partners/pages/application/[id]/review.tsx
  sites/partners/pages/settings/index.tsx
  sites/partners/src/ConfirmationModal.tsx
  sites/partners/src/applications/Aside.tsx
  sites/partners/src/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/settings/PreferenceDeleteModal.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/partners/src/users/ReRequestConfirmation.tsx
  sites/public/pages/applications/start/choose-language.tsx
  sites/public/pages/create-account.tsx
  sites/public/pages/index.tsx
  sites/public/src/ConfirmationModal.tsx
  ui-components/package.json
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/overlays/Drawer.stories.tsx
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.stories.tsx
  ui-components/src/overlays/Modal.tsx
  ui-components/src/overlays/Overlay.tsx
  ui-components/src/page_components/sign-in/ResendConfirmationModal.tsx
  yarn.lock
Labels: sf request, ready to merge

#3163 fix: allow for scrollable modal to have flexible height
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.stories.tsx
Labels: sf request, ready to merge

#3169 feat: get rid of ui-component prerelease
  .github/workflows/release_components.yml
  README.md
Labels: 1 review needed

#3170 fix: support jsx in EventSection, QuantityRowSection
  ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.stories.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventSection.tsx
Labels: sf request, ready to merge

#3172 feat: adding UUID validation
  backend/core/src/applications/applications.controller.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/multiselect-question/multiselect-question.controller.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
Labels: ready to merge

#3168 feat: adding last run to pending page
  sites/partners/pages/listings/[id]/applications/pending/index.tsx
Labels: ready to merge

#3180 fix: cypress tests working again
  sites/partners/cypress/integration/03-listing.spec.ts
Labels: ready to merge

#3177 fix: fix text alignment on action block component
  ui-components/src/blocks/ActionBlock.scss
Labels: ready to merge

#3178 refactor: table a11y dynamic linting until performance issues are resolved
  sites/partners/pages/_app.tsx
  sites/public/pages/_app.tsx
Labels: ready to merge

#3167 feat: add startDate field to listing events
  backend/core/src/listings/entities/listing-event.entity.ts
  backend/core/src/migration/1668076003953-add-start-date.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-pending.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-results.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/events.ts
  shared-helpers/src/stringFormatting.ts
  sites/partners/src/listings/PaperListingForm/formatters/EventsFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/src/ListingView.tsx
Labels: ready to merge
