Repository bloom-housing/bloom, pull requests merged in 2023-08, with the labels that each got.

#3571 feat: (re)adding sentry to public site
  .eslintrc.js
  sites/public/.env.template
  sites/public/.gitignore
  sites/public/next.config.js
  sites/public/package.json
  sites/public/sentry.client.config.ts
  sites/public/sentry.edge.config.ts
  sites/public/sentry.server.config.ts
  sites/public/src/pages/api/sentry-example-api.js
  sites/public/src/pages/sentry-example-page.js
  sites/public/tsconfig.json
  yarn.lock
Labels: ready to merge

#3569 feat: Prisma heartbeat
  .circleci/config.yml
  backend_new/src/app.controller.spec.ts
  backend_new/src/app.controller.ts
  backend_new/src/app.module.ts
  backend_new/src/app.service.ts
  backend_new/src/controllers/app.controller.ts
  backend_new/src/main.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/services/app.service.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/multiselect-question.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/unit/services/app.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3494 feat: application get endpoints
  backend_new/package.json
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/application-factory.ts
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/unit-type-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/controllers/application.controller.ts
  backend_new/src/decorators/search-string-length-check.decorator.ts
  backend_new/src/dtos/addresses/address-get.dto.ts
  backend_new/src/dtos/application-methods/application-method-get.dto.ts
  backend_new/src/dtos/applications/accessibility.dto.ts
  backend_new/src/dtos/applications/alternate-contact.dto.ts
  backend_new/src/dtos/applications/applicant.dto.ts
  backend_new/src/dtos/applications/application-multiselect-question-option.dto.ts
  backend_new/src/dtos/applications/application-multiselect-question.dto.ts
  backend_new/src/dtos/applications/application-query-params.dto.ts
  backend_new/src/dtos/applications/application.dto.ts
  backend_new/src/dtos/applications/demographic.dto.ts
  backend_new/src/dtos/applications/household-member.dto.ts
  backend_new/src/dtos/applications/paginated-application.dto.ts
  backend_new/src/dtos/jurisdictions/jurisdiction.dto.ts
  backend_new/src/dtos/listings/listing-event.dto.ts
  backend_new/src/dtos/listings/listing-feature.dto.ts
  backend_new/src/dtos/listings/listing-get.dto.ts
  backend_new/src/dtos/listings/listing-image.dto.ts
  backend_new/src/dtos/listings/listing-multiselect-question.dto.ts
  backend_new/src/dtos/listings/listing-utility.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-option.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-get.dto.ts
  backend_new/src/dtos/paper-applications/paper-application.dto.ts
  backend_new/src/dtos/reserved-community-types/reserved-community-type.dto.ts
  backend_new/src/dtos/units/unit-get.dto.ts
  backend_new/src/dtos/units/unit-summary-get.dto.ts
  backend_new/src/dtos/units/units-summery-get.dto.ts
  backend_new/src/enums/applications/order-by-enum.ts
  backend_new/src/enums/shared/input-type-enum.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/modules/application.module.ts
  backend_new/src/services/application.service.ts
  backend_new/src/services/prisma.service.ts
  backend_new/src/utilities/applications-utilities.ts
  backend_new/src/utilities/build-pagination-meta.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/application.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/multiselect-question.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/jest-e2e.config.js
  backend_new/test/jest.config.js
  backend_new/test/unit/services/application.service.spec.ts
  backend_new/test/unit/services/unit-rent-type.service.spec.ts
  backend_new/types/src/backend-swagger.ts
  backend_new/yarn.lock
Labels: prisma rewrite

#3560 feat: prisma asset endpoint
  backend_new/.env.template
  backend_new/package.json
  backend_new/src/controllers/asset.controller.ts
  backend_new/src/dtos/assets/create-presign-upload-meta-response.dto.ts
  backend_new/src/dtos/assets/create-presigned-upload-meta.dto.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/modules/asset.module.ts
  backend_new/src/services/asset.service.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/asset.e2e-spec.ts
  backend_new/test/unit/services/asset.service.spec.ts
  backend_new/yarn.lock
Labels: prisma rewrite

#3581 feat: listings approval feature flag
  sites/partners/.env.template
  sites/partners/next.config.js
Labels: 1 review needed

#3582 feat: new listings status enum
  backend/core/src/listings/types/listing-status-enum.ts
  backend/core/src/listings/validation-pipes/listing-create-validation-pipe.ts
  backend/core/src/listings/validation-pipes/listing-update-validation-pipe.ts
  backend/core/src/migration/1691377869351-new-status-fields.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/.env.template
Labels: ready to merge

#3585 feat: refactor listing actions file
  sites/partners/src/components/listings/Aside.tsx
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/shared/StatusBar.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
Labels: ready to merge

#3546 feat: Prisma user get endpoints
  backend_new/package.json
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/user-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/controllers/user.controller.ts
  backend_new/src/dtos/users/paginated-user.dto.ts
  backend_new/src/dtos/users/user-filter-params.dto.ts
  backend_new/src/dtos/users/user-query-param.dto.ts
  backend_new/src/dtos/users/user-role.dto.ts
  backend_new/src/dtos/users/user.dto.ts
  backend_new/src/enums/user_accounts/filter-key-enum.ts
  backend_new/src/modules/ami-chart.module.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/modules/application.module.ts
  backend_new/src/modules/jurisdiction.module.ts
  backend_new/src/modules/listing.module.ts
  backend_new/src/modules/multiselect-question.module.ts
  backend_new/src/modules/prisma.module.ts
  backend_new/src/modules/reserved-community-type.module.ts
  backend_new/src/modules/unit-accessibility-priority-type.module.ts
  backend_new/src/modules/unit-rent-type.module.ts
  backend_new/src/modules/unit-type.module.ts
  backend_new/src/modules/user.module.ts
  backend_new/src/services/listing.service.ts
  backend_new/src/services/user.service.ts
  backend_new/src/utilities/build-filter.ts
  backend_new/src/utilities/pagination-helpers.ts
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/unit/services/user.service.spec.ts
  backend_new/test/unit/utilities/pagination-helpers.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3551 fix: add image fallback
  shared-helpers/package.json
  shared-helpers/src/utilities/photos.ts
  sites/partners/package.json
  sites/public/package.json
  sites/public/public/images/listing-fallback.png
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/lib/helpers.tsx
  yarn.lock
Labels: ready to merge

#3592 fix: only email language if user has set language
  backend/core/src/email/email.service.ts
Labels: ready to merge

#3583 feat: new requested changes field
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1691438164033-user-req-changes.ts
  backend/core/types/src/backend-swagger.ts
Labels: ready to merge

#3591 feat: prisma user write
  backend_new/.env.template
  backend_new/package.json
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/user-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/controllers/user.controller.ts
  backend_new/src/decorators/match-decorator.ts
  backend_new/src/dtos/users/confirmation-request.dto.ts
  backend_new/src/dtos/users/email-and-app-url.dto.ts
  backend_new/src/dtos/users/user-create-params.dto.ts
  backend_new/src/dtos/users/user-create.dto.ts
  backend_new/src/dtos/users/user-invite.dto.ts
  backend_new/src/dtos/users/user-role.dto.ts
  backend_new/src/dtos/users/user-update.dto.ts
  backend_new/src/dtos/users/user.dto.ts
  backend_new/src/services/user.service.ts
  backend_new/src/utilities/password-helpers.ts
  backend_new/src/utilities/password-regex.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/application.e2e-spec.ts
  backend_new/test/integration/asset.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/multiselect-question.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/unit/services/user.service.spec.ts
  backend_new/test/unit/utilities/password-helper.spec.ts
  backend_new/test/unit/utilities/password-regex.spec.ts
  backend_new/tsconfig.json
  backend_new/types/src/backend-swagger.ts
  backend_new/yarn.lock
Labels: ready to merge, prisma rewrite

#3576 3556/partners listings table sort by status
  backend/core/src/listings/db/listing-query-builder.ts
  shared-helpers/package.json
  sites/partners/package.json
  sites/partners/src/pages/index.tsx
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#3597 refactor: use new seeds tag component
  sites/partners/__tests__/components/shared/StatusBar.test.tsx
  sites/partners/package.json
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/flags/applicationsCols.tsx
  sites/partners/src/components/flags/flagSetCols.tsx
  sites/partners/src/components/listings/ListingStatusBar.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/components/shared/StatusBar.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/styles/overrides.scss
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#3598 feat: submit for approval flow
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
Labels: ready to merge

#3564 fix: cors origin deploy preview issues
  backend/core/.env.template
  backend/core/src/app.module.ts
Labels: ready to merge

#3609 fix: update label for monthly minimum income
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge

#3568 fix: add backend url validation for url fields
  backend/core/src/application-methods/entities/application-method.entity.ts
  backend/core/src/listings/entities/listing-event.entity.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/multiselect-question/types/multiselect-link.ts
  backend/core/src/shared/decorators/hasHttps.decorator.ts
  backend/core/test/listings/listings.e2e-spec.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/helpers.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
Labels: ready to merge

#3613 fix: change how user is retreived from req
  backend_new/package.json
  backend_new/src/controllers/user.controller.ts
  backend_new/yarn.lock
Labels: ready to merge, prisma rewrite

#3618 fix: add four and five bedrooms keys to sort array
  backend/core/src/shared/units-transformations.ts
Labels: ready to merge

#3622 fix: sort table with listings approval statuses
  backend/core/src/listings/db/listing-query-builder.ts
Labels: ready to merge

#3612 test: add listings approval cypress tests
  .circleci/config.yml
  sites/partners/cypress/e2e/default/01-sign-in-terms.spec.ts
  sites/partners/cypress/e2e/default/02-mfa.spec.ts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/04-application.spec.ts
  sites/partners/cypress/e2e/default/05-paperApplication.spec.ts
  sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts
  sites/partners/cypress/e2e/default/07-jurisdictional-admin-user-management.spec.ts
  sites/partners/cypress/e2e/default/08-preference-management.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/cypress/fixtures/jurisdictionalAdminUser.json
  sites/partners/cypress/fixtures/minimalListing.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/RequestChangesModal.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/pages/index.tsx
Labels: ready to merge
