Repository bloom-housing/bloom, pull requests merged in 2023-07, with the labels that each got.

#3526 fix: timezone adjustment
  backend/core/src/applications/applications.controller.ts
  backend/core/src/applications/dto/applications-csv-list-query-params.ts
  backend/core/src/applications/helpers.ts
  backend/core/src/applications/services/application-csv-exporter.service.ts
  backend/core/test/lib/format-local-date.spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/components/flags/applicationsCols.tsx
  sites/partners/src/lib/helpers.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/application/[id]/applicationsCols.tsx
Labels: ready to merge

#3483 feat: jurisdiction
  backend_new/src/app.module.ts
  backend_new/src/controllers/jurisdiction.controller.ts
  backend_new/src/dtos/jurisdictions/jurisdiction-create.dto.ts
  backend_new/src/dtos/jurisdictions/jurisdiction-update.dto.ts
  backend_new/src/dtos/jurisdictions/jurisdiction.dto.ts
  backend_new/src/dtos/listings/listing-get.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question.dto.ts
  backend_new/src/modules/jurisdiction.module.ts
  backend_new/src/services/jurisdiction.service.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/unit/services/jurisdiction.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: prisma rewrite

#3527 fix: remove updated_at field from listing details page
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingData.tsx
Labels: ready to merge

#3536 fix: add check in afs for null email (#625)
  backend/core/src/application-flagged-sets/application-flagged-sets-cronjob.service.ts
Labels: ready to merge

#3509 feat: uptake field value v2
  sites/partners/package.json
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdIncome.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsMultiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsTerms.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormAlternateContact.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdIncome.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrograms.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormTerms.tsx
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalDetails.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalEligibility.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailBuildingDetails.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailCommunityType.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingData.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailListingIntro.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailPreferences.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/helpers.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingIntro.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/_app.tsx
  sites/partners/styles/overrides.scss
  sites/public/.jest/setup-tests.js
  sites/public/package.json
  sites/public/src/components/applications/HouseholdMemberForm.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/_app.tsx
  sites/public/src/pages/applications/household/add-members.tsx
  yarn.lock
Labels: ready to merge

#3524 fix: add better seeded data
  backend_new/README.md
  backend_new/package.json
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/address-factory.ts
  backend_new/prisma/seed-helpers/ami-chart-factory.ts
  backend_new/prisma/seed-helpers/jurisdiction-factory.ts
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/multiselect-question-factory.ts
  backend_new/prisma/seed-helpers/reserved-community-type-factory.ts
  backend_new/prisma/seed-helpers/unit-accessibility-priority-type-factory.ts
  backend_new/prisma/seed-helpers/unit-factory.ts
  backend_new/prisma/seed-helpers/unit-rent-type-factory.ts
  backend_new/prisma/seed-helpers/unit-type-factory.ts
  backend_new/prisma/seed-helpers/user-factory.ts
  backend_new/prisma/seed-helpers/word-generator.ts
  backend_new/prisma/seed-staging.ts
  backend_new/prisma/seed.ts
  backend_new/src/services/translation.service.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/test/unit/services/unit-accessibility-priority-type.service.spec.ts
  backend_new/test/unit/services/unit-rent-type.service.spec.ts
  backend_new/test/unit/services/unit-type.service.spec.ts
  backend_new/yarn.lock
Labels: ready to merge, prisma rewrite

#3550 fix: adding more logging to user confirm()
  backend/core/src/auth/services/user.service.ts
Labels: ready to merge

#3549 fix: adds missing translation
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#3552 fix: add correct command to run on heroku
  backend_new/Procfile
  backend_new/package.json
  backend_new/tsconfig.json
Labels: ready to merge

#3555 fix: delete household member in application
  sites/public/src/pages/applications/household/member.tsx
Labels: ready to merge

#3484 feat: multiselect question endpoints
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/multiselect-question-factory.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/listing.controller.ts
  backend_new/src/controllers/multiselect-question.controller.ts
  backend_new/src/dtos/listings/listing-get.dto.ts
  backend_new/src/dtos/listings/listing-multiselect-question.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-option.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-create.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-filter-params.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-get.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-query-params.dto.ts
  backend_new/src/dtos/multiselect-questions/multiselect-question-update.dto.ts
  backend_new/src/enums/multiselect-questions/filter-key-enum.ts
  backend_new/src/modules/multiselect-question.module.ts
  backend_new/src/services/listing.service.ts
  backend_new/src/services/multiselect-question.service.ts
  backend_new/src/utilities/build-filter.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/multiselect-question.e2e-spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/test/unit/services/multiselect-question.service.spec.ts
  backend_new/test/unit/services/translation.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: prisma rewrite

#3558 fix: prevent public users from logging into partners
  backend/core/.env.template
  backend/core/src/auth/passport-strategies/local-mfa.strategy.ts
  docs/DeployServicesHeroku.md
Labels: ready to merge

#3566 fix: use correct statuses for deciding to purge
  backend/core/src/listings/cache-purge.service.ts
  backend/core/src/listings/listings.service.ts
Labels: ready to merge
