Repository bloom-housing/bloom, pull requests merged in 2023-06, with the labels that each got.

#3461 fix: upgrade all nest dependencies
  backend/core/package.json
  backend/core/src/auth/services/sms-mfa.service.ts
  yarn.lock
Labels: ready to merge

#3489 fix: update backend-new circleci job
  .circleci/config.yml
  .eslintrc.js
  backend/core/src/activity-log/interceptors/activity-log.interceptor.ts
  backend/core/src/applications/services/application-csv-exporter.service.ts
  backend/core/src/assets/services/upload.service.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-pending.ts
  backend/core/src/seeder/seeds/listings/listing-default-lottery-results.ts
  backend/core/src/seeder/seeds/listings/listing-default-missing-ami.ts
  backend/core/src/seeder/seeds/listings/listing-default-sanjose-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/shared/services/abstract-service.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/src/shared/url-helper.ts
  backend_new/package.json
  backend_new/src/decorators/enforce-lower-case.decorator.ts
  backend_new/src/dtos/shared/pagination.dto.ts
  backend_new/src/services/listing.service.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/jest-e2e.config.js
  backend_new/test/jest-e2e.json
  backend_new/test/jest.config.js
  backend_new/test/jest.json
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/yarn.lock
  package.json
  shared-helpers/src/auth/Timeout.tsx
  sites/partners/.jest/setup-tests.js
  sites/partners/__tests__/testUtils.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/flags/flagSetCols.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/partners/src/lib/helpers.ts
  sites/partners/src/lib/users/signInHelpers.ts
  sites/partners/src/pages/users/index.tsx
  sites/partners/tsconfig.json
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/tsconfig.json
  sites/public/tsconfig.test.json
  yarn.lock
Labels: 1 review needed

#3492 fix: add additional unit fields to base view
  backend/core/src/listings/views/config.ts
Labels: ready to merge

#3469 fix: cypress coverage
  sites/partners/cypress/e2e/03-listing.spec.ts
Labels: ready to merge

#3477 Prisma ami-charts
  backend_new/README.md
  backend_new/package.json
  backend_new/prisma/seed-helpers/ami-chart-factory.ts
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/ami-chart.controller.ts
  backend_new/src/dtos/ami-charts/ami-chart-create.dto.ts
  backend_new/src/dtos/ami-charts/ami-chart-query-params.dto.ts
  backend_new/src/dtos/ami-charts/ami-chart-update.dto.ts
  backend_new/src/dtos/ami-charts/ami-chart.dto.ts
  backend_new/src/dtos/shared/abstract.dto.ts
  backend_new/src/dtos/shared/id.dto.ts
  backend_new/src/dtos/shared/success.dto.ts
  backend_new/src/dtos/units/ami-chart-item-get.dto.ts
  backend_new/src/dtos/units/unit-get.dto.ts
  backend_new/src/modules/ami-chart.module.ts
  backend_new/src/modules/listing.module.ts
  backend_new/src/services/ami-chart.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/src/utilities/unit-utilities.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/unit/services/ami-chart.service.spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/test/unit/utilities/unit-utilities.spec.ts
  backend_new/types/src/backend-swagger.ts
  backend_new/yarn.lock
Labels: ready to merge, prisma rewrite

#3478 feat: reserved community type
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/reserved-community-type-factory.ts
  backend_new/prisma/seed.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/reserved-community-type.controller.ts
  backend_new/src/dtos/listings/listing-get.dto.ts
  backend_new/src/dtos/reserved-community-types/reserved-community-type-create.dto.ts
  backend_new/src/dtos/reserved-community-types/reserved-community-type-query-params.dto.ts
  backend_new/src/dtos/reserved-community-types/reserved-community-type-update.dto.ts
  backend_new/src/dtos/reserved-community-types/reserved-community-type.dto.ts
  backend_new/src/modules/reserved-community-type.module.ts
  backend_new/src/services/reserved-community-type.service.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/unit/services/reserved-community-type.service.spec.ts
  backend_new/types/src/backend-swagger.ts
  package.json
Labels: ready to merge, prisma rewrite

#3460 fix: validate url field in building section criteria
  shared-helpers/package.json
  sites/partners/package.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#3514 fix: get correct time period for submitted
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: ready to merge

#3512 fix: do a cache purge on listings cron job
  backend/core/src/listings/cache-purge.service.ts
  backend/core/src/listings/listings-cron.service.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
Labels: ready to merge

#3479 feat: Prisma unit type
  backend_new/prisma/migrations/20230622231511_init/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/unit-type-factory.ts
  backend_new/prisma/seed.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/unit-type.controller.ts
  backend_new/src/dtos/unit-types/unit-type-create.dto.ts
  backend_new/src/dtos/unit-types/unit-type-update.dto.ts
  backend_new/src/dtos/unit-types/unit-type.dto.ts
  backend_new/src/dtos/units/unit-get.dto.ts
  backend_new/src/dtos/units/unit-summarized.dto.ts
  backend_new/src/dtos/units/unit-summary-get.dto.ts
  backend_new/src/dtos/units/units-summery-get.dto.ts
  backend_new/src/modules/unit-type.module.ts
  backend_new/src/services/unit-type.service.ts
  backend_new/src/utilities/unit-utilities.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/unit/services/unit-type.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3480 feat: unit accessibility priority type
  backend_new/prisma/migrations/20230623180942_init/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/unit-accessibility-priority-type-factory.ts
  backend_new/prisma/seed.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/unit-accessibility-priority-type.controller.ts
  backend_new/src/dtos/unit-accessibility-priority-types/unit-accessibility-priority-type-create.dto.ts
  backend_new/src/dtos/unit-accessibility-priority-types/unit-accessibility-priority-type-update.dto.ts
  backend_new/src/dtos/unit-accessibility-priority-types/unit-accessibility-priority-type.dto.ts
  backend_new/src/dtos/units/unit-accessibility-priority-type-get.dto.ts
  backend_new/src/dtos/units/unit-get.dto.ts
  backend_new/src/dtos/units/unit-summarized.dto.ts
  backend_new/src/dtos/units/units-summery-get.dto.ts
  backend_new/src/modules/unit-accessibility-priority-type.module.ts
  backend_new/src/services/unit-accessibility-priority-type.service.ts
  backend_new/src/utilities/mapTo.ts
  backend_new/src/utilities/unit-utilities.ts
  backend_new/test/integration/app.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/unit/services/translation.service.spec.ts
  backend_new/test/unit/services/unit-accessibility-priority-type.service.spec.ts
  backend_new/types/src/backend-swagger.ts
  package.json
Labels: ready to merge, prisma rewrite

#3481 feat: unit rent type
  backend_new/prisma/migrations/20230626231609_init/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-helpers/unit-rent-type-factory.ts
  backend_new/prisma/seed.ts
  backend_new/src/app.module.ts
  backend_new/src/controllers/unit-rent-type.controller.ts
  backend_new/src/dtos/shared/pagination.dto.ts
  backend_new/src/dtos/unit-rent-types/unit-rent-type-create.dto.ts
  backend_new/src/dtos/unit-rent-types/unit-rent-type-update.dto.ts
  backend_new/src/dtos/unit-rent-types/unit-rent-type.dto.ts
  backend_new/src/dtos/units/unit-get.dto.ts
  backend_new/src/dtos/units/unit-rent-type-get.dto.ts
  backend_new/src/modules/unit-rent-type.module.ts
  backend_new/src/services/unit-rent-type.service.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/unit/services/unit-rent-type.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: prisma rewrite
