Repository bloom-housing/bloom, pull requests merged in 2023-09, with the labels that each got.

#3600 feat: listings approval emails
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1692122923259-listings-approval-emails.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/shared/views/changes-requested.hbs
  backend/core/src/shared/views/listing-approved.hbs
  backend/core/src/shared/views/request-approval.hbs
  backend/core/src/translations/services/translations.service.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/locales/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
Labels: ready to merge

#3606 feat: custom exception filter
  backend_new/.env.template
  backend_new/src/main.ts
  backend_new/src/utilities/custom-exception-filter.ts
Labels: ready to merge, prisma rewrite

#3632 fix: use primary tag variants in partners
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/application/[id]/review.tsx
Labels: ready to merge

#3636 fix: allow sms mfa to be toggled on and off
  sites/partners/.env.template
  sites/partners/next.config.js
  sites/partners/src/components/users/FormSignInMFAType.tsx
Labels: ready to merge

#3635 fix: amiPercentage being unset on unit edit
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge

#3640 chore: upgrade ui-c to 12.0.21
  shared-helpers/package.json
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#3617 feat: prisma auth
  backend_new/.env.template
  backend_new/README.md
  backend_new/package.json
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/user-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/controllers/auth.controller.ts
  backend_new/src/dtos/auth/confirm.dto.ts
  backend_new/src/dtos/auth/login.dto.ts
  backend_new/src/dtos/auth/update-password.dto.ts
  backend_new/src/dtos/mfa/request-mfa-code-response.dto.ts
  backend_new/src/dtos/mfa/request-mfa-code.dto.ts
  backend_new/src/enums/mfa/mfa-type-enum.ts
  backend_new/src/guards/jwt.guard.ts
  backend_new/src/guards/mfa.guard.ts
  backend_new/src/guards/optional.guard.ts
  backend_new/src/main.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/modules/auth.module.ts
  backend_new/src/modules/sms-module.ts
  backend_new/src/passports/jwt.strategy.ts
  backend_new/src/passports/mfa.strategy.ts
  backend_new/src/services/auth.service.ts
  backend_new/src/services/sms.service.ts
  backend_new/src/services/user.service.ts
  backend_new/src/utilities/password-helpers.ts
  backend_new/test/integration/auth.e2e-spec.ts
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/jest-with-coverage.config.js
  backend_new/test/unit/passports/jwt.strategy.spec.ts
  backend_new/test/unit/passports/mfa.strategy.spec.ts
  backend_new/test/unit/services/auth.service.spec.ts
  backend_new/test/unit/services/user.service.spec.ts
  backend_new/types/src/backend-swagger.ts
  backend_new/yarn.lock
Labels: ready to merge, prisma rewrite

#3607 fix: add email-service
  backend_new/.env.template
  backend_new/nest-cli.json
  backend_new/package.json
  backend_new/prisma/seed-dev.ts
  backend_new/prisma/seed-helpers/translation-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/modules/email.module.ts
  backend_new/src/modules/user.module.ts
  backend_new/src/services/email.service.ts
  backend_new/src/services/sendgrid.service.ts
  backend_new/src/services/translation.service.ts
  backend_new/src/services/user.service.ts
  backend_new/src/views/change-email.hbs
  backend_new/src/views/confirmation.hbs
  backend_new/src/views/forgot-password.hbs
  backend_new/src/views/invite.hbs
  backend_new/src/views/layouts/default.hbs
  backend_new/src/views/mfa-code.hbs
  backend_new/src/views/partials/feedback.hbs
  backend_new/src/views/partials/footer.hbs
  backend_new/src/views/partials/head.hbs
  backend_new/src/views/partials/header.hbs
  backend_new/src/views/partials/leasing-agent.hbs
  backend_new/src/views/partials/simple-footer.hbs
  backend_new/src/views/partials/user-name.hbs
  backend_new/src/views/portal-account-update.hbs
  backend_new/src/views/register-email.hbs
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/unit/services/auth.service.spec.ts
  backend_new/test/unit/services/email.service.spec.ts
  backend_new/test/unit/services/translation.service.spec.ts
  backend_new/test/unit/services/user.service.spec.ts
  backend_new/yarn.lock
Labels: prisma rewrite

#3642 feat: open modal when selecting paper app download language
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/__tests__/components/listing/GetApplication.test.tsx
  sites/public/src/components/listing/GetApplication.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge

#3625 feat: prisma application Create endpoints
  backend_new/prisma/seed-helpers/application-factory.ts
  backend_new/src/controllers/application.controller.ts
  backend_new/src/dtos/addresses/address.dto.ts
  backend_new/src/dtos/applications/accessibility-update.dto.ts
  backend_new/src/dtos/applications/accessibility.dto.ts
  backend_new/src/dtos/applications/alternate-contact-update.dto.ts
  backend_new/src/dtos/applications/alternate-contact.dto.ts
  backend_new/src/dtos/applications/applicant-update.dto.ts
  backend_new/src/dtos/applications/applicant.dto.ts
  backend_new/src/dtos/applications/application-create.dto.ts
  backend_new/src/dtos/applications/application-multiselect-question-option.dto.ts
  backend_new/src/dtos/applications/application-multiselect-question.dto.ts
  backend_new/src/dtos/applications/application-update.dto.ts
  backend_new/src/dtos/applications/application.dto.ts
  backend_new/src/dtos/applications/demographic-update.dto.ts
  backend_new/src/dtos/applications/demographic.dto.ts
  backend_new/src/dtos/applications/household-member-update.dto.ts
  backend_new/src/dtos/applications/household-member.dto.ts
  backend_new/src/enums/applications/view-enum.ts
  backend_new/src/services/application.service.ts
  backend_new/test/integration/application.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/unit/services/application.service.spec.ts
  backend_new/types/src/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3651 fix: remove email from export error
  sites/partners/__tests__/pages/listings/index.test.tsx
  sites/partners/__tests__/pages/users/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/users/index.tsx
Labels: ready to merge

#3644 fix: jurisdiction permission array approach
  backend/core/src/jurisdictions/entities/jurisdiction.entity.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1694130645798-listings-approval-permissioning.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeder.module.ts
  backend/core/src/seeder/seeds/jurisdictions.ts
  backend/core/src/seeder/seeds/listings/listing-default-draft.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
Labels: ready to merge

#3655 fix: remove electron
  sites/partners/package.json
  yarn.lock
Labels: ready to merge
