Repository bloom-housing/bloom, pull requests merged in 2023-11, with the labels that each got.

#3701 fix: grid fix for listing intro
  sites/partners/src/components/listings/PaperListingForm/sections/ListingIntro.tsx
Labels: 1 review needed

#3697 feat: csv export for users
  backend_new/prisma/seed-helpers/translation-factory.ts
  backend_new/src/controllers/user.controller.ts
  backend_new/src/services/email.service.ts
  backend_new/src/services/user.service.ts
  backend_new/src/utilities/csv-builder.ts
  backend_new/src/views/csv-export.hbs
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/unit/services/email.service.spec.ts
  backend_new/test/unit/services/user.service.spec.ts
  backend_new/test/unit/utilities/csv-builder.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3692 feat: geocoding geographic radius set up
  backend/core/src/multiselect-question/types/multiselect-option.ts
  backend/core/src/multiselect-question/types/validation-method-enum.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/__tests__/testHelpers.ts
  sites/partners/cypress/e2e/default/08-preference-management.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/settings/PreferenceDrawer.tsx
Labels: ready to merge

#3703 feat: geocoding - showing name and relationship on preference screens
  shared-helpers/index.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/utilities/constants.ts
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge

#3720 fix: re-enable CSS purging to minimize Tailwind bundles
  sites/partners/tailwind.config.js
  sites/public/tailwind.config.js
Labels: ready to merge

#3674 feat: prisma application flagged sets
  backend_new/.env.template
  backend_new/package.json
  backend_new/prisma/migrations/20231030230627_init/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/application-factory.ts
  backend_new/src/controllers/application-flagged-set.controller.ts
  backend_new/src/dtos/application-flagged-sets/afs-meta.dto.ts
  backend_new/src/dtos/application-flagged-sets/afs-pagination-meta.dto.ts
  backend_new/src/dtos/application-flagged-sets/afs-query-params.dto.ts
  backend_new/src/dtos/application-flagged-sets/afs-resolve.dto.ts
  backend_new/src/dtos/application-flagged-sets/application-flagged-set.dto.ts
  backend_new/src/dtos/application-flagged-sets/paginated-afs.dto.ts
  backend_new/src/dtos/shared/pagination.dto.ts
  backend_new/src/enums/application-flagged-sets/view.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/modules/application-flagged-set.module.ts
  backend_new/src/modules/listing.module.ts
  backend_new/src/services/application-flagged-set.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/test/integration/ami-chart.e2e-spec.ts
  backend_new/test/integration/application-flagged-set.e2e-spec.ts
  backend_new/test/integration/application.e2e-spec.ts
  backend_new/test/integration/asset.e2e-spec.ts
  backend_new/test/integration/auth.e2e-spec.ts
  backend_new/test/integration/jurisdiction.e2e-spec.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/multiselect-question.e2e-spec.ts
  backend_new/test/integration/reserved-community-type.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/integration/unit-rent-type.e2e-spec.ts
  backend_new/test/integration/unit-type.e2e-spec.ts
  backend_new/test/integration/user.e2e-spec.ts
  backend_new/test/unit/services/application-flagged-set.service.spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/yarn.lock
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3723 fix: remove password from logs
  shared-helpers/index.ts
  shared-helpers/src/utilities/maskData.ts
  sites/partners/src/pages/api/adapter/[...backendUrl].ts
  sites/public/src/pages/api/adapter/[...backendUrl].ts
Labels: ready to merge

#3731 fix: only send listing approval email once
  backend/core/src/listings/listings.service.ts
Labels: ready to merge
