Repository bloom-housing/bloom, pull requests merged in 2023-12, with the labels that each got.

#3715 feat: add address verification for preferences step
  shared-helpers/src/locales/general.json
  shared-helpers/src/views/address/FormAddressAlternate.tsx
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
  sites/public/src/components/applications/ValidateAddress.tsx
Labels: ready to merge

#3694 fix: update dependencies for backend
  backend/core/package.json
  yarn.lock
Labels: ready to merge

#3662 feat: core changes for application style alignment
  shared-helpers/package.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/multiselectQuestions.tsx
  shared-helpers/src/views/sign-in/ResendConfirmationModal.tsx
  sites/partners/package.json
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/users/index.tsx
  sites/public/cypress/e2e/pages/application/household/add-members.spec.ts
  sites/public/cypress/e2e/pages/application/household/member.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/cypress/support/index.d.ts
  sites/public/package.json
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
  sites/public/src/components/applications/ValidateAddress.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/layouts/application-form.module.scss
  sites/public/src/layouts/application-form.tsx
  sites/public/src/layouts/forms.tsx
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/src/pages/applications/contact/alternate-contact-name.tsx
  sites/public/src/pages/applications/contact/alternate-contact-type.tsx
  sites/public/src/pages/applications/contact/name.tsx
  sites/public/src/pages/applications/financial/income.tsx
  sites/public/src/pages/applications/financial/vouchers.tsx
  sites/public/src/pages/applications/household/ada.tsx
  sites/public/src/pages/applications/household/add-members.tsx
  sites/public/src/pages/applications/household/changes.tsx
  sites/public/src/pages/applications/household/live-alone.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/applications/household/members-info.tsx
  sites/public/src/pages/applications/household/preferred-units.tsx
  sites/public/src/pages/applications/household/student.tsx
  sites/public/src/pages/applications/preferences/all.tsx
  sites/public/src/pages/applications/preferences/general.tsx
  sites/public/src/pages/applications/review/confirmation.tsx
  sites/public/src/pages/applications/review/demographics.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/review/terms.tsx
  sites/public/src/pages/applications/start/autofill.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/applications/start/what-to-expect.tsx
  sites/public/src/pages/applications/view.tsx
  sites/public/src/pages/index.tsx
  sites/public/styles/overrides.scss
  yarn.lock
Labels: 1 review needed

#3746 test: fix cypress lat long error
  sites/partners/cypress/e2e/default/03-listing.spec.ts
Labels: ready to merge

#3745 fix: padding issue on address verify
  sites/public/src/pages/applications/contact/address.tsx
Labels: ready to merge

#3736 fix: verify application errors
  sites/public/src/lib/applications/AppSubmissionContext.ts
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/pages/_app.tsx
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/src/pages/applications/contact/alternate-contact-name.tsx
  sites/public/src/pages/applications/contact/alternate-contact-type.tsx
  sites/public/src/pages/applications/contact/name.tsx
  sites/public/src/pages/applications/financial/income.tsx
  sites/public/src/pages/applications/financial/vouchers.tsx
  sites/public/src/pages/applications/household/ada.tsx
  sites/public/src/pages/applications/household/add-members.tsx
  sites/public/src/pages/applications/household/changes.tsx
  sites/public/src/pages/applications/household/live-alone.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/applications/household/preferred-units.tsx
  sites/public/src/pages/applications/household/student.tsx
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#3763 fix: application multiselect questions
  backend_new/src/dtos/applications/application-multiselect-question.dto.ts
  backend_new/test/integration/application.e2e-spec.ts
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/multiselectQuestions.tsx
Labels: ready to merge

#3773 feat: MA-3752 add SHOW_MANDATED_ACCOUNTS flag
  sites/public/.env.template
  sites/public/next.config.js
Labels: ready to merge

#3739 feat: listing process
  backend_new/.env.template
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/src/controllers/application.controller.ts
  backend_new/src/controllers/listing.controller.ts
  backend_new/src/controllers/user.controller.ts
  backend_new/src/guards/admin-or-jurisdiction-admin.guard.ts
  backend_new/src/guards/permission.guard.ts
  backend_new/src/guards/user-profile-permission-guard.ts
  backend_new/src/interceptors/activity-log.interceptor.ts
  backend_new/src/modules/listing.module.ts
  backend_new/src/services/application-flagged-set.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/src/utilities/cron-job-starter.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
Labels: ready to merge, prisma rewrite

#3716 feat: add address holder fields to paper application
  backend/core/types/index.ts
  backend/core/types/src/geocoding-keys.ts
  shared-helpers/src/views/address/FormAddressAlternate.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsMultiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/partners/styles/overrides.scss
Labels: ready to merge

#3765 feat: add geocoding preference label
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/styles/overrides.scss
Labels: ready to merge

#3778 fix: add geocoding fields to csv export
  backend/core/src/applications/helpers.ts
  backend/core/src/applications/services/application-csv-exporter.service.ts
Labels: ready to merge
