Repository bloom-housing/bloom, pull requests merged in 2024-05, with the labels that each got.

#3956 feat: add Hero icons and additional uptake of Seeds Icon
  shared-helpers/index.ts
  shared-helpers/package.json
  shared-helpers/src/views/CustomIconMap.tsx
  shared-helpers/src/views/CustomIcons.tsx
  shared-helpers/src/views/accounts/CustomIconMap.tsx
  shared-helpers/src/views/components/BloomCard.tsx
  shared-helpers/src/views/forgot-password/FormForgotPassword.tsx
  sites/partners/__tests__/components/shared/StatusBar.test.tsx
  sites/partners/package.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/settings/ManageIconSection.tsx
  sites/partners/src/components/users/FormSignInAddPhone.tsx
  sites/partners/src/components/users/FormSignInMFACode.tsx
  sites/partners/src/components/users/FormSignInMFAType.tsx
  sites/partners/src/components/users/FormTerms.tsx
  sites/partners/src/components/users/FormUserConfirm.tsx
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/reset-password.tsx
  sites/partners/src/pages/users/index.tsx
  sites/public/package.json
  sites/public/src/components/account/SignUpBenefits.tsx
  sites/public/src/components/applications/FormBackLink.tsx
  sites/public/src/components/applications/HouseholdMemberForm.tsx
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/layouts/application-form.tsx
  sites/public/src/pages/applications/contact/name.tsx
  sites/public/src/pages/applications/preferences/general.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/index.tsx
  yarn.lock
Labels: ready to merge

#4070 test: fix cypress longitude error
  sites/partners/cypress/e2e/default/03-listing.spec.ts
Labels: ready to merge

#3993 feat: uptake Seeds Tabs
  sites/partners/src/components/listings/PaperListingForm/index.tsx
Labels: ready to merge

#4096 fix: restores getStaticProps functionality
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/index.tsx
Labels: high priority, ready to merge

#4092 feat: script runner part 1
  api/prisma/migrations/11_add_script_runs/migration.sql
  api/prisma/schema.prisma
  api/src/controllers/script-runner.controller.ts
  api/src/modules/app.module.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/app.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#4097 feat: filter flagged duplicate sets
  api/src/dtos/application-flagged-sets/afs-query-params.dto.ts
  api/src/services/application-flagged-set.service.ts
  api/test/unit/services/application-flagged-set.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/lib/helpers.test.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsApplicationData.tsx
  sites/partners/src/lib/helpers.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/application/[id]/applicationsCols.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/applications/resolved/index.tsx
Labels: ready to merge

#4098 feat: new application index on user_id
  api/prisma/migrations/20240520173759_application_user_id_index/migration.sql
  api/prisma/schema.prisma
Labels: ready to merge

#4107 fix: update password requirements
  api/prisma/seed-dev.ts
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/utilities/password-regex.ts
  api/test/integration/ami-chart.e2e-spec.ts
  api/test/integration/api-key-guard.e2e-spec.ts
  api/test/integration/application-flagged-set.e2e-spec.ts
  api/test/integration/application.e2e-spec.ts
  api/test/integration/asset.e2e-spec.ts
  api/test/integration/auth.e2e-spec.ts
  api/test/integration/jurisdiction.e2e-spec.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/multiselect-question.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/integration/reserved-community-type.e2e-spec.ts
  api/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  api/test/integration/unit-rent-type.e2e-spec.ts
  api/test/integration/unit-type.e2e-spec.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/passports/mfa.strategy.spec.ts
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  api/test/unit/utilities/password-helper.spec.ts
  api/test/unit/utilities/password-regex.spec.ts
  shared-helpers/index.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/utilities/passwordRegex.ts
  sites/partners/cypress/e2e/default/02-mfa.spec.ts
  sites/partners/cypress/fixtures/jurisdictionalAdmin.json
  sites/partners/cypress/fixtures/jurisdictionalAdminUser.json
  sites/partners/cypress/fixtures/termsUnacceptedUser.json
  sites/partners/src/components/users/FormUserConfirm.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/reset-password.tsx
  sites/public/src/pages/sign-in.tsx
Labels: ready to merge

#4038 fix: various uptake and visual enhancements to address design QA
  sites/public/src/components/applications/HouseholdMemberForm.tsx
  sites/public/src/components/applications/HouseholdSizeField.tsx
  sites/public/src/components/shared/FormSummaryDetails.module.scss
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/layouts/application-form.module.scss
  sites/public/src/pages/applications/household/add-members.tsx
Labels: 1 review needed

#4108 fix: saving household member
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-staging.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/public/cypress.config.ts
  sites/public/cypress/e2e/pages/submit-application.spec.ts
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/cypress/support/index.d.ts
  sites/public/src/components/applications/ValidateAddress.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/applications/household/preferred-units.tsx
Labels: ready to merge

#4104 feat: script runner data transfer part 1
  api/.env.template
  api/src/controllers/auth.controller.ts
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#4110 feat: Fremont Familes Email Template for Script Runner
  api/prisma/migrations/12_add_script_runner_translations/migration.sql
  api/src/services/email.service.ts
  api/src/views/script-runner.hbs
Labels: ready to merge

#4111 feat: bulk app resend script runner
  api/prisma/seed-helpers/translation-factory.ts
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/bulk-application-resend.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: high priority, ready to merge

#4102 fix: Demographics Race Field Render Issue
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormDemographics.tsx
  sites/public/src/pages/applications/review/demographics.tsx
Labels: ready to merge
