Repository bloom-housing/bloom, pull requests merged in 2024-08, with the labels that each got.

#4169 fix: prevent listings without AMI charts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge

#4234 fix: switch sign in ctas to sentence case
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/helpers.tsx
Labels: ready to merge

#4239 fix: remove errant lottery copy
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: bug, ready to merge

#4245 feat: new opt in language for partners
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
Labels: ready to merge

#4244 feat: rerun modal
  api/src/services/lottery.service.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/lottery.service.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#4241 fix: return proper exception for email in use
  api/src/services/user.service.ts
  sites/partners/page_content/locale_overrides/general.json
Labels: ready to merge

#4237 feat: application side nav
  shared-helpers/package.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/partners/package.json
  sites/public/package.json
  sites/public/src/components/account/ApplicationsView.module.scss
  sites/public/src/components/account/ApplicationsView.tsx
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/account/StatusItemWrapper.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/applications/closed/index.tsx
  sites/public/src/pages/account/applications/index.tsx
  sites/public/src/pages/account/applications/lottery/index.tsx
  sites/public/src/pages/account/applications/open/index.tsx
  yarn.lock
Labels: 1 review needed

#4233 feat: adding preference sheets to lottery export
  api/prisma/seed-helpers/address-factory.ts
  api/prisma/seed-helpers/application-preference-factory.ts
  api/prisma/seed-staging.ts
  api/src/services/lottery.service.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#4250 feat: require lottery date time fields
  api/src/dtos/listings/listing-update.dto.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/utilities/lottery-date-validator.ts
  api/test/unit/utilities/lottery-date-validator.spec.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
Labels: ready to merge

#4235 feat: lotteries history log
  api/prisma/seed-helpers/listing-factory.ts
  api/src/controllers/listing.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/decorators/activity-log-metadata.decorator.ts
  api/src/dtos/applications/application-csv-query-params.dto.ts
  api/src/dtos/listings/listing-lottery-status.dto.ts
  api/src/dtos/lottery/lottery-activity-log-item.dto.ts
  api/src/interceptors/activity-log.interceptor.ts
  api/src/interceptors/export-log.interceptor.ts
  api/src/modules/lottery.module.ts
  api/src/services/application-csv-export.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  backend/core/src/applications/services/applications.service.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#4249 fix: add lottery re-run functionality
  api/src/services/lottery.service.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/lottery.service.spec.ts
Labels: ready to merge

#4254 fix: lottery history log filtering
  api/src/controllers/lottery.controller.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/listings/lottery.test.tsx
  sites/partners/src/lib/hooks.ts
Labels: ready to merge

#4262 fix: remove db dependency from unit tests
  api/package.json
  api/src/services/script-runner.service.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  api/test/unit/services/script-runner.service.spec.ts
  api/test/unit/services/translation.service.spec.ts
  api/yarn.lock
Labels: ready to merge

#4261 fix: update zip length requirement and error messaging
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/views/address/FormAddressAlternate.tsx
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/applications/contact/address.tsx
  sites/public/src/pages/applications/contact/alternate-contact-contact.tsx
  sites/public/src/pages/applications/contact/alternate-contact-name.tsx
  sites/public/src/pages/applications/contact/alternate-contact-type.tsx
  sites/public/src/pages/applications/contact/name.tsx
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/create-account.tsx
Labels: ready to merge

#4255 feat: public account lottery view
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/scripts/get-machine-translations.ts
  sites/public/src/components/account/ApplicationCards.module.scss
  sites/public/src/components/account/ApplicationCards.tsx
  sites/public/src/components/account/StatusItem.module.scss
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/account/StatusItemWrapper.tsx
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/pages/account/application/[id]/index.tsx
  sites/public/src/pages/account/application/[id]/lottery-results.tsx
  sites/public/styles/lottery-results.module.scss
Labels: ready to merge

#4267 feat: opt out existing lotteries
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#4265 feat: lottery toasts
  shared-helpers/src/utilities/MessageContext.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge

#4252 feat: feature flag and new endpoint
  api/src/controllers/application.controller.ts
  api/src/dtos/applications/public-apps-count.dto.ts
  api/src/dtos/applications/public-apps-filtered.dto.ts
  api/src/dtos/applications/public-apps-view-params.dto.ts
  api/src/dtos/applications/public-apps-view-response.dto.ts
  api/src/enums/applications/filter-enum.ts
  api/src/services/application.service.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/components/account/ApplicationsView.module.scss
  sites/public/src/components/account/ApplicationsView.tsx
  sites/public/src/components/account/StatusItemWrapper.tsx
  sites/public/src/pages/account/applications/closed/index.tsx
  sites/public/src/pages/account/applications/index.tsx
  sites/public/src/pages/account/applications/lottery/index.tsx
  sites/public/src/pages/account/applications/open/index.tsx
Labels: ready to merge

#4264 fix: allow a due date for open waitlist
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/lib/listings/formTypes.ts
Labels: ready to merge

#4278 fix: build resolution
  sites/public/src/components/account/StatusItemWrapper.tsx
Labels: ready to merge

#4281 fix: clean up dto
  api/src/controllers/application.controller.ts
  api/src/dtos/applications/public-apps-filtered.dto.ts
  api/src/dtos/applications/public-apps-view-response.dto.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#4274 fix: include comparison in next config
  sites/partners/next.config.js
Labels: ready to merge

#4256 feat: save and continue
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/CloseListingDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/ListingApprovalDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/LiveConfirmationDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/PublishListingDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/RequestChangesDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/SaveBeforeExitDialog.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/pages/listings/[id]/edit.tsx
Labels: ready to merge
