Repository bloom-housing/bloom, pull requests merged in 2024-01, with the labels that each got.

#3793 fix: update seeds button
  shared-helpers/src/views/forgot-password/FormForgotPassword.tsx
Labels: ready to merge

#3784 fix: add translations for geocoding
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
Labels: ready to merge

#3796 fix: update labeling
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
Labels: ready to merge

#3767 fix: add geocoding radius functionality
  backend_new/package.json
  backend_new/prisma/seed-helpers/multiselect-question-factory.ts
  backend_new/src/modules/application.module.ts
  backend_new/src/services/application.service.ts
  backend_new/src/services/geocoding.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/test/integration/application.e2e-spec.ts
  backend_new/test/unit/services/application.service.spec.ts
  backend_new/test/unit/services/geocoding.service.spec.ts
  backend_new/yarn.lock
  sites/partners/cypress/e2e/default/05-paperApplication.spec.ts
Labels: prisma rewrite

#3802 fix: update listing export
  backend/core/src/listings/listings-csv-exporter.service.ts
  backend/core/src/listings/views/config.ts
Labels: ready to merge

#3797 fix: on listing create, add to cache
  backend/core/src/listings/listings.service.ts
Labels: ready to merge

#3798 fix: on listing create, add to cache
  backend_new/src/services/listing.service.ts
Labels: prisma rewrite

#3777 fix: partner listings applications
  backend_new/prisma/migrations/20231030230627_init/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/application-factory.ts
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/dtos/applications/application.dto.ts
  backend_new/src/services/application-flagged-set.service.ts
  backend_new/src/services/application.service.ts
  backend_new/src/utilities/build-order-by.ts
  backend_new/src/utilities/cron-job-starter.ts
  backend_new/test/integration/application-flagged-set.e2e-spec.ts
  backend_new/test/unit/services/application-flagged-set.service.spec.ts
  backend_new/test/unit/services/application.service.spec.ts
  shared-helpers/src/auth/AuthContext.ts
  sites/partners/cypress/e2e/default/02-mfa.spec.ts
  sites/partners/cypress/e2e/default/04-application.spec.ts
  sites/partners/next.config.js
  sites/partners/package.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsAddressColumns.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsAlternateContact.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/public/next.config.js
  sites/public/package.json
  sites/public/src/pages/applications/contact/address.tsx
Labels: ready to merge, prisma rewrite

#3775 feat: creating new migration flow
  backend_new/.env.template
  backend_new/package.json
  backend_new/prisma/migrations/0_init/migration.sql
  backend_new/prisma/migrations/1_change_to_prisma/migration.sql
  backend_new/prisma/migrations/20231030230627_init/migration.sql
  backend_new/prisma/migrations/2_hba_to_prisma/migration.sql
  backend_new/prisma/schema.prisma
  backend_new/prisma/seed-helpers/unit-accessibility-priority-type-factory.ts
  backend_new/src/dtos/unit-accessibility-priority-types/unit-accessibility-priority-type.dto.ts
  backend_new/src/main.ts
  backend_new/src/services/listing.service.ts
  backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  backend_new/test/integration/unit-accessibility-priority-type.e2e-spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/test/unit/services/unit-accessibility-priority-type.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/cypress/fixtures/listing.json
Labels: prisma rewrite

#3809 fix: provides additional fields info text overflows
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
Labels: ready to merge

#3813 fix: add links to preference description
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
Labels: ready to merge

#3812 fix: pagination and deletion fix
  backend_new/src/services/listing.service.ts
  backend_new/src/services/user.service.ts
  backend_new/test/integration/listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  backend_new/test/unit/services/listing.service.spec.ts
  backend_new/test/unit/services/user.service.spec.ts
Labels: ready to merge, prisma rewrite

#3819 fix: perm and login fixes
  backend_new/src/passports/mfa.strategy.ts
  backend_new/src/permission-configs/permission_policy.csv
  backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  backend_new/test/unit/passports/mfa.strategy.spec.ts
Labels: 1 review needed, prisma rewrite

#3825 fix: add map layer geocoding checks
  backend/core/package.json
  backend/core/src/applications/applications.module.ts
  backend/core/src/applications/services/geocoding.service.spec.ts
  backend/core/src/applications/services/geocoding.service.ts
  backend/core/src/map-layers/entities/map-layer.entity.ts
  backend/core/src/migration/1705637577495-add-feature-collection.ts
  backend/core/src/seeder/seeds/map-layers.ts
  yarn.lock
Labels: ready to merge

#3829 fix: add default value for map layer
  backend/core/src/migration/1705637577495-add-feature-collection.ts
  sites/partners/__tests__/pages/settings/index.test.tsx
Labels: ready to merge

#3816 feat: 3761/direct to sign in
  sites/public/__tests__/components/listing/GetApplication.test.tsx
  sites/public/src/components/listing/GetApplication.tsx
  sites/public/src/components/listing/ListingView.tsx
Labels: ready to merge

#3791 feat: 422/updated account theming
  shared-helpers/src/locales/general.json
  sites/public/cypress/e2e/pages/my-applications.spec.ts
  sites/public/src/components/account/AccountCard.module.scss
  sites/public/src/components/account/AccountCard.tsx
  sites/public/src/components/account/StatusItem.module.scss
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/shared/CustomIconMap.tsx
  sites/public/src/components/shared/CustomIcons.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/pages/account/edit.tsx
Labels: ready to merge

#3841 fix: add divider width
  sites/public/src/components/account/AccountCard.module.scss
Labels: 1 review needed

#3811 feat: 3753/ma sign in copy
  .circleci/config.yml
  shared-helpers/src/locales/general.json
  sites/public/src/components/account/SignUpBenefits.tsx
  sites/public/src/layouts/forms.tsx
  sites/public/src/pages/sign-in.tsx
Labels: ready to merge
