Repository bloom-housing/bloom, pull requests merged in 2024-02, with the labels that each got.

#3842 fix: spacing on preference pages
  shared-helpers/src/views/multiselectQuestions.tsx
Labels: ready to merge

#3854 fix: upgrade netlify plugin
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#3858 Prisma change over feature branch heap
  .circleci/config.yml
  backend_new/package.json
  backend_new/src/services/permission.service.ts
  backend_new/test/jest-with-coverage.config.js
Labels: ready to merge, prisma rewrite

#3806 Listings CSV
  backend_new/package.json
  backend_new/prisma/seed-staging.ts
  backend_new/src/controllers/application.controller.ts
  backend_new/src/controllers/listing.controller.ts
  backend_new/src/dtos/listings/listing-csv-query-params.dto.ts
  backend_new/src/enums/listings/review-order-enum.ts
  backend_new/src/enums/listings/view-enum.ts
  backend_new/src/modules/listing.module.ts
  backend_new/src/services/application-csv-export.service.ts
  backend_new/src/services/listing-csv-export.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/src/types/CsvExportInterface.ts
  backend_new/src/utilities/format-local-date.ts
  backend_new/src/utilities/is-empty.ts
  backend_new/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  backend_new/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  backend_new/test/jest-with-coverage.config.js
  backend_new/test/unit/services/application-csv-export.service.spec.ts
  backend_new/yarn.lock
  package.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/api/adapter/[...backendUrl].ts
  sites/partners/src/pages/index.tsx
Labels: 2 reviews needed, prisma rewrite

#3855 fix: allow jurisdictional admin for map layers
  backend/core/src/map-layers/map-layers.controller.ts
Labels: ready to merge

#3843 fix: move preference url below preference description
  sites/public/src/components/applications/ApplicationMultiselectQuestionStep.tsx
Labels: ready to merge

#3840 fix: bug bash fixes
  backend_new/prisma/migrations/00_init/migration.sql
  backend_new/prisma/migrations/01_change_to_prisma/migration.sql
  backend_new/prisma/migrations/02_hba_to_prisma/migration.sql
  backend_new/prisma/seed-helpers/listing-factory.ts
  backend_new/prisma/seed-staging.ts
  backend_new/src/services/application-csv-export.service.ts
  backend_new/src/services/listing-csv-export.service.ts
  backend_new/src/services/listing.service.ts
  backend_new/test/unit/services/listing.service.spec.ts
  sites/partners/src/pages/api/adapter/[...backendUrl].ts
Labels: ready to merge, prisma rewrite

#3865 fix: foreign language in export
  shared-helpers/__tests__/views/multiselectQuestions.test.ts
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge

#3866 feat: moving temp file clean up cron
  backend_new/.env.template
  backend_new/src/controllers/app.controller.ts
  backend_new/src/controllers/listing.controller.ts
  backend_new/src/modules/app.module.ts
  backend_new/src/services/app.service.ts
  backend_new/src/services/listing-csv-export.service.ts
  backend_new/test/unit/services/app.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: 1 review needed, prisma rewrite

#3839 feat: 3760/redirect to application
  backend/core/src/auth/services/user.service.ts
  backend/core/src/email/email.service.ts
  backend/core/src/shared/utils/get-public-email-url.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/utilities/getListingRedirectUrl.ts
  shared-helpers/src/views/sign-in/FormSignIn.tsx
  sites/public/src/components/account/ConfirmationModal.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/forgot-password.tsx
  sites/public/src/pages/reset-password.tsx
Labels: ready to merge

#3878 fix: fixing the cache purge
  api/src/services/listing.service.ts
Labels: ready to merge

#3863 feat: maintenance flag
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/layouts/application.module.scss
  sites/public/src/layouts/application.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/applications/start/what-to-expect.tsx
Labels: ready to merge

#3820 feat: add MA sign in styling
  shared-helpers/src/views/accounts/AccountCard.module.scss
  shared-helpers/src/views/accounts/AccountCard.tsx
  shared-helpers/src/views/accounts/CustomIconMap.tsx
  shared-helpers/src/views/accounts/CustomIcons.tsx
  shared-helpers/src/views/sign-in/FormSignIn.tsx
  shared-helpers/src/views/sign-in/FormSignInErrorBox.tsx
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/styles/sign-in.module.scss
Labels: 1 review needed

#3850 feat: add MA application check for signed-in user
  shared-helpers/src/auth/UseRequireLoggedInUser.ts
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: 1 review needed

#3853 422/account design updates
  shared-helpers/src/views/accounts/AccountCard.module.scss
  shared-helpers/src/views/accounts/AccountCard.tsx
  sites/public/src/components/account/StatusItem.module.scss
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/applications/SubmittedApplicationView.modules.scss
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/account/StatusItemWrapper.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/application/[id].tsx
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/applications/view.tsx
  sites/public/src/pages/create-account.tsx
Labels: ready to merge

#3879 chore(deps): upgrade nestjs
  api/package.json
  api/yarn.lock
Labels: dependencies, ready to merge

#3890 feat: external listing endpoint
  api/src/controllers/listing.controller.ts
  api/src/services/listing.service.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, prisma rewrite

#3882 fix: move user export to direct download
  api/prisma/seed-staging.ts
  api/src/controllers/user.controller.ts
  api/src/modules/user.module.ts
  api/src/services/listing-csv-export.service.ts
  api/src/services/user-csv-export.service.ts
  api/src/services/user.service.ts
  api/src/types/CsvExportInterface.ts
  api/src/utilities/build-user-where.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/user-csv-export.service.spec.ts
  api/test/unit/services/user.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts
  sites/partners/src/lib/hooks.ts
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/account/edit.tsx
Labels: ready to merge, prisma rewrite

#3897 fix: null check on option links
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
Labels: ready to merge

#3908 feat: limit user names allowed
  api/src/services/user.service.ts
Labels: ready to merge

#3901 fix: the Save and Return link should only show after the Review step has been reached
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/pages/applications/review/summary.tsx
Labels: ready to merge

#3902 fix: 3898/passwordless schema changes
  api/prisma/migrations/03_mfa_code_to_single_use_code/migration.sql
  api/prisma/migrations/04_allow_single_use_code_login_jurisdiction_flag/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/dtos/jurisdictions/jurisdiction.dto.ts
  api/src/passports/mfa.strategy.ts
  api/src/services/auth.service.ts
  api/src/services/email.service.ts
  api/src/services/sms.service.ts
  api/test/integration/auth.e2e-spec.ts
  api/test/integration/jurisdiction.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/unit/passports/mfa.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
Labels: ready to merge
