Repository bloom-housing/bloom, pull requests merged in 2025-06, with the labels that each got.

#4909 test: frontend integration tests public src pages account edit
  sites/public/__tests__/pages/account/edit.test.tsx
Labels: ready to merge

#4912 fix: enableAdditionalResources feature flag fix
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  sites/public/src/components/home/HomeResources.tsx
Labels: ready to merge

#4930 fix: multiselect question public hook
  api/src/permission-configs/permission_policy.csv
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/listings-closed.tsx
  sites/public/src/pages/listings.tsx
Labels: ready to merge

#4914 fix: update navbar to match jurisdiction color
  sites/public/src/layouts/application-form.module.scss
Labels: ready to merge

#4900 feat: under construction home page
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/components/ClickableCard.tsx
  sites/public/__tests__/home/Home.test.tsx
  sites/public/__tests__/home/HomeUnderConstruction.test.tsx
  sites/public/src/components/browse/ListingCard.module.scss
  sites/public/src/components/home/Home.module.scss
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/home/HomeRegions.tsx
  sites/public/src/components/home/HomeSection.module.scss
  sites/public/src/components/home/HomeSection.tsx
  sites/public/src/components/home/HomeUnderConstruction.tsx
  sites/public/src/components/home/MinimalListingCard.module.scss
  sites/public/src/components/home/MinimalListingCard.tsx
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/index.tsx
Labels: ready to merge

#4926 feat: update card footers in Common App to use new styles
  sites/public/src/pages/applications/household/member.tsx
  sites/public/src/pages/applications/review/confirmation.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/review/terms.tsx
  sites/public/src/pages/applications/start/autofill.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/applications/start/community-disclaimer.tsx
  sites/public/src/pages/applications/start/what-to-expect.tsx
Labels: ready to merge

#4939 fix: see all under construction button
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  sites/public/__tests__/home/HomeUnderConstruction.test.tsx
  sites/public/src/components/home/HomeUnderConstruction.tsx
Labels: ready to merge

#4936 fix: Unit groups drawer previous data bug
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
Labels: ready to merge

#4935 fix: five digit waitlist size
  shared-helpers/package.json
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: ready to merge

#4941 4917/unit group closed waitlist bug
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
Labels: ready to merge

#4974 fix: change path to housing-basics
  sites/public/src/components/assistance/Assistance.tsx
Labels: ready to merge

#4934 feat: handle unit group unit types in common app
  shared-helpers/__tests__/unitTypes.test.ts
  shared-helpers/src/utilities/unitTypes.ts
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/lib/applications/configInterfaces.ts
  sites/public/src/pages/applications/household/preferred-units.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: ready to merge

#4976 feat: 404 page, hero pattern
  shared-helpers/src/locales/general.json
  sites/public/__tests__/pages/404.test.tsx
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/home/HomeDeprecated.tsx
  sites/public/src/components/page/Content404.tsx
  sites/public/src/components/page/Content404Deprecated.tsx
  sites/public/src/components/page/ContentError.tsx
  sites/public/src/components/page/ContentErrorDeprecated.tsx
  sites/public/src/components/page/HeroDeprecated.module.scss
  sites/public/src/components/page/HeroDeprecated.tsx
  sites/public/src/pages/404.tsx
  sites/public/src/pages/_error.tsx
  sites/public/src/patterns/Hero.module.scss
  sites/public/src/patterns/Hero.tsx
Labels: ready to merge

#4979 fix: update seed with due date
  api/prisma/seed-helpers/listing-factory.ts
Labels: ready to merge

#4981 fix: null event target
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
Labels: bug, ready to merge

#4972 Fix: Hide Listing preferences based on jurisdiction feature flags
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/listings/PaperListingForm/index.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/PreferencesAndPrograms.test.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/PreferencesAndPrograms.tsx
  sites/public/__tests__/components/listing/ListingView.test.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
Labels: ready to merge

#4910 feat: align dependabot config file
  .github/dependabot.yml
  README.md
Labels: ready to merge

#4940 fix: functioning search and multiselect
  api/prisma/seed-staging.ts
  shared-helpers/src/locales/general.json
  sites/public/__tests__/components/browse/FilterDrawer.test.tsx
  sites/public/__tests__/components/browse/FilterDrawerHelpers.test.tsx
  sites/public/__tests__/components/browse/ListingBrowse.test.tsx
  sites/public/src/components/browse/FilterDrawer.module.scss
  sites/public/src/components/browse/FilterDrawer.tsx
  sites/public/src/components/browse/FilterDrawerHelpers.tsx
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/pages/listings-closed.tsx
  sites/public/src/pages/listings.tsx
Labels: ready to merge

#4983 Feat: unit group form integration tests
  shared-helpers/__tests__/testHelpers.ts
  sites/partners/__tests__/components/listings/PaperListingForm/UnitGroupForm.test.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
Labels: ready to merge

#5001 refactor: apply jurisdictional theme class in prod
  sites/public/src/pages/_app.tsx
Labels: ready to merge

#4980 refactor: mixed availability
  api/prisma/seed-staging.ts
  sites/public/src/components/listing/ListingViewSeeds.module.scss
  sites/public/src/components/listing/listing_sections/Apply.tsx
  sites/public/src/components/listing/listing_sections/Availability.tsx
  sites/public/src/components/listing/listing_sections/DateSection.tsx
  sites/public/src/components/listing/listing_sections/InfoCard.tsx
  sites/public/src/components/listing/listing_sections/LeasingAgent.tsx
  sites/public/src/components/listing/listing_sections/LotteryResults.tsx
Labels: wip

#5004 fix: common app selection
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/cypress/fixtures/minimalListing.json
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/public/src/pages/404.tsx
Labels: ready to merge

#4994 Fix: Fix missing accessibility tag
  sites/public/__tests__/components/listing/listing_sections/MainDetails.test.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/home/MinimalListingCard.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
Labels: ready to merge

#4538 docs: update readme
  README.md
Labels: ready to merge

#4978 fix: show closed waitlist
  shared-helpers/__tests__/views/summaryTables.test.ts
  shared-helpers/src/views/summaryTables.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
Labels: ready to merge

#5016 fix: fix accessibility tag
  sites/public/__tests__/components/browse/ListingCard.test.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
Labels: 1 review needed

#4992 test: add unit testing for the Lottery Results page in Public
  shared-helpers/__tests__/testHelpers.ts
  sites/public/__tests__/pages/account/application/[id]/lottery-results.test.tsx
  sites/public/src/pages/account/application/[id]/lottery-results.tsx
Labels: ready to merge
