Repository bloom-housing/bloom, pull requests merged in 2025-04, with the labels that each got.

#4758 refactor: design qa for seeds homepage
  shared-helpers/src/views/CustomIconMap.tsx
  sites/public/src/components/home/Home.module.scss
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/shared/CustomSiteFooter.module.scss
  sites/public/src/components/shared/CustomSiteFooter.tsx
  sites/public/src/layouts/max-width.module.scss
  sites/public/src/pages/404.tsx
  sites/public/src/pages/_error.tsx
Labels: ready to merge

#4738 feat: availability filters
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-helpers/unit-group-factory.ts
  api/src/enums/listings/filter-availability-enum.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#4693 feat: seeds siteheader
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/public/src/layouts/application.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/patterns/SiteHeader.module.scss
  sites/public/src/patterns/SiteHeader.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#4766 fix: add the ability to disable jurisdictional admin
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/users/FormUserManage.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/09-lottery.spec.ts
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/components/users/JurisdictionAndListingSelection.tsx
Labels: ready to merge

#4714 chore: upgrade axios
  api/package.json
  api/yarn.lock
  shared-helpers/src/auth/catchNetworkError.ts
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: dependencies, ready to merge

#4773 fix: remove automatic paragraph spacing from layout
  sites/public/src/layouts/max-width.module.scss
  sites/public/src/pages/404.tsx
  sites/public/src/pages/_error.tsx
Labels: ready to merge

#4703 feat: add a Favorite button and My Favorites view to the Public app
  api/prisma/seed-staging.ts
  api/src/controllers/user.controller.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/enums/user/view-enum.ts
  api/src/services/user.service.ts
  api/test/integration/user.e2e-spec.ts
  shared-helpers/index.ts
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/exceptions.ts
  shared-helpers/src/views/CustomIconMap.tsx
  shared-helpers/src/views/components/BloomCard.module.scss
  shared-helpers/src/views/components/BloomCard.tsx
  sites/public/cypress/e2e/pages/my-favorites.spec.ts
  sites/public/cypress/support/commands.js
  sites/public/src/components/account/FavoritesView.module.scss
  sites/public/src/components/account/FavoritesView.tsx
  sites/public/src/components/browse/ListingBrowse.module.scss
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
  sites/public/src/components/shared/FavoriteButton.tsx
  sites/public/src/layouts/application.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/lib/hooks.ts
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/pages/account/favorites/index.tsx
  sites/public/src/pages/listing/[id]/[slug].tsx
  sites/public/src/pages/listings.tsx
  sites/public/src/pages/sign-in.tsx
  sites/public/src/patterns/PageHeaderLayout.module.scss
  sites/public/src/patterns/PageHeaderLayout.tsx
Labels: ready to merge

#4785 fix: seeds a11y misc improvements
  sites/public/src/components/listing/listing_sections/Eligibility.tsx
  sites/public/src/patterns/CollapsibleSection.tsx
  sites/public/src/patterns/OrderedSection.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#4716 chore: upgrade postcss
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: dependencies, ready to merge

#4796 fix: allow favorites to work in deployed environments
  sites/public/src/pages/sign-in.tsx
Labels: ready to merge

#4718 chore: upgrade webpack
  api/package.json
  api/yarn.lock
  sites/partners/package.json
  sites/public/package.json
  yarn.lock
Labels: dependencies, ready to merge

#4769 feat: home page regions
  shared-helpers/src/locales/general.json
  shared-helpers/src/views/CustomIconMap.tsx
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/home/HomeRegions.module.scss
  sites/public/src/components/home/HomeRegions.tsx
  sites/public/src/components/home/HomeSection.module.scss
  sites/public/src/components/home/HomeSection.tsx
Labels: ready to merge

#4779 feat: swap programs with community types
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/ar.json
  shared-helpers/src/locales/bn.json
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/listings/PaperListingDetails/sections/DetailCommunityType.test.tsx
  sites/partners/__tests__/components/listings/PaperListingDetails/sections/DetailPrograms.test.tsx
  sites/partners/__tests__/components/listings/PaperListingDetails/sections/DetailUnits.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/CommunityType.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/PreferencesAndPrograms.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailCommunityType.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/PreferencesAndPrograms.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/public/__tests__/components/listing/ListingViewSeedsHelpers.test.ts
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/Availability.tsx
Labels: ready to merge

#4782 feat: add tag for Home Type on listings
  api/prisma/seed-helpers/listing-data/blue-sky-apartments.ts
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/components/account/FavoritesView.tsx
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
Labels: ready to merge

#4789 feat: seeds page header on listings browse
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/patterns/PageHeaderLayout.module.scss
  sites/public/src/patterns/PageHeaderLayout.tsx
Labels: ready to merge

#4806 feat: public neighborhood amenities
  shared-helpers/src/locales/general.json
  sites/public/__tests__/components/listing/listing_sections/Neighborhood.test.tsx
  sites/public/src/components/listing/ListingViewSeeds.module.scss
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/AdditionalFees.tsx
  sites/public/src/components/listing/listing_sections/Features.tsx
  sites/public/src/components/listing/listing_sections/Neighborhood.tsx
Labels: ready to merge

#4780 feat: partners unit groups integration
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/general.json
  sites/partners/__tests__/components/listings/PaperListingDetails/sections/DetailUnits.test.tsx
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupAmiForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/lib/listings/ListingDataPipeline.ts
  sites/partners/src/lib/listings/UnitGroupsFormatter.ts
  sites/partners/src/lib/listings/formTypes.ts
Labels: ready to merge

#4752 feat: FE - public unit groups
  api/prisma/seed-staging.ts
  api/src/dtos/unit-groups/unit-group-summary.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/utilities/unit-groups-transformations.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/unit-group-transformations.spec.ts
  shared-helpers/__tests__/views/summaryTables.test.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/summaryTables.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/RentSummary.tsx
  sites/public/src/lib/helpers.tsx
Labels: 1 review needed

#4791 feat: add feature flag for disabling common app
  api/prisma/seed-helpers/listing-data/lakeview-villa.ts
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
Labels: ready to merge

#4816 4572/listings application add integration tests
  sites/partners/__tests__/components/applications/sections/FormAlternateContact.test.tsx
  sites/partners/__tests__/components/applications/sections/FormApplicationData.test.tsx
  sites/partners/__tests__/components/applications/sections/FormDemographics.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdIncome.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx
  sites/partners/__tests__/components/applications/sections/FormMultiselectQuestions.test.tsx
  sites/partners/__tests__/components/applications/sections/FormPrimaryApplicant.test.tsx
  sites/partners/__tests__/components/applications/sections/FormTerms.test.tsx
  sites/partners/__tests__/components/applications/sections/helpers.tsx
  sites/partners/__tests__/pages/listings/[id]/applications/add.test.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
Labels: ready to merge

#4719 chore: upgrade node-polyglot
  api/package.json
  api/prisma/seed-helpers/jurisdiction-factory.ts
  api/prisma/seed-staging.ts
  api/yarn.lock
  shared-helpers/package.json
  yarn.lock
Labels: dependencies, ready to merge

#4722 chore: upgrade ts-loader
  api/package.json
  api/yarn.lock
  shared-helpers/package.json
  sites/public/package.json
  yarn.lock
Labels: dependencies, ready to merge

#4799 feat: add filters for unitGroups
  api/prisma/seed-helpers/unit-group-factory.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
Labels: ready to merge

#4833 fix: remove token max length
  api/src/dtos/auth/confirm.dto.ts
  api/src/dtos/auth/update-password.dto.ts
Labels: ready to merge

#4823 fix: allow duplication to not copy unit groups
  api/prisma/seed-helpers/feature-flag-factory.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
Labels: ready

#4835 fix: listing status sort bug
  api/src/utilities/build-order-by.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/build-order-by.spec.ts
Labels: bug, ready to merge
