Repository bloom-housing/bloom, pull requests merged in 2025-07, with the labels that each got.

#5029 fix: detroit prod data qa
  shared-helpers/__tests__/stringFormatting.test.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/utilities/stringFormatting.ts
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/public/__tests__/components/browse/ListingBrowse.test.tsx
  sites/public/__tests__/components/listing/ListingViewSeeds.test.tsx
  sites/public/__tests__/components/listing/ListingViewSeedsHelpers.test.ts
  sites/public/__tests__/components/listing/listing_sections/AdditionalFees.test.tsx
  sites/public/__tests__/components/listing/listing_sections/RentSummary.test.tsx
  sites/public/__tests__/lib/helpers.test.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/AdditionalFees.module.scss
  sites/public/src/components/listing/listing_sections/AdditionalFees.tsx
  sites/public/src/components/listing/listing_sections/Apply.tsx
  sites/public/src/components/listing/listing_sections/Availability.tsx
  sites/public/src/components/listing/listing_sections/Eligibility.tsx
  sites/public/src/components/listing/listing_sections/RentSummary.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/lib/hooks.ts
Labels: ready to merge

#5025 feat: add new feature flag UI
  api/prisma/migrations/27_add_super_admin/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/user-factory.ts
  api/prisma/seed-staging.ts
  api/src/dtos/users/user-role.dto.ts
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/__tests__/pages/admin/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/pages/admin/index.tsx
Labels: ready to merge

#5037 4993/update unit groups displayed if needed
  shared-helpers/__tests__/unitTypes.test.ts
  shared-helpers/src/utilities/unitTypes.ts
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/public/__tests__/pages/account/application/[id]/index.test.tsx
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/applications/ApplicationConductor.ts
  sites/public/src/lib/applications/PreferredUnitSizeStep.ts
  sites/public/src/lib/helpers.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#5026 feat: api partners full time student paper application questions
  api/prisma/migrations/27_add_full_time_student_fields/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/dtos/applications/applicant.dto.ts
  api/src/dtos/applications/household-member.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/application-exporter.service.ts
  api/src/services/application.service.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application-exporter.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/utilities/application-export-helpers.spec.ts
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/blankApplication.ts
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx
  sites/partners/__tests__/components/applications/sections/FormPrimaryApplicant.test.tsx
  sites/partners/__tests__/pages/application/index.test.tsx
  sites/partners/__tests__/pages/listings/applications/index.test.tsx
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/lib/applications/FormTypes.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
  sites/partners/src/pages/application/[id]/index.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
Labels: ready to merge

#5043 test: remove index from data-testid on public site
  sites/public/cypress/support/commands.js
  sites/public/src/patterns/SiteHeader.tsx
Labels: ready to merge

#5055 fix: add null checks
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/public/src/pages/applications/financial/income.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: ready to merge

#5065 fix: clean up finder styling
  sites/public/src/components/finder/RentalsFinder.module.scss
  sites/public/src/components/finder/RentalsFinder.tsx
Labels: ready to merge

#5005 feat: custom filtering empty state
  shared-helpers/src/locales/general.json
  sites/public/__tests__/components/browse/ListingBrowse.test.tsx
  sites/public/__tests__/testUtils.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/browse/ListingBrowse.module.scss
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/pages/listings-closed.tsx
  sites/public/src/pages/listings.tsx
Labels: ready to merge

#5076 feat: preview listing will now show the Seeds version
  sites/public/src/pages/preview/listings/[id].tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#5066 fix: fix unit group occupancy table duplicates
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/src/utilities/mergeDeep.ts
  shared-helpers/src/utilities/resolveObject.ts
  shared-helpers/src/views/occupancyFormatting.tsx
  shared-helpers/tsconfig.json
  sites/partners/__tests__/testUtils.tsx
  sites/partners/src/lib/helpers.ts
  sites/public/__tests__/pages/listing/index.test.tsx
Labels: ready to merge

#5017 feat: other ada option
  api/prisma/migrations/27_other_ada_option/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/dtos/applications/accessibility.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/services/application-exporter.service.ts
  api/src/services/application.service.ts
  api/src/utilities/application-export-helpers.ts
  api/test/unit/services/application-exporter.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/utilities/application-export-helpers.spec.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsHouseholdDetails.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdDetails.tsx
  sites/partners/src/pages/application/[id]/index.tsx
  sites/public/__tests__/testUtils.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/components/applications/SubmittedApplicationView.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/pages/applications/household/ada.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/start/autofill.tsx
  sites/public/src/pages/preview/listings/[id].tsx
Labels: ready to merge

#5084 fix: cant unselect unit types in paper applications
  api/src/services/application.service.ts
  api/test/unit/services/application.service.spec.ts
  sites/partners/src/lib/applications/formatApplicationData.ts
Labels: ready to merge

#5095 fix: add missing app methods to seed data
  api/prisma/seed-helpers/listing-data/hollywood-hills-heights.ts
  api/prisma/seed-helpers/listing-data/little-village-apartments.ts
Labels: bug, ready to merge

#5059 fix: show hmi ranges if multiple ami charts are used
  api/prisma/seed-helpers/ami-chart-factory.ts
  api/prisma/seed-staging.ts
  api/src/utilities/unit-groups-transformations.ts
  api/src/utilities/unit-utilities.ts
  api/test/unit/utilities/unit-group-transformations.spec.ts
  sites/partners/__tests__/components/listings/PaperListingForm/UnitGroupForm.test.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupAmiForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/public/__tests__/components/listing/ListingViewSeedsHelpers.test.ts
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
Labels: ready to merge

#5099 fix: add missing app method pt2
  api/prisma/seed-helpers/listing-data/district-view-apartments.ts
  api/prisma/seed-helpers/listing-data/sunshine-flats.ts
  api/prisma/seed-helpers/listing-data/valley-heights-senior-community.ts
Labels: ready to merge

#5073 fix: Fix search page waitlist status closed label bug
  shared-helpers/__tests__/views/summaryTables.test.ts
  shared-helpers/src/views/summaryTables.tsx
Labels: ready to merge

#5104 feat: bash fixes 1
  shared-helpers/src/utilities/photos.ts
  sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/Apply.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
Labels: ready to merge

#5108 test: authenticate with api when not testing sign in
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/04-application.spec.ts
  sites/partners/cypress/e2e/default/05-paperApplication.spec.ts
  sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts
  sites/partners/cypress/e2e/default/07-jurisdictional-admin-user-management.spec.ts
  sites/partners/cypress/e2e/default/08-preference-management.spec.ts
  sites/partners/cypress/e2e/default/09-lottery.spec.ts
  sites/partners/cypress/e2e/listings-approval/listings-approval.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
Labels: ready to merge

#5102 chore: update filter drawer label for unit groups enabled
  shared-helpers/src/locales/general.json
  sites/public/src/components/browse/FilterDrawer.tsx
  sites/public/src/components/browse/FilterDrawerHelpers.tsx
  sites/public/src/components/browse/ListingBrowse.tsx
Labels: ready to merge

#5113 feat: remove work in region question
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  api/src/utilities/application-export-helpers.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/components/applications/ApplicationsColDefs.ts
  sites/partners/src/components/applications/PaperApplicationDetails/sections/DetailsPrimaryApplicant.tsx
  sites/partners/src/components/applications/PaperApplicationForm/PaperApplicationForm.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/public/__tests__/pages/applications/contact/address.test.tsx
  sites/public/src/pages/applications/contact/address.tsx
Labels: ready to merge

#5125 fix: use listing assets only when array, refactor of photo helper
  shared-helpers/src/utilities/photos.ts
Labels: ready to merge

#5116 chore: improve seed data
  api/prisma/seed-helpers/listing-data/blue-sky-apartments.ts
  api/prisma/seed-helpers/listing-data/hollywood-hills-heights.ts
  api/prisma/seed-helpers/listing-data/lakeview-villa.ts
  api/prisma/seed-helpers/listing-data/little-village-apartments.ts
  api/prisma/seed-helpers/listing-data/sunshine-flats.ts
  api/prisma/seed-helpers/listing-data/valley-heights-senior-community.ts
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-staging.ts
Labels: ready to merge

#5169 fix: use the right backend availability key
  sites/public/src/components/browse/FilterDrawer.tsx
Labels: high priority, ready to merge

#5101 feat: frontend required fields
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/package.json
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/index.test.tsx
  sites/partners/__tests__/components/listings/PaperListingForm/sections/CommunityType.test.tsx
  sites/partners/__tests__/lib/helpers.test.ts
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/__tests__/pages/settings/index.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/package.json
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/ListingForm.module.scss
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupAmiForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/AdditionalDetails.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/AdditionalEligibility.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/CommunityType.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingIntro.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingVerification.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/NeighborhoodAmenities.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/shared/SectionWithGrid.tsx
  sites/partners/src/components/shared/TextEditor.module.scss
  sites/partners/src/components/shared/TextEditor.tsx
  sites/partners/src/lib/helpers.tsx
  sites/public/__tests__/pages/listing/index.test.tsx
  sites/public/package.json
  sites/public/src/components/shared/FormSummaryDetails.tsx
  yarn.lock
Labels: ready to merge

#5175 fix: text editor a11y improvements
  sites/partners/__tests__/components/listings/PaperListingForm/index.test.tsx
  sites/partners/src/components/shared/TextEditor.module.scss
  sites/partners/src/components/shared/TextEditor.tsx
Labels: ready to merge

#5164 fix: hide the How to Apply section if external url is blank
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
Labels: ready to merge

#5054 feat: add marketing sort ordering
  api/prisma/migrations/28_change_marketing_date_to_marketing_year/migration.sql
  api/prisma/schema.prisma
  api/src/dtos/listings/listing.dto.ts
  api/src/enums/listings/order-by-enum.ts
  api/src/services/listing-csv-export.service.ts
  api/src/utilities/build-order-by.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/lib/listings/DatesFormatter.ts
  sites/partners/src/lib/listings/formTypes.ts
  sites/public/__tests__/components/listing/listing_sections/Availability.test.tsx
  sites/public/__tests__/lib/helpers.test.tsx
  sites/public/src/components/listing/listing_sections/Availability.tsx
  sites/public/src/lib/helpers.tsx
  sites/public/src/lib/hooks.ts
Labels: ready to merge

#5187 fix: improve rich text a11y pt 2
  sites/partners/src/components/shared/TextEditor.tsx
Labels: ready to merge

#5140 Fix: Fix occupancy formatting for multiple unit groups with only max or min values
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/src/views/occupancyFormatting.tsx
Labels: ready to merge
